### ISSUE TITLE
Unexpected behavior of Time.captureFramerate and Time.time

### ISSUE THREAD

**Issue by hejcz** [Unity-Technologies/ml-agents#1302] opened 2018-10-08 18:30 UTC
To measure time in game for example to exit level after some time I use Time.time function. I've seen that it is used in example environments as well. In 2018.2.11f and 2018.3.0b4 Unity releases manipulating time scale in academy object ends up with strange time behavior. 

Time.time seems to be too fast even though scale is set to 1. Changing timeScale has no effect. Debug shows that it is 1 indeed. Commenting out Time.captureFramerate = 60; in Academy ConfigureEnvironmentHelper method solves the problem. I don't know Unity too good so I don't know what's wrong. 2018.1.0b13 release seems to not have this problem.

**Comment by hejcz** [comment] 2018-10-16 20:55
@mmattar , should I wait for some response from you as you assigned yourself to this task?

**Comment by hejcz** [comment] 2018-10-21 09:46
@vincentpierre, do you know what's the status of this issue? It's crucial for me because I don't know if commenting out Time.captureFramerate = 60 won't break anything as I use visual observations.

**Comment by vincentpierre** [comment] 2018-10-22 19:21
`Time.captureFramerate` ensures that the Update and FixedUpdate frequency are matched. Time.captureFrameRate does not modify the speed of the simulation at all, but it might modify the frequency of Updates and FixedUpdates. Did you make sure that all displacements were scaled with [Time.deltaTime](https://docs.unity3d.com/ScriptReference/Time-deltaTime.html) in Update methods and Time.fixedDeltaTime in the FixedUpdate method ?

**Comment by hejcz** [comment] 2018-10-22 20:41
Having MonoBehavior as simple as:
`public class Timer : MonoBehaviour
{
    public float Value;

    private void Update()
    {
        Value = Time.time;
    }
}`
Just check in Unity UI how Value changes when mentioned line is commented out and present in the code. For me Value changes much faster when this line is present. As far as I understand Time.time represents scaled time from some moment. This MonoBehavior is attached to Agent object in my case.

**Comment by vincentpierre** [comment] 2018-10-22 23:11
When CaptureFrameRate is on, the time seems to flow a lot slower. CaptureFrameRate forces Unity to assume that Updates take exactly 1/60 seconds regardless of how long it actually takes. We use it to make sure that when the simulation is speed up, the number of Updates per second / time scale remains unchanged. We can get more consistent training this way. I will label this as a bug and we will investigate. In the meantime, could you try deactivating Time.CaptureFrameRate at inference time and leave it at training time?

**Comment by hejcz** [comment] 2018-10-23 06:09
Yes, I can but I'm afraid that during training it might not work. If my agent wont have enough time to figure out what to do training will be useless as every 15 sec i reset the map. Im gonna wait for the results of investihation.

**Comment by LeSphax** [comment] 2018-10-28 15:42
I just spent some time debugging why my game was running slowly and the fixedUpdate frequency was weird. So it turns out Time.captureFramerate was the cause for me as well.

So if I understand well, this makes sure that the FixedUpdate and Update frequencies stay consistent independently of the actual framerate that the game is running at.

So it makes my game speed look inconsistent to me at inference time because the frequency of FixedUpdate is not always 50/s anymore.
But, as long as I don't rely on Time.realTimeSinceStartup,  I shouldn't worry about it because the game speed will appear consistent to my agent. Is that it?

**Comment by itggot-linus-styren** [comment] 2018-11-10 17:41
I had this issue as well and I just added an argument isInference to ConfigureEnvironmentHelper and made this workaround:
```
if (!isInference) Time.captureFramerate = 60;
```

Hopefully this will be fixed soon.

**Comment by nathanvogel** [comment] 2019-01-18 16:44
I also ran into this issue, but when building for Windows, Android, etc. Time.captureFramerate makes Unity builds run at **very** different speeds than in the editor!  This is super unintuitive to debug, because Time.timeScale is always 1, but suddenly everything runs at different speeds (including WaitForSeconds, physics, etc.)

For now, I'm overriding the captureFramerate on AcademyReset like this:
```
if (GetIsInference())
    Time.captureFramerate = 0;
```
But will agents perceive the environment in the same way during training and inference?

Also, this is doubly annoying, because I based my physics settings on what the editor showed me and now my previously trained models are completely lost with the newly adjusted physics settings.

**Comment by vincentpierre** [comment] 2019-04-03 22:22
After investigation, using capture frame rate fixes the Time.deltaTime regardless of how long a frame actually takes. We need it for training in order to make sure that when speeding up the environment, the Time.deltaTime will be consistent with regular speed game time. In order to train the game at faster speeds, the game time scale must be increased without breaking the game. You can either put all of the logic into the Fixed Update or make sure the actual game FPS is close to the capture frame rate (and turn off capture frame rate at inference). If capture frame rate is 60 but the game FPS is 30, then the game will be going twice slower (because doing 30 FPS with half the delta time).

**Comment by DVonk** [comment] 2019-05-22 02:06
@vincentpierre So, does it break anything if I only use captureFramerate for training and deactivate it in inference? I just came across this as well. 
My game speed is completely dependent on the framerate now with captureFramerate set to 60. Using the Roller Ball environment as an example: the ball is moving about three times as fast on my laptop (200fps) than it is on my computer (70fps). My particle system is moving three times faster as well. Even when I change scenes everything's too fast. 

This is really annoying and seems to go against everything I've learned. It's not possible to make my game framerate-independent if this is set. Does it break anything if I deactivate this for inference or not? And if it doesn't, you should probably add that check in the official release since this pretty much breaks every scene that has an Academy in it for real games.

**Comment by vincentpierre** [comment] 2019-05-22 18:24
@DVonk I cannot guarantee that removing capture frame rate at inference will not break the agent's behaviors. It does work in a lot of cases where the actual FPS is close to the set captureFrameRate of training.

**Comment by DVonk** [comment] 2019-05-22 20:19
@vincentpierre Am I just missing something then? It doesn't seem possible to use ML-Agents in a real game if the framerate just changes the entire game speed. With it set to 60 even the use of AddForce is dependent on the framerate. I don't see anyone shipping a game where people with good computers are forced to play at three times the speed of people with bad ones?

**Comment by vincentpierre** [comment] 2019-05-22 20:29
If you want to remove the capture frame rate during inference, you need to make sure that the agent's behavior is going to be consistent. You still need capture frame rate for training and you should set is close to your target frame rate. Additionally, you should set the timeScale to a large enough value that it trains fast and small enough so the behavior of the agent is not modified.
I hope it makes sense. There is currently no nice way to speed up training but we working on it.

**Comment by surfnerd** [comment] 2019-10-02 18:03
Hello, thank you for this discussion.  We are closing it now due to inactivity.  Please reopen it if you'd like to further discuss this topic.

**Closed by surfnerd** 2019-10-02 18:03 UTC
Labels: bug
