### ISSUE TITLE
ModuleNotFoundError: No module named 'win32api'

### ISSUE THREAD

**Issue by TrollOfAllTrolls** [Unity-Technologies/ml-agents#1362] opened 2018-10-19 03:18 UTC
So I've tried to run the learn.py program using the following command:
mlagents-learn /config/config_trainer.yaml --train --run-id=test

However, it keeps returning this error:
Traceback (most recent call last):
  File "c:\users\jpste\anaconda3\envs\ml-agents\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\jpste\anaconda3\envs\ml-agents\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\jpste\Anaconda3\envs\ml-agents\Scripts\mlagents-learn.exe\__main__.py", line 5, in <module>
  File "c:\users\jpste\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py", line 9, in <module>
    from trainer_controller import TrainerController
ModuleNotFoundError: No module named 'trainer_controller'

I followed the instructions as told multiple times, restarting a few instances, yet I keep getting this error. I'm honestly lost as to what I did wrong at this point...

**Comment by awjuliani** [comment] 2018-10-19 17:53
Hi @TrollOfAllTrolls,

Can you let me know what platform you are using, and how you installed the `mlagents` python package?

**Comment by TrollOfAllTrolls** [comment] 2018-10-20 13:58
Oh right, I should have clarified that I'm using windows. I used Anaconda to install the mlagents python package, first creating the ml-agents environment. I then installed all the necessary content from the requirements file in the ml-agents folder

**Comment by chrizstvan** [comment] 2018-10-24 04:13
i have same issue
No module named 'trainer_controller',
 i'm using Mac OSX

**Comment by awjuliani** [comment] 2018-12-18 01:21
Hi @TrollOfAllTrolls 

We have updated our installation process for v0.6, could you try it using the new system and see if the error persists?

**Comment by whiteGhost333** [comment] 2019-01-15 05:20
Hello,
Excuse me for jumping in, but, this is wigging me out.  I also have an Anaconda, tensorflow  installation and I went back to 2017.4.18 which seems the safest.  I was working with 2018.2.14 and actually had better luck in that in one shining moment I was able to connect with 3DBall environment but could never get it to repeat the trick.

Here's a python log which has me in a choke hold : 
(ml-agents) c:\Users\msi\Downloads\ml-agents>mlagents-learn C:\Users\msi\Downloads\ml-agents\config\trainer_config.yaml --env=3DBall --train
Traceback (most recent call last):
  File "C:\Users\msi\Anaconda3\envs\ml-agents\Scripts\mlagents-learn-script.py", line 11, in <module>
    load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')()
  File "C:\Users\msi\Anaconda3\envs\ml-agents\lib\site-packages\pkg_resources\__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\msi\Anaconda3\envs\ml-agents\lib\site-packages\pkg_resources\__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "C:\Users\msi\Anaconda3\envs\ml-agents\lib\site-packages\pkg_resources\__init__.py", line 2346, in load
    return self.resolve()
  File "C:\Users\msi\Anaconda3\envs\ml-agents\lib\site-packages\pkg_resources\__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\msi\downloads\ml-agents\ml-agents\mlagents\trainers\__init__.py", line 5, in <module>
    from .trainer_controller import *
  File "c:\users\msi\downloads\ml-agents\ml-agents\mlagents\trainers\trainer_controller.py", line 11, in <module>
    import win32api
ModuleNotFoundError: No module named 'win32api'

Any pointers or comments would be greatly appreciated.

Thanks!

**Comment by xiaomaogy** [comment] 2019-01-16 01:53
@whiteGhost333 Which version of the code are you using and which platform are you running this on?

**Comment by xiaomaogy** [comment] 2019-01-16 02:17
Oh I was able to reproduce this. You just need to type "pip install pypiwin32" to fix this. I will put a fix for this.

**Comment by whiteGhost333** [comment] 2019-01-16 16:46
windows pro 10, 2017.4.18, tensorflow 1.7.1   python 3.6 & ml-agents 0.6.

I'll give the command stream a go.

**Comment by whiteGhost333** [comment] 2019-01-16 18:12
Below are the results in anaconda. It was apparently the command was successful, but, an even more baffling error occurred...

(base) C:\Users\msi>activate ml-agents

(ml-agents) C:\Users\msi>pip install pypiwin32
Collecting pypiwin32
  Downloading https://files.pythonhosted.org/packages/d0/1b/2f292bbd742e369a100c91faa0483172cd91a1a422a6692055ac920946c5/pypiwin32-223-py3-none-any.whl
Collecting pywin32>=223 (from pypiwin32)
  Downloading https://files.pythonhosted.org/packages/b2/1a/7727b406391b0178b6ccb7e447e963df5ebf1ce9e0f615fc6ce23b6f6753/pywin32-224-cp36-cp36m-win_amd64.whl (9.1MB)
    100% |████████████████████████████████| 9.1MB 2.3MB/s
Installing collected packages: pywin32, pypiwin32
Successfully installed pypiwin32-223 pywin32-224


(ml-agents) C:\Users\msi>c:\Users\msi\Downloads\ml-agents>mlagents-learn C:\Users\msi\Downloads\ml-agents\config\trainer_config.yaml --env=3DBall --train
'c:\Users\msi\Downloads\ml-agents' is not recognized as an internal or external command,
operable program or batch file.

**Comment by xiaomaogy** [comment] 2019-01-16 18:59
@whiteGhost333 Can you post a snapshot of the message you see?

**Comment by whiteGhost333** [comment] 2019-01-16 19:38
@xiaomaogy It is in the tail end of my last message.

Here is a newer one from my last attempt.

(ml-agents) C:\Users\msi>(ml-agents) C:\Users\msi>c:\Users\msi\Downloads\ml-agents>mlagents-learn C:\Users\msi\Downloads\ml-agents\config\trainer_config.yaml --env=3DBall --train
C:\Users\msi was unexpected at this time.

**Comment by xiaomaogy** [comment] 2019-01-16 21:40
@whiteGhost333 It seems that the error message you received says your path C:\Users\msi doesn't exist or something similar.

**Comment by whiteGhost333** [comment] 2019-01-16 22:50
Not really...


(base) C:\Users\msi>activate ml-agents

(ml-agents) C:\Users\msi>cd
C:\Users\msi

(ml-agents) C:\Users\msi>conda info --envs
# conda environments:
#
base                     C:\Users\msi\Anaconda3
ml-agents             *  C:\Users\msi\Anaconda3\envs\ml-agents


(ml-agents) C:\Users\msi>

**Comment by xiaomaogy** [comment] 2019-01-17 19:30
This might also be because your "mlagents-learn" command hasn't been installed correctly. Have you done "pip install . " within your ml-agents folder that contains setup.py? Has the ml-agents 0.6 python package been installed successfully?

**Comment by xiaomaogy** [comment] 2019-01-18 03:08
pip install -e . is the same, it just uses the local version of the code instead of the v0.6 one.

**Comment by whiteGhost333** [comment] 2019-01-18 04:03
Voila !!!..I was able to connect to the 3Dball scene build...this is after
running  pip install pypiwin32, of course.  See below.  One item which
surprised me was that I did get the build results
I expected , i.e. the learning brains are int scene but not the build.  I
must have missed something there?

(ml-agents) C:\Users\msi>mlagents-learn
C:\Users\msi\Downloads\ml-agents\config\trainer_config.yaml
--env=C:\Users\msi\Downloads\ml-agents\ml-agents\3DBall_Exp1 --train


                        ▄▄▄▓▓▓▓
                   ╓▓▓▓▓▓▓█▓▓▓▓▓
              ,▄▄▄m▀▀▀'  ,▓▓▓▀▓▓▄                           ▓▓▓  ▓▓▌
            ▄▓▓▓▀'      ▄▓▓▀  ▓▓▓      ▄▄     ▄▄ ,▄▄ ▄▄▄▄   ,▄▄ ▄▓▓▌▄ ▄▄▄
  ,▄▄
          ▄▓▓▓▀        ▄▓▓▀   ▐▓▓▌     ▓▓▌   ▐▓▓ ▐▓▓▓▀▀▀▓▓▌ ▓▓▓ ▀▓▓▌▀ ^▓▓▌
╒▓▓▌
        ▄▓▓▓▓▓▄▄▄▄▄▄▄▄▓▓▓      ▓▀      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌   ▐▓▓▄
▓▓▌
        ▀▓▓▓▓▀▀▀▀▀▀▀▀▀▀▓▓▄     ▓▓      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌
▐▓▓▐▓▓
          ^█▓▓▓        ▀▓▓▄   ▐▓▓▌     ▓▓▓▓▄▓▓▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▓▄
▓▓▓▓`
            '▀▓▓▓▄      ^▓▓▓  ▓▓▓       └▀▀▀▀ ▀▀ ^▀▀    `▀▀ `▀▀   '▀▀
▐▓▓▌
               ▀▀▀▀▓▄▄▄   ▓▓▓▓▓▓,                                      ▓▓▓▓▀
                   `▀█▓▓▓▓▓▓▓▓▓▌
                        ¬`▀▀▀█▓


INFO:mlagents.trainers:{'--curriculum': 'None',
 '--docker-target-name': 'None',
 '--env': 'C:\\Users\\msi\\Downloads\\ml-agents\\ml-agents\\3DBall_Exp1',
 '--help': False,
 '--keep-checkpoints': '5',
 '--lesson': '0',
 '--load': False,
 '--no-graphics': False,
 '--num-runs': '1',
 '--run-id': 'ppo',
 '--save-freq': '50000',
 '--seed': '-1',
 '--slow': False,
 '--train': True,
 '--worker-id': '0',
 '<trainer-config-path>':
'C:\\Users\\msi\\Downloads\\ml-agents\\config\\trainer_config.yaml'}
INFO:mlagents.envs:
'Ball3DAcademy' started successfully!
Unity Academy name: Ball3DAcademy
        Number of Brains: 1
        Number of Training Brains : 0
        Reset Parameters :

Unity brain name: 3DBallLearning
        Number of Visual Observations (per agent): 0
        Vector Observation space size (per agent): 8
        Number of stacked Vector Observation: 1
        Vector Action space type: continuous
        Vector Action space size (per agent): [2]
        Vector Action descriptions: ,
WARNING:mlagents.envs: No Learning Brains set to train found in the Unity
Environment. You will not be able to pass actions to your agent(s).

(ml-agents) C:\Users\msi>

**Comment by xiaomaogy** [comment] 2019-01-18 05:47
I guess you didn't check the learning brain as external, or something else.

**Comment by whiteGhost333** [comment] 2019-01-18 16:11
ah, yes  you must be referring the control check box.  will give it a go.
thanks for the help.

**Comment by sunrisebacon** [comment] 2019-01-28 11:14
I ran into this as well on Windows 10 64bit using ml-agents 0.6. 
I would suggest adding the "pip install pypiwin32" command to Installation-Windows.md.

**Comment by whiteGhost333** [comment] 2019-01-28 23:59
I'd second the motion.

**Comment by mphil355** [comment] 2019-01-30 04:03
Also ran into the same error and the **pip install pypiwin32** command fixed it for me. Feels good to finally have it running after uninstalling/reinstalling multiple times combing over the windows install guide profusely.

Thanks!

**Comment by xiaomaogy** [comment] 2019-01-30 04:44
I will add the pypiwin32 dependency to the installation this or next week.

**Comment by Cbunz** [comment] 2019-02-16 06:51
So I was getting: 

ModuleNotFoundError: No module named 'win32api'

So I used the command pip install pypiwin32, which installed properly. When I try after installing, I get this error:

Import Error: DLL load failed: The specified module could not be found.

**Comment by gregaton** [comment] 2019-02-16 11:00
Did you follow [the Windows installation guide](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation-Windows.md) and added the environment variables? (the folders are enough)
It's important to use the right python and tensorflow version.

**Comment by LSDemian** [comment] 2019-02-17 18:04
@Cbunz I had the same issue
Here's what helped for me https://github.com/michaelgundlach/pyspeech/issues/23#issuecomment-280915608

**Comment by xiaomaogy** [comment] 2019-04-03 22:29
Since this bug is fixed, I will close the issue. Feel free to open if you want to discuss more.

**Closed by xiaomaogy** 2019-04-03 22:29 UTC
Labels: bug, help-wanted

**Comment by pepeto** [comment] 2019-07-22 04:12
I had the same issue and it was fixed after running pip install pypiwin32

**Comment by Mohsinrazaa** [comment] 2021-01-16 18:02
This is resolve my case as found on Where to find the win32api module for Python?

**pip install pypiwin32**
