### ISSUE TITLE
Open multiple environments with python multi processing

### ISSUE THREAD

**Issue by imankgoyal** [Unity-Technologies/ml-agents#1382] opened 2018-10-28 13:51 UTC
Hi, 
I want to use python multi-processing to open up multiple unity environments. More specifically, I was thinking of modifying ml-agents/ml-agents/mlagents/envs/environment.py function to open up multiple processes with different instantiations of unity, and communicate accordingly. Do you think it is a good way to go? Is there any obvious limitation/bottleneck to this approach? I would very much appreciate any suggestions and advice.

**Comment by xiaomaogy** [comment] 2018-11-02 19:09
Hi @imankgoyal, the bottleneck here is how many instance of Unity you can launch in one machine. We are also exploring this approach ourselves.

**Comment by eshvk** [comment] 2018-12-17 23:15
Hi @imankgoyal, Thanks for reaching out to us. Hopefully you were able to resolve your issue.  We are closing this due to inactivity, but if you need additional assistance, feel free to reopen the issue.

**Comment by harperj** [comment] 2019-02-01 05:43
This is a duplicate of #828 and something we're working on for the near future. I'm going to close this issue, but please feel free to continue any related discussion there.

**Closed by harperj** 2019-02-01 05:43 UTC
Labels: request/roadmap
