### ISSUE TITLE
potential memory leak from TFTensor

### ISSUE THREAD

**Issue by tcmxx** [Unity-Technologies/ml-agents#926] opened 2018-06-27 14:30 UTC
I see in CoreBrainInternal, all TFTensors are not disposed by calling Dispose() (including datas feeding to network that are implicitly converted to TFTensor). 

I think this might cause memory leak problem, at least according to Tensorflowsharp it is necessary to Dispose it, and previously this has encountered to me.

Also, Texture2D that are not destroyed might also cause memory leak (not very sure.).

**Comment by awjuliani** [comment] 2018-06-28 19:19
Hi @tcmxx,

Thanks for pointing this out. We currently have a PR addressing memory issues caused by the `ObservationToTexture` function: https://github.com/Unity-Technologies/ml-agents/pull/935

**Comment by tcmxx** [comment] 2018-06-29 08:20
Hello @awjuliani . 
The Texture is just one issue. Other issue is with the TFTensor when using the internal brain.

Seems like TFTensor needs to be disposed after feeding as input and obtained from output. https://github.com/migueldeicaza/TensorFlowSharp/issues/137

**Comment by tcmxx** [comment] 2018-07-26 12:16
can you try to dispose the result as well?

**Comment by xiaomaogy** [comment] 2018-09-06 21:44
@vincentpierre Does this seems to be the memory leak issue you had before?

**Comment by awjuliani** [comment] 2019-04-03 22:20
Hi all. We have switched to Barracuda for inference. Closing this issue for now. Please feel free to re-open if you deem it necessary.

**Closed by awjuliani** 2019-04-03 22:20 UTC
Labels: bug
