### ISSUE TITLE
Video Recorder plugin does not work with --num-envs > 1

### ISSUE THREAD

**Issue by caioc2** [Unity-Technologies/ml-agents#3312] opened 2020-01-29 18:24 UTC
**Describe the bug**
Video Recorder plugin does not work with --num-envs > 1.
With more than one executable running, all instances tries to write to the same video file. The duration control  also wont work as intended because now the Academy steps are globally counted.

**To Reproduce**
Add the video recorder to any test scene. Build it and launch the training with --num-envs greater than 1 The generated videos cant be played correctly.

**Console logs / stack traces**
No logs stack-trace.

**Environment (please complete the following information):**
- OS + version: Windows 10
- _ML-Agents version_: 0.13.0+
- _Environment_: Any example from ML-Agents

**Possible fix**

Make each instance open it own file (i.e by process id) or  make it run just for the first instance and also count it steps locally (for the video duration only).

**Comment by anupambhatnagar** [comment] 2020-01-31 21:54
@caioc2 This is not a bug, it is the intended behavior.

**Comment by caioc2** [comment] 2020-02-01 01:16
@anupambhatnagar

Sorry if I'm being pedantic, are you sure that you understood what's happening?

If [this video](https://www.youtube.com/watch?v=UoEQICke7N4&feature=youtu.be) is "intended behavior" instead of [this](https://www.youtube.com/watch?v=XE9hwIsIqk4&feature=youtu.be), without a single line of text in the documentation, no error and no warning whatsoever, then please close this ticket.

Thanks

**Comment by anupambhatnagar** [comment] 2020-02-01 02:33
ah, sorry about that. I intended to write that comment on the other issue you submitted. https://github.com/Unity-Technologies/ml-agents/issues/3326 
We will look into this issue and make the necessary fix.

**Comment by chriselion** [comment] 2020-10-16 18:45
For reference, this was logged in our internal tracker as MLA-750. I'm closing this issue because we're not supporting the video recorder any further and wont' fix the bug.

**Closed by chriselion** 2020-10-16 18:45 UTC
Labels: bug
