### ISSUE TITLE
AcademyReset called twice

### ISSUE THREAD

**Issue by ann234** [Unity-Technologies/ml-agents#1117] opened 2018-08-23 06:32 UTC
When Academy is done, I found that AcademyReset function is called twice every done condition.

Current episode count: 2          <--- print(GetCurrentEpicode())
UnityEngine.MonoBehaviour:print(Object)
RobotAcademy:AcademyReset() (at Assets/Scripts/ReinforcementLearning/RobotAcademy.cs:24)
MLAgents.Academy:EnvironmentReset() (at Assets/ML-Agents/Scripts/Academy.cs:597)
MLAgents.Academy:EnvironmentStep() (at Assets/ML-Agents/Scripts/Academy.cs:572)
MLAgents.Academy:FixedUpdate() (at Assets/ML-Agents/Scripts/Academy.cs:605)

Current episode count: 3
UnityEngine.MonoBehaviour:print(Object)
RobotAcademy:AcademyReset() (at Assets/Scripts/ReinforcementLearning/RobotAcademy.cs:24)
MLAgents.Academy:EnvironmentReset() (at Assets/ML-Agents/Scripts/Academy.cs:597)
MLAgents.Academy:ForcedFullReset() (at Assets/ML-Agents/Scripts/Academy.cs:506)
MLAgents.Academy:EnvironmentStep() (at Assets/ML-Agents/Scripts/Academy.cs:542)
MLAgents.Academy:FixedUpdate() (at Assets/ML-Agents/Scripts/Academy.cs:605)

One from normal EnvironmentReset() and the other is in ForcedFullReset().
I also found episode count is count up twice in every Done condition.
Is it possible to call AcademyReset function just once in Done condition?

**Comment by donlee90** [comment] 2018-11-30 04:59
I am having the same issue, when I am training with default `mlagents-learn` script. This does not happen when I set the Brain Type to "Player". I think the ForcedFullReset() is invoked by the `mlagents-learn` script.

**Comment by WHiT3R4bBiT** [comment] 2019-02-07 21:44
This is still happening for me on v0.6a.

At the start it's only called once via ForcedFullReset() under `else if (!firstAcademyReset)`. 

Then every time my Academy hits Max Steps I get two AcademyReset() calls, one via the if(done) in EnvironmentStep() and then one fixed update later one via ForcedFullReset() under `if (brainBatcher.GetCommand() == CommunicatorObjects.CommandProto.Reset)`

This may be related to #1687 which is also my project. We're using On Demand decisions in case that helps.

**Comment by vincentpierre** [comment] 2019-02-07 22:31
When we do training with mlagents-learn, we call reset manually when the Academy is done. I think this is what is causing the problem. The Academy resets once because its done flag has been set to true and then the python process calls a reset manually. This way of reseting the environment is sub optimal indeed, is it causing problem in your environment? My guess is that it should only messes up the counting of the episodes. Am I wrong ? Is it causing other issues ?

**Comment by WHiT3R4bBiT** [comment] 2019-02-07 23:31
I haven't seen any other issues caused by this.

**Comment by donlee90** [comment] 2019-02-09 01:29
In my case, I have two screens (VideoPlayer) showing different videos, and I want to swap the videos between the two screens at the end of each episode (when AcademyReset() is called). But since AcademyReset() is called twice, the videos are swapped twice, and as a result the same videos are played in the same screens.

**Comment by awjuliani** [comment] 2019-09-16 17:44
Hi all. For the next release of ML-Agents we are cleaning up some of the logic in Academy, and this issue should be resolved. As such, I am closing this issue.

**Closed by awjuliani** 2019-09-16 17:44 UTC
Labels: bug
