### ISSUE TITLE
Empty project on Unity 2020.1.9f1, ml-agents version 2.0.1 has unfixable compile errors

### ISSUE THREAD

**Issue by Hokage3211** [Unity-Technologies/ml-agents#5632] opened 2021-12-06 16:33 UTC
**Describe the bug**
When using my project, I installed ML-agents and got these errors about build targets not existing

**To Reproduce**
1. Open empty project in 2020.1.9f1
2. Install ML-Agents via adding it in the package menu and typing com.unity.ml-agents
3. Observe compile errors

**Console logs / stack traces**
```
Library\PackageCache\com.unity.burst@1.6.0\Editor\BurstAotCompiler.cs(243,47): error CS0117: 'BuildTarget' does not contain a definition for 'GameCoreXboxOne'

Library\PackageCache\com.unity.burst@1.6.0\Editor\BurstAotCompiler.cs(243,93): error CS0117: 'BuildTarget' does not contain a definition for 'GameCoreXboxSeries'

Library\PackageCache\com.unity.burst@1.6.0\Editor\BurstAotCompiler.cs(1109,34): error CS0117: 'BuildTarget' does not contain a definition for 'GameCoreXboxOne'

Library\PackageCache\com.unity.burst@1.6.0\Editor\BurstAotCompiler.cs(1112,34): error CS0117: 'BuildTarget' does not contain a definition for 'GameCoreXboxSeries'

Library\PackageCache\com.unity.burst@1.6.0\Editor\BurstAotCompiler.cs(1138,34): error CS0117: 'BuildTarget' does not contain a definition for 'PS5'
```

**Screenshots**
![image](https://user-images.githubusercontent.com/54164358/144884042-0258cc23-1ebb-4466-9891-67a093380793.png).

**Environment (please complete the following information):**
- Unity Version: 2020.1.9f1
- OS + version: Windows 10
- _ML-Agents version_: 2.0.1
- _Torch version_: Not applicable
- _Environment_: Unity environment

**Comment by jrupert-unity** [comment] 2021-12-07 05:16
I checked 2020.3.20f1 and it didn't have this problem, which I was able to reproduce on Unity 2020.1.9f1.  I'll follow up on that but in the meantime is moving up to a Unity 2020.3 LTS version an option?

**Comment by Hokage3211** [comment] 2021-12-07 06:23
> is moving up to a Unity 2020.3 LTS version an option?
Yes for my instance it's an option, luckily, but not sure if everyone can do the same

**Comment by jrupert-unity** [comment] 2021-12-10 18:16
This is being tracked in Jira as MLA-2319.  Closing as there is a workaround in this case and the issue isn't on an LTS version.  Please open a new issue if anything similar is causing a problem that the proposed workaround does not fix.

**Closed by jrupert-unity** 2021-12-10 18:16 UTC
Labels: bug

**Comment by jihene-enit** [comment] 2021-12-18 20:38
Hi , I need help i've find the same errors and i can't fix it, did you find a solution please ?

**Comment by jrupert-unity** [comment] 2021-12-19 00:26
The easy solution is to upgrade to Unity 2020.3 LTS if this is possible for your situation.
