### ISSUE TITLE
Bug with reading/writing SAC experience buffer

### ISSUE THREAD

**Issue by niskander** [Unity-Technologies/ml-agents#3164] opened 2020-01-06 15:58 UTC
Hi, this error with reading the SAC experience buffer seems to occur randomly, but I've seen it many times:

```
INFO:mlagents.trainers:Saving Experience Replay Buffer to \last_replay_buffer.hdf5
Traceback (most recent call last):
  File "\.conda\envs\ml-agents\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "\.conda\envs\ml-agents\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "\.conda\envs\ml-agents\Scripts\mlagents-learn.exe\__main__.py", line 9, in <module>
  File "\.conda\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py", line 422, in main
    run_training(0, run_seed, options, Queue())
  File "\.conda\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py", line 266, in run_training
    tc.start_learning(env)
  File "\.conda\envs\ml-agents\lib\site-packages\mlagents\trainers\trainer_controller.py", line 215, in start_learning
    self._save_model()
  File "\.conda\envs\ml-agents\lib\site-packages\mlagents\trainers\trainer_controller.py", line 97, in _save_model
    self.trainers[brain_name].save_model()
  File "\.conda\envs\ml-agents\lib\site-packages\mlagents\trainers\sac\trainer.py", line 112, in save_model
    self.save_replay_buffer()
  File "\.conda\envs\ml-agents\lib\site-packages\mlagents\trainers\sac\trainer.py", line 121, in save_replay_buffer
    self.training_buffer.update_buffer.save_to_file(file_object)
  File "\.conda\envs\ml-agents\lib\site-packages\mlagents\trainers\buffer.py", line 230, in save_to_file
    key, data=data, dtype="f", compression="gzip"
  File "\.conda\envs\ml-agents\lib\site-packages\h5py\_hl\group.py", line 139, in create_dataset
    self[name] = dset
  File "\.conda\envs\ml-agents\lib\site-packages\h5py\_hl\group.py", line 373, in __setitem__
    h5o.link(obj.id, self.id, name, lcpl=lcpl, lapl=self._lapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5o.pyx", line 202, in h5py.h5o.link
  File "h5py\defs.pyx", line 1542, in h5py.defs.H5Olink
  File "h5py\h5fd.pyx", line 158, in h5py.h5fd.H5FD_fileobj_read
io.UnsupportedOperation: read
INFO:mlagents.envs:UnityEnvironment worker 9: environment stopping.
```

Earlier on, this warning appears:
```
\.conda\envs\ml-agents\lib\site-packages\mlagents\trainers\buffer.py:227: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(file_object) as write_file:
INFO:mlagents.envs:Saved Model
```
Could it be related? Or could it have to do with the experience buffer being too big? 
It's pretty inconvenient cause it causes the model to not save afterwards, and it cannot be reloaded.

**Comment by chriselion** [comment] 2020-01-06 17:42
Hi @niskander - what version of h5py are you using? Looks like we've only tested up to 2.9.0, but 2.10.0 came out in December.

**Comment by surfnerd** [comment] 2020-01-06 18:11
Hi @niskander,
Thank you for your feedback.  I've logged this in our internal tracker as MLA-491.  @chriselion as kindly already created #3165 to check against different versions in CI.  We will provide any updates here as they come.

**Comment by chriselion** [comment] 2020-01-06 18:27
I can reproduce the deprecation warning using h5py==2.10.0 in our unit tests with
```
pytest ml-agents/mlagents/trainers/tests/test_sac.py::test_sac_save_load_buffer
```
but I don't get the `io.UnsupportedOperation` that you're seeing. This might be due to a difference in platforms (I'm on Mac, looks like you're on Windows).

The fix is in https://github.com/Unity-Technologies/ml-agents/pull/3165 and I'll make sure that goes into the next release; in the meantime, can you try applying the changes locally and see if they help? (You can ignore the `test_constraints_*_version.txt` changes, those just affect our CI).

**Comment by niskander** [comment] 2020-01-06 19:16
@chriselion yes I'm on windows. I'll try that, thanks!

**Comment by chriselion** [comment] 2020-01-07 18:05
@niskander Any luck with applying those changes? Just want to make sure it helps before I close the bug in our tracker...

**Comment by niskander** [comment] 2020-01-07 19:43
@chriselion sorry, didn't get a chance to try yet but will post here once I do

**Comment by niskander** [comment] 2020-01-09 20:38
@chriselion I actually haven't had this issue since I reduced the size of the experience buffer (I had went a little ham with it earlier; it was 90 million, reduced to 2 million).

**Comment by chriselion** [comment] 2020-01-24 01:58
OK, closing this, please reopen if you hit any other errors around this.

**Comment by dlindmark** [comment] 2020-03-09 07:53
I recently got this error aswell. With `buffer_size = 750000`, but using one visual observation. Grayscale with size 128x64. So the buffer size is well below 2 million but with visual observation the amount of data might be in the same range?

It was able to save the buffer 3 times before crashing. The saved file size is about 27 mb. I have started the run again to investigate if it is reproducible.

**Comment by dlindmark** [comment] 2020-03-09 13:52
Yes, it seems to crash again. After approx.  the same amount of time. Are there any tests with visual observations and `save_replay_buffer = true`? 
```
INFO:mlagents.trainers:Saving Experience Replay Buffer to ./models/sac1/MuckingBehavior\last_replay_buffer.hdf5
INFO:mlagents_envs:Environment shut down with return code 0 (CTRL_C_EVENT).
INFO:mlagents_envs:Environment shut down with return code 0 (CTRL_C_EVENT).
INFO:mlagents_envs:Environment shut down with return code 0 (CTRL_C_EVENT).
Traceback (most recent call last):
  File "C:\Python\Python36\Lib\multiprocessing\queues.py", line 236, in _feed
    send_bytes(obj)
  File "C:\Python\Python36\Lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "C:\Python\Python36\Lib\multiprocessing\connection.py", line 290, in _send_bytes
    nwritten, err = ov.GetOverlappedResult(True)
BrokenPipeError: [WinError 109] The pipe has been ended
INFO:mlagents_envs:Environment shut down with return code 0 (CTRL_C_EVENT).
Traceback (most recent call last):
  File "e:\xxxx\mlagents\trainers\buffer.py", line 231, in save_to_file
    write_file.create_dataset(key, data=data, dtype="f", compression="gzip")
  File "e:\xxxx\lib\site-packages\h5py\_hl\group.py", line 137, in create_dataset
    dset = dataset.Dataset(dsid)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "e:\daniel\epiroc\venv\lib\site-packages\h5py\_hl\dataset.py", line 403, in __init__
    self._dcpl = self.id.get_create_plist()
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5d.pyx", line 324, in h5py.h5d.DatasetID.get_create_plist
  File "h5py\defs.pyx", line 440, in h5py.defs.H5Dget_create_plist
  File "h5py\h5fd.pyx", line 158, in h5py.h5fd.H5FD_fileobj_read
io.UnsupportedOperation: read
```

**Comment by chriselion** [comment] 2020-03-09 16:51
@dlindmark What version of ml-agents and h5py are you using? We'll look into this today.

**Comment by dlindmark** [comment] 2020-03-09 17:11
```
pip show h5py
Name: h5py
Version: 2.10.0
```
```
pip show mlagents
Name: mlagents
Version: 0.14.1
```

**Comment by ervteng** [comment] 2020-03-09 18:21
Hi @dlindmark, we're trying to reproduce your issue on our end. So far we've been able to load replay buffers >400MB with no issue. Had a couple of questions:

- Which platform are you on (Mac/Windows/Linux)?
- Which ver of Python are you using?
- On the last successful load, the console should have printed a line similar to this: `Experience replay buffer has X experiences.` How many experiences was it able to load successfully?

Thanks!

**Comment by dlindmark** [comment] 2020-03-10 07:29
I am on Windows. With python 3.6.7.

The error occurs while training. When it saves. I guess it tries to read the buffer after saving as a sanity check or something?

If I try to restart the failed training using `--load` it crashes while loading the replay buffer. It looks like it does not find the file `./models/sac1/MuckingBehavior\last_replay_buffer.hdf5`. Even though it exists.

```
INFO:mlagents.trainers:Loading Model for brain MuckingBehavior?team=0
INFO:mlagents.trainers:Loading Experience Replay Buffer from ./models/sac1/MuckingBehavior\last_replay_buffer.hdf5
INFO:mlagents_envs:Environment shut down with return code 0 (CTRL_C_EVENT).
Traceback (most recent call last):
  File "E:\xxx\xxx\venv\Scripts\mlagents-learn-script.py", line 11, in <module>
    load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')()
  File "e:\xxx\xxx\ml-agents-fork\ml-agents\mlagents\trainers\learn.py", line 479, in main
    run_cli(parse_command_line())
  File "e:\xxx\xxx\ml-agents-fork\ml-agents\mlagents\trainers\learn.py", line 475, in run_cli
    run_training(run_seed, options)
  File "e:\xxx\xxx\ml-agents-fork\ml-agents\mlagents\trainers\learn.py", line 320, in run_training
    tc.start_learning(env_manager)
  File "e:\xxx\xxx\ml-agents-fork\ml-agents\mlagents\trainers\trainer_controller.py", line 213, in start_learning
    self._create_trainers_and_managers(env_manager, new_behavior_ids)
  File "e:\xxx\xxx\ml-agents-fork\ml-agents\mlagents\trainers\trainer_controller.py", line 200, in _create_trainers_and_managers
    self._create_trainer_and_manager(env_manager, behavior_id)
  File "e:\xxx\xxx\ml-agents-fork\ml-agents\mlagents\trainers\trainer_controller.py", line 180, in _create_trainer_and_manager
    policy = trainer.create_policy(env_manager.external_brains[name_behavior_id])
  File "e:\xxx\xxx\ml-agents-fork\ml-agents\mlagents\trainers\sac\trainer.py", line 229, in create_policy
    self.load_replay_buffer()
  File "e:\xxx\xxx\ml-agents-fork\ml-agents\mlagents\trainers\sac\trainer.py", line 129, in load_replay_buffer
    self.update_buffer.load_from_file(file_object)
  File "e:\xxx\xxx\ml-agents-fork\ml-agents\mlagents\trainers\buffer.py", line 237, in load_from_file
    with h5py.File(file_object, "r") as read_file:
  File "e:\xxx\xxx\venv\lib\site-packages\h5py\_hl\files.py", line 408, in __init__
    swmr=swmr)
  File "e:\xxx\xxx\venv\lib\site-packages\h5py\_hl\files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (file signature not found)

(venv) E:\xxx\xxx>dir models\sac1\MuckingBehavior\
 Volume in drive E is Seagate3TB
 Volume Serial Number is 4869-2B9D

 Directory of E:\xxx\xxx\models\sac1\MuckingBehavior

2020-03-09  11:46    <DIR>          .
2020-03-09  11:46    <DIR>          ..
2020-03-09  11:46               233 checkpoint
2020-03-09  11:47        28 115 676 last_replay_buffer.hdf5
2020-03-09  10:54        47 272 540 model-146749.cptk.data-00000-of-00001
2020-03-09  10:54             6 963 model-146749.cptk.index
2020-03-09  10:54           777 645 model-146749.cptk.meta                                                               
```

**Comment by ervteng** [comment] 2020-03-11 22:00
Hi @dlindmark, I noticed this line in your output: `INFO:mlagents_envs:Environment shut down with return code 0 (CTRL_C_EVENT).`
How many environments are you using? Also, when quitting ML-Agents, after pressing CTRL+C, the program _will_ hang on "Saving Experience Replay Buffer" for a bit before quitting. Hitting CTRL+C again would cause similar errors to what you have there. Thanks!

**Comment by chriselion** [comment] 2020-03-11 22:03
@dlindmark We're stumped. @ervteng tried to reproduce this on Windows yesterday and wasn't able to get it to happen. I looked a bit through the h5py code and it don't see where that error would be coming from (we're writing, so I don't understand where the complaints about read access are coming from)

Could you either open an issue in h5py, or provide the details here that they ask for in their [issue template](https://github.com/h5py/h5py/issues/new), and I'll open it?

**Comment by niskander** [comment] 2020-03-11 22:16
@chriselion @dlindmark If it helps with repro when I was getting this error it was usually with a `--load`, not on the first run. Also, my buffers were in the order of GBs so much bigger than 27 MB. Ever since reducing the buffer size to 0.99GB it hasn't occurred for me.

**Comment by dlindmark** [comment] 2020-03-12 08:42
@chriselion I have reverted to training without saving replay buffer. It is not vital for me, but would be convinient sometimes. 

@ervteng I have been using 4 environments. I have not intentionally stopped the training with CTRL+C. I will try reproducing with one environment and experiment with the observations etc. To see if I can narrow it down in some way.

Aand look at h5py issue template today.

**Comment by ervteng** [comment] 2020-03-12 16:58
@dlindmark thanks for checking; so it happens when training hits `max_step`? About how many steps did it go for before quitting?

**Comment by dlindmark** [comment] 2020-03-13 10:06
@ervteng Ok, did not have much time yesterday. But started a training with same environment but with only one. Crashed at the same point. The max steps are ` max_steps:      5.0e6   ` And I am quite certain I have not unintentionally Ctrl-c the training three times at the row at the same spot.

But for some reason the environment stops. Noticed that the memory usage for the python process seemed to be much higher than usual. Will try to investigate during the weekend.

**Comment by ervteng** [comment] 2020-03-13 17:39
Got it, so it's crashing in the middle of the run w/o intervention. Thanks, that'll help us find the issue.

**Comment by dlindmark** [comment] 2020-03-18 10:45
Have not really had time to look into this. But I have completed trainings while saving `replay_buffer` now. It have not been a problem since decreasing the resolution from 64x64 to the minimum 20x20. So seems likely that the process just crashed because my desktop ran out of memory. Or somehow related anyway.

**Comment by ervteng** [comment] 2020-03-18 16:59
Hi @dlindmark, I did see similar problems when my machine was close to running out of RAM, so that might be it. I think what was happening was memory was running out, the Unity environment quits, and then the Python code tries to save the replay buffer - causing the error. If 20x20 is too small, I'd recommend reducing the replay buffer size to around 50-100k - that should help as well and usually isn't too detrimental to training.

**Comment by surfnerd** [comment] 2021-01-28 19:43
Hi @dlindmark,
I'm going to close this issue since it seems like it was resolved.  Thank you!  Please reopen this if you have further issues.

**Closed by surfnerd** 2021-01-28 19:43 UTC
Labels: bug
