### ISSUE TITLE
ONNX exported by Pytorch 1.11.0 does not have required constant "version_number"

### ISSUE THREAD

**Issue by anayebi** [Unity-Technologies/ml-agents#5956] opened 2023-08-02 13:18 UTC
**Describe the bug**
When using an ONNX model in Unity as the `Behavior Parameters->Model` of an ML Agent that I exported from Pytorch 1.11.0 via `torch.onnx.export`, I get the error that the file does not have the required constant "version_number".

What is the best way to modify my ONNX file to add this attribute? 

I trained the model in Pytorch and not ML Agents to be able to customize things more.

I also tried the following 3 strategies to manually update the ONNX file, none of which worked and gave the same error:

Strategy 1:
```
import onnx

# Load the ONNX model
model = onnx.load("model.onnx")

# Check that the IR is well formed
onnx.checker.check_model(model)

# Print a human readable representation of the graph
print(onnx.helper.printable_graph(model.graph))

# Set the version number
model.producer_version = "1.6.0"  # Set the version number here

# Save the model
onnx.save(model, "updated_model.onnx")
```

Strategy 2:
```
import onnx
from onnx import helper

# Load the model
model = onnx.load("model.onnx")

# Create a tensor for the version number
version_number_tensor = helper.make_tensor(
    'VersionNumber',                    # tensor name (string)
    onnx.TensorProto.FLOAT,             # tensor data type
    dims=(1,),                          # tensor shape as tuple
    vals=[2.0],                         # tensor values
)

# Add the version number tensor to the graph
model.graph.initializer.append(version_number_tensor)

# Save the model
onnx.save(model, "updated_model.onnx")
```

Strategy 3:
```
import onnx

# Load the model
model = onnx.load("model.onnx")

# Write into the ProducerName field
model.producer_name = "torch-jit-export 2"

# Save the model
onnx.save(model, "updated_model.onnx")
```

**To Reproduce**
1. Add the ONNX file to `Behavior Parameters->Model`.
2. Click on Run.

**Console logs / stack traces**
This is this line 52 in `Runtime/Inference/BarracudaModelExtensions.cs` that is causing the error:
```
        public static int GetVersion(this Model model)
        {
            return (int)model.GetTensorByName(TensorNames.VersionNumber)[0];
        }
```
It does not appear to have `VersionNumber`, according to the full stacktrace below:
```
NullReferenceException: Object reference not set to an instance of an object
Unity.MLAgents.Inference.BarracudaModelExtensions.GetVersion (Unity.Barracuda.Model model) (at ./Library/PackageCache/com.unity.ml-agents@2.0.1/Runtime/Inference/BarracudaModelExtensions.cs:52)
Unity.MLAgents.Inference.BarracudaModelParamLoader.CheckModelVersion (Unity.Barracuda.Model model) (at ./Library/PackageCache/com.unity.ml-agents@2.0.1/Runtime/Inference/BarracudaModelParamLoader.cs:73)
Unity.MLAgents.Inference.ModelRunner..ctor (Unity.Barracuda.NNModel model, Unity.MLAgents.Actuators.ActionSpec actionSpec, Unity.MLAgents.Policies.InferenceDevice inferenceDevice, System.Int32 seed) (at ./Library/PackageCache/com.unity.ml-agents@2.0.1/Runtime/Inference/ModelRunner.cs:74)
Unity.MLAgents.Academy.GetOrCreateModelRunner (Unity.Barracuda.NNModel model, Unity.MLAgents.Actuators.ActionSpec actionSpec, Unity.MLAgents.Policies.InferenceDevice inferenceDevice) (at ./Library/PackageCache/com.unity.ml-agents@2.0.1/Runtime/Academy.cs:620)
Unity.MLAgents.Policies.BarracudaPolicy..ctor (Unity.MLAgents.Actuators.ActionSpec actionSpec, System.Collections.Generic.IList`1[T] actuators, Unity.Barracuda.NNModel model, Unity.MLAgents.Policies.InferenceDevice inferenceDevice, System.String behaviorName) (at ./Library/PackageCache/com.unity.ml-agents@2.0.1/Runtime/Policies/BarracudaPolicy.cs:84)
Unity.MLAgents.Policies.BehaviorParameters.GeneratePolicy (Unity.MLAgents.Actuators.ActionSpec actionSpec, Unity.MLAgents.Actuators.ActuatorManager actuatorManager) (at ./Library/PackageCache/com.unity.ml-agents@2.0.1/Runtime/Policies/BehaviorParameters.cs:240)
Unity.MLAgents.Agent.LazyInitialize () (at ./Library/PackageCache/com.unity.ml-agents@2.0.1/Runtime/Agent.cs:462)
Unity.MLAgents.Agent.OnEnable () (at ./Library/PackageCache/com.unity.ml-agents@2.0.1/Runtime/Agent.cs:365)
```

**Screenshots**
This is the warning in the GUI that appears when I add the ONNX file to the `Model` attribute of the `Behavior Parameters` of the agent:
<img width="198" alt="Screenshot 2023-08-02 at 9 16 03 AM" src="https://github.com/Unity-Technologies/ml-agents/assets/12835914/41e6f958-09e7-4811-87f9-9a25ca0602b7">

**Environment (please complete the following information):**
- Unity Version: Unity 2022.3.5f1
- OS + version: Mac OS X Ventura 13.2.1
- _ML-Agents version_: ML-Agents v2.0.1
- _Torch version_: 1.11.0
- _Environment_: Custom

**Comment by miguelalonsojr** [comment] 2023-10-08 21:52
If you train a policy outside of the ML-Agents training pipeline, you'll have to export it properly. At the end of this colab, https://github.com/Unity-Technologies/ml-agents/blob/develop/colab/Colab_UnityEnvironment_2_Train.ipynb, you can find details of how to export a custom model for use in Unity with ML-Agents. If you need further assistance, please post in the forums. https://forum.unity.com/forums/ml-agents.453/ Closing as this is not a bug.

**Closed by miguelalonsojr** 2023-10-08 21:52 UTC
Labels: bug
