### ISSUE TITLE
docopt not found training not working

### ISSUE THREAD

**Issue by BenM77** [Unity-Technologies/ml-agents#750] opened 2018-05-14 04:47 UTC
help needed: learn.py is unable to run. Similar problem to https://github.com/Unity-Technologies/ml-agents/issues/675 but when i enter 
`python learn.py (<envname>) --run-id=<run-id> --train`
i still get the problem.
the issue is also related to https://github.com/Unity-Technologies/ml-agents/issues/647 as I have gotten the same error message
<img width="960" alt="2018-05-13" src="https://user-images.githubusercontent.com/34111213/39978491-c7633474-56f5-11e8-810d-34b273a8bf24.png">

**Comment by wimachtendink** [comment] 2018-05-14 06:44
You might want to share less information about yourself in public.

I was having the same problem, Using Anaconda Navigator I added and updated Docopt from the list it offers which fixed it for me.

**Comment by BenM77** [comment] 2018-05-14 07:16
@wimachtendink How did you do this?

**Comment by wimachtendink** [comment] 2018-05-14 16:06
Yeah, when I installed from pip in my ml-agents environment I was getting that error. 

I tried it again from Anaconda Navigator, not Anaconda Prompt, and it worked.

I guess you could just verify by going into the Anaconda Navigator>Environments>ml-agents>installed and scroll down to Docopt.

![anacondanavigator](https://user-images.githubusercontent.com/19740189/40008543-68bc59e6-5754-11e8-8f8d-355c50a16351.png)

you also don't need the full path of your file as long as it's in the python folder/directory I just use [in the right folder]/python> python learn.py test --run-id=test0 --train


but also, your executable extension is .apk?

https://github.com/Unity-Technologies/ml-agents/blob/master/python/unitytrainers/trainer_controller.py#L38

        env_path = (env_path.strip()
                    .replace('.app', '')
                    .replace('.exe', '')
                    .replace('.x86_64', '')
                    .replace('.x86', ''))  # Strip out executable extensions if passed

perhaps .apk is breaking something and Docopt is just their best guess? Maybe train it on a windows/mac/linux build then import it to apk?

**Comment by vincentpierre** [comment] 2018-05-14 18:08
This is a duplicate of #749 Please Continue this conversation here.

**Closed by vincentpierre** 2018-05-14 18:08 UTC
