### ISSUE TITLE
Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by PrintAlot** [Unity-Technologies/ml-agents#1964] opened 2019-04-20 10:57 UTC
Hello,

I follow the step to install the ml-agents environment and everything else to have the project run. I am on Windows 10 and I used python 3.6 (the one recommended in the getting started section). And I am on Unity 2018.3.12f1

When I try to launch the learning for the 3D Balls example, the python program shows these errors.

Here is a screenshot of the errors 
![Anaconda Prompt part1](https://user-images.githubusercontent.com/8568121/56456313-ba03b880-636a-11e9-8708-d38b18f38c9a.png)
![Anaconda Prompt part2](https://user-images.githubusercontent.com/8568121/56456317-c25bf380-636a-11e9-932b-57627a8f1eaf.png)

Please tell me what I've done wrong, I've been trying to get ML-Agents to work for two days and I didn't wanna post earlier without trying to solve it myself.

**Comment by vincentpierre** [comment] 2019-04-22 16:57
Hi @PrintAlot 
This seems to be a TensorFlow related error from what I can see [online](https://github.com/tensorflow/tensorflow/issues/11571). Probably due to missing DLLs on your machine. I would recommend uninstalling and reinstalling tensorflow 1.7.1 in a virtual environment.

**Comment by PrintAlot** [comment] 2019-04-23 11:19
no, I tryed uninstalling and reinstalling tensorflow 1.7.1 in a virtual environment. 
and I'm still getting the same errors.

**Comment by vincentpierre** [comment] 2019-04-23 18:13
Hi, I cannot reproduce this error. Are you trying to use tensorflow-gpu ? It seems you have missing cuDNN library.

**Comment by FelipGC** [comment] 2019-05-01 10:52
I am experiencing similar issues, did you find a solution @PrintAlot?

**Comment by PrintAlot** [comment] 2019-05-02 10:38
no tensorflow-GPU but I have tried the tensorflow-GPU install just in case in help but I had no luck (same outcome) I have also how to install on another p.c and am getting the same results so it's most likely something I'm doing or misunderstanding in the install or setup process. it's getting rather frustrating. 

@FelipGC no still no solution :-(

**Comment by PrintAlot** [comment] 2019-05-02 10:51
Do you have a video guide to install and set up for dummies? Because this is making me feel so thick

**Comment by xiaomaogy** [comment] 2019-05-02 17:53
@PrintAlot This seems to be a tensorflow related issue. https://github.com/tensorflow/tensorflow/issues/9469. 

My suggestion would be not use the tensorflow-gpu version and not deal with the cuda stuff, if you don't know how to use it. 

I'm going to close the issue for now since it is not related to our code.

**Closed by xiaomaogy** 2019-05-02 17:53 UTC
Labels: help-wanted

**Comment by PrintAlot** [comment] 2019-05-03 14:39
but I was not using tensorflow-gpu version on either of my p.c's.
Thank you for trying to help anyway.
