### ISSUE TITLE
Learn.py throws an error if you manually close the Unity environment window

### ISSUE THREAD

**Issue by jo3w4rd** [Unity-Technologies/ml-agents#543] opened 2018-03-26 21:45 UTC
@andersonaddo found that he wasn't getting a trained .bytes file if he manually closed the Unity environment app window. He is using Anaconda on Windows, but the same problem happens on Mac w/o Anaconda, too.

I suspect that this breaks the connection between the two apps and instead of handling it gracefully, learn.py throws an exception. Presumably, closing the Unity app manually should have the same effect as hitting CTRL-C at the command prompt.

"...I waited till the "Saved Model" message and closed the Unity window myself. I received no .bytes file."

His command-line log follows (note the Python exception at the end):

(ml-agents) C:\Users\addo_a\Documents\#UNITY PROJECTS\ml-agents-master>python python/learn.py python/MyFIrstMLExercise.exe --run-id=githubexercise --train --save-freq 3000
INFO:unityagents:{'--curriculum': 'None',
 '--docker-target-name': 'Empty',
 '--help': False,
 '--keep-checkpoints': '5',
 '--lesson': '0',
 '--load': False,
 '--run-id': 'githubexercise',
 '--save-freq': '3000',
 '--seed': '-1',
 '--slow': False,
 '--train': True,
 '--worker-id': '0',
 '<env>': 'python/MyFIrstMLExercise.exe'}
INFO:unityagents:
'Ball3DAcademy' started successfully!
Unity Academy name: Ball3DAcademy
        Number of Brains: 1
        Number of External Brains : 1
        Lesson number : 0
        Reset Parameters :

Unity brain name: Ball3DBrain
        Number of Visual Observations (per agent): 0
        Vector Observation space type: continuous
        Vector Observation space size (per agent): 8
        Number of stacked Vector Observation: 3
        Vector Action space type: continuous
        Vector Action space size (per agent): 2
        Vector Action descriptions: ,
2018-03-26 19:53:19.069033: I C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
C:\Users\addo_a\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\tensorflow\python\ops\gradients_impl.py:96: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
INFO:unityagents:Hypermarameters for the PPO Trainer of brain Ball3DBrain:
        batch_size:     1024
        beta:   0.005
        buffer_size:    10240
        epsilon:        0.2
        gamma:  0.99
        hidden_units:   128
        lambd:  0.95
        learning_rate:  0.0003
        max_steps:      5.0e4
        normalize:      True
        num_epoch:      3
        num_layers:     2
        time_horizon:   64
        sequence_length:        64
        summary_freq:   1000
        use_recurrent:  False
        graph_scope:
        summary_path:   ./summaries/githubexercise
        memory_size:    256
INFO:unityagents: Ball3DBrain: Step: 1000. Mean Reward: 0.903. Std of Reward: 0.524.
INFO:unityagents: Ball3DBrain: Step: 2000. Mean Reward: 1.033. Std of Reward: 0.657.
INFO:unityagents:Saved Model
INFO:unityagents: Ball3DBrain: Step: 3000. Mean Reward: 1.535. Std of Reward: 1.644.
INFO:unityagents: Ball3DBrain: Step: 4000. Mean Reward: 4.048. Std of Reward: 4.486.
INFO:unityagents: Ball3DBrain: Step: 5000. Mean Reward: 34.959. Std of Reward: 35.601.
Traceback (most recent call last):
  File "python/learn.py", line 62, in <module>
    tc.start_learning()
  File "C:\Users\addo_a\Documents\#UNITY PROJECTS\ml-agents-master\python\unitytrainers\trainer_controller.py", line 249, in start_learning
    text_action=take_action_text)
  File "C:\Users\addo_a\Documents\#UNITY PROJECTS\ml-agents-master\python\unityagents\environment.py", line 471, in step
    return self._get_state()
  File "C:\Users\addo_a\Documents\#UNITY PROJECTS\ml-agents-master\python\unityagents\environment.py", line 287, in _get_state
    state_dict, end_of_message = self._get_state_dict()
  File "C:\Users\addo_a\Documents\#UNITY PROJECTS\ml-agents-master\python\unityagents\environment.py", line 243, in _get_state_dict
    state = self._recv_bytes().decode('utf-8')
  File "C:\Users\addo_a\Documents\#UNITY PROJECTS\ml-agents-master\python\unityagents\environment.py", line 219, in _recv_bytes
    message_length = struct.unpack("I", bytearray(s[:4]))[0]
struct.error: unpack requires a buffer of 4 bytes

**Comment by xiaomaogy** [comment] 2018-05-17 21:15
@vincentpierre @awjuliani I am also getting this issue when training on Windows, this is something pretty important for our windows users. Do you guys have any idea what might be causing this?

**Comment by xiaomaogy** [comment] 2018-12-17 23:52
I will close this since this is a duplicate of issue #980

**Closed by xiaomaogy** 2018-12-17 23:52 UTC
Labels: request/roadmap

**Comment by xiaomaogy** [comment] 2019-01-08 01:40
This bug has been fixed with https://github.com/Unity-Technologies/ml-agents/pull/1558. The error message 
```
forrtl: error (200): program aborting due to control-C event
Image PC Routine Line Source
libifcoremd.dll 00007FFDAFF994C4 Unknown Unknown Unknown
KERNELBASE.dll 00007FFDEF127EDD Unknown Unknown Unknown
KERNEL32.DLL 00007FFDF2131FE4 Unknown Unknown Unknown
ntdll.dll 00007FFDF226EFC1 Unknown Unknown Unknown
```

still exist, which is related to this stackoverflow https://stackoverflow.com/questions/42653389/ctrl-c-causes-forrtl-error-200-rather-than-python-keyboardinterrupt-exception. Our fix get around this error by adding another ctrl-c event handler which saves the model before this error.
