### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by ironjunk** [Unity-Technologies/ml-agents#5] opened 2017-09-20 05:05 UTC
I am getting an **AttributeError** while running the 3rd cell of the PPO jupyter notebook. Not sure what is causing this. Please help.

![unityml](https://user-images.githubusercontent.com/27753214/30627620-0ca2d230-9def-11e7-99d7-9353926126ed.jpg)

**Comment by ASPePeX** [comment] 2017-09-20 12:13
A easy workaround is removing the lines 10, 88, 89, 99 and 100 from /python/unityagents/environment.py. That's not a nice solution but at least it is working this way.

#7 is a duplicate of this.

**Comment by awjuliani** [comment] 2017-09-21 01:08
This should be addressed now with recent push to master: https://github.com/Unity-Technologies/ml-agents/issues/7#issuecomment-331022162.

**Comment by ASPePeX** [comment] 2017-09-21 10:11
Works well for me, thanks.

**Comment by romerocesar** [comment] 2017-09-21 14:45
Feel free to reopen if you still see the error

**Closed by romerocesar** 2017-09-21 14:45 UTC
Labels: bug
