### ISSUE TITLE
Sample projects Wall, Push and GridWorld don't work on iOS

### ISSUE THREAD

**Issue by 3DAPPG2018** [Unity-Technologies/ml-agents#314] opened 2018-02-04 21:03 UTC
I've been trying to install the sample projects on iOS to see whether they work.  I've discovered that the 3DBall, Crawler and Reacher work fine on iOS.  However, the Wall, Push and GridWorld projects don't work on iOS at all. The game objects appear but they don't move.  The only difference between the samples that work and the ones that don't (that I can see) #is "Action Space Type" is set to continuous in the working samples and "Action Space Type" is set to Discrete in the non-working ones.  I tried to change Discrete to Continuous but it still doesn't work.  

I would appreciate the community's help figuring this out.  I would like to develop a maze and teach the agent to navigate the maze and then build it on the iPhone.  This project is more like the GridWorld project than the other ones so I need to figure this issue out.  

Thank you!

Here's my setup:
Xcode 9.2
Tensorflow 1.4.0
Python 2.7.14
MacBook Pro (2015) running High Sierra 10.13.3
iPhone 8

**Comment by mmattar** [comment] 2018-04-11 21:56
Hi @3DAPPG2018 - are you still running into issues here? I'm curious if you've tried your set-up with v0.3 of ML-Agents.

**Comment by 3DAPPG2018** [comment] 2018-04-12 11:45
Hi, 
I stepped away from the machine learning to work on another project. I will try to building again in V.3 to see whether it fixed the issue & will let you know.

Thank you for the email.
Debbie

**Comment by xiaomaogy** [comment] 2018-04-12 17:27
@3DAPPG2018 For training, we replaced the PPO.ipynb with learn.py script. Please refer to https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-ML-Agents.md for how to use that. Also we are no longer supporting Python 2. 

Also regarding all the examples with Action Type Space = "Discrete" not working , we will looking into that.

**Comment by 3DAPPG2018** [comment] 2018-04-22 17:54
Thank you for the update. I will check it out.

**Comment by xiaomaogy** [comment] 2018-05-17 22:02
Hi @3DAPPG2018, the previous version of TensorFlowSharp plugin for iOS was missing a certain operator in the complied libtensorflow-core.a which is used in discrete mode, and that's the cause for the issue you were seeing. In the new TensorFlowSharp plugin for 1.7.1 listed in the PR https://github.com/Unity-Technologies/ml-agents/pull/746 we've fixed that issue, and now it should work for the discrete mode for iOS. 

If you still run into any issue with this plugin, please let me know.

**Comment by 3DAPPG2018** [comment] 2018-05-19 13:31
Thank you so much. I appreciate your following up on this.

**Comment by eshvk** [comment] 2018-06-08 22:37
Hey @3DAPPG2018, we are going to close this issue for now. Hopefully you were able to solve your issue, if not please feel free to reopen the issue again.

**Closed by eshvk** 2018-06-08 22:37 UTC
Labels: help-wanted, needs-info
