### ISSUE TITLE
Memory Leak on Linux

### ISSUE THREAD

**Issue by atapley** [Unity-Technologies/ml-agents#1402] opened 2018-11-05 18:44 UTC
Hi,

I have been using Unity ml-agents on my Mac to create environments. I then build the environment for Linux and upload it to git in order to pull the environment down on a Linux machine. When I use the environment on the Linux machine, I run the learn.py algorithm, but it continues to use more and more memory until it runs out and it crashes. 

I am running on Ubuntu 16.04 with ml-agents 0.4.0b and Unity 2017.2.0f1.

I know this was an issue with textures in the past, but the version of ml-agents that I have is after this issue was fixed.

**Comment by icaro56** [comment] 2018-11-13 19:56
My ML version 0.5 is also has this problem in Linux. The memory increase, increase ....

**Comment by xiaomaogy** [comment] 2018-11-15 05:13
This is a known issue that is on our to fix bug list.

**Comment by valanchik** [comment] 2018-11-17 19:01
Resources.UnloadUnusedAssets();

**Comment by arixlin** [comment] 2018-11-30 08:32
@xiaomaogy  is fix bug on Version 0.6  ?

**Comment by xiaomaogy** [comment] 2018-12-03 19:10
@arixlin Not yet.

**Comment by arixlin** [comment] 2018-12-05 01:09
@xiaomaogy  Thanks!

**Comment by tjad** [comment] 2019-05-13 23:10
any pointers to what the cause of this is ?

**Comment by atapley** [comment] 2019-05-13 23:15
In my opinion it could either be an issue on Unity's end with the visual observations, or an issue with Tensorflow itself. I have seen a few things saying that Tensorflow has a memory leak like this. I don't have the issue with vector observations though, so I'm not sure.

**Comment by tjad** [comment] 2019-05-14 07:20
@atapley Thanks for the fast reply. Yes, I suspected TF too, but will need to do some profiling to confirm that. The unity process (executable) itself seems stable, the python side is doing horrible things. Will post updates.

**Comment by tjad** [comment] 2019-05-14 09:49
Using mlagents 0.7 with TF 1.13.1 results with the same memory leak. Could be a TF usage error - not freeing memory when it should be freed from the session? 

Onwards...

**Comment by tjad** [comment] 2019-05-14 09:56
Why I say it may be a usage error, is that utilizing rainbow (dopamine) with the same environment does not result in the memory leak. So it can't be TF alone - well it could, but not likely ?

**Comment by tjad** [comment] 2019-05-14 10:34
@xiaomaogy let me in on any knowns - perhaps including where this bug is being managed please-, would like to keep eye on progress and provide input.

**Comment by tjad** [comment] 2019-05-14 13:52
From what I can tell, it's got to do with the trainer's accumulation of experiences

**Comment by tjad** [comment] 2019-05-14 14:38
Located the problem. Will see if I can get to the bottom of this and submit a PR.

**Comment by xiaomaogy** [comment] 2019-05-15 18:37
This bug is mainly being tracked on this issue. We also have a internal Trello board, which just links to this issue.

**Comment by tjad** [comment] 2019-05-25 18:51
@xiaomaogy It's not the most desirable fix, but it does the job.

Ideally the training and eval would be completely decoupled, but that's a larger task than have time for at present. 

This PR ultimately stops the buffer from being filled at all during training, hence no leak. Alternatively control flow could have been added as to clear the buffer during eval after it fills, would be fruitless though.

**Comment by tjad** [comment] 2019-05-25 18:55
Ah, ignore the first commit (be5e0ea). I split some coupled changes, the patch is in 6fc56f7

**Comment by xiaomaogy** [comment] 2019-05-29 00:26
Hence no leak during the evaluation. But the training will still have memory leak, am I correct? @tjad

**Comment by tjad** [comment] 2019-08-08 22:17
The training wont have a leak - as far as I remember, I'll confirm that. The way in which the training works clears the buffer ,but during eval it wasn't training, and hence not clearing the buffer.

**Comment by tjad** [comment] 2019-08-08 22:20
Probably why it's not been such a major issue :-)

**Comment by tjad** [comment] 2019-08-08 22:24
I suspected when I looked into this issue that there may have been lack of direction where the actual memory leak was. I trained fine for hours on end. Evaluation wasn't happening as easily.

**Comment by harperj** [comment] 2019-09-24 20:08
It looks like this issue has been solved, so I'm going to close it.  Thanks, and feel free to reopen if needed.

**Closed by harperj** 2019-09-24 20:08 UTC
Labels: bug
