### ISSUE TITLE
BananaImitation Collectors Example 

### ISSUE THREAD

**Issue by palomagr** [Unity-Technologies/ml-agents#546] opened 2018-03-27 21:12 UTC
Hi,
The BananaImitation Collectors Example has the following error when in player mode:

NullReferenceException: Object reference not set to an instance of an object
BananaAgent.CollectObservations () (at Assets/ML-Agents/Examples/BananaCollectors/Scripts/BananaAgent.cs:47)
Agent.SendInfoToBrain () (at Assets/ML-Agents/Scripts/Agent.cs:511)
Agent.SendInfo () (at Assets/ML-Agents/Scripts/Agent.cs:829)
Academy.EnvironmentStep () (at Assets/ML-Agents/Scripts/Academy.cs:475)
Academy.FixedUpdate () (at Assets/ML-Agents/Scripts/Academy.cs:507)

My guess is that the ray is not instantiated, is this the issue?
Thanks

**Comment by xiaomaogy** [comment] 2018-03-28 21:25
Maybe the latest 0.3.0b fix solves this problem. Have you pulled the newest code and retried?

**Comment by palomagr** [comment] 2018-03-30 19:13
Yes it does! runs perfectly. Thanks,

**Comment by mmattar** [comment] 2018-04-12 00:55
@palomagr I believe the issue is that `ML-AgentsWithPlugin` has not been updated to 0.3.0b. We'll fix in the next week.

**Comment by xiaomaogy** [comment] 2018-05-17 21:18
@palomagr We are no longer supporting the unitypackage with ML-Agents, and hopefully people would all directly use the github repo to setup the project. 

Since this issue is related to the legacy ML-agentsWithPlugin.unitypackage that has been deprecated, I'm closing this issue.

**Closed by xiaomaogy** 2018-05-17 21:18 UTC
Labels: help-wanted, needs-info
