### ISSUE TITLE
NNModel doesn't contain a definition for Value

### ISSUE THREAD

**Issue by epiccoder2** [Unity-Technologies/ml-agents#3593] opened 2020-03-07 18:29 UTC
**Describe the bug**
I'm using Unity 2019.3.4f1 and Ml_Agents 0.13.1. I imported the Unity assets from the folder, and I got an error. See screenshots for the error.

**To Reproduce**
1. Download ML_Agents 0.13.1
2. Import the assets
3. Install package from the package manager

**Screenshots**
https://gyazo.com/c6c3aa75dcdd09f2d9fedb81cbda45cd

**Environment (please complete the following information):**
- OS + version: Windows 10
- _ML-Agents version_: _ML_agents 0.13.1

**Comment by chriselion** [comment] 2020-03-07 18:39
Hi,
This is a duplicate of https://github.com/Unity-Technologies/ml-agents/issues/3336

You should either:
* downgrade barracuda to 0.4.0
* upgrade ML-Agents to 0.14.1
* use the branch from https://github.com/Unity-Technologies/ml-agents/pull/3339

I'm going to close this; please re-open if you have more problems.

**Closed by chriselion** 2020-03-07 18:39 UTC
Labels: duplicate
