### ISSUE TITLE
No samples other than the 3DBall

### ISSUE THREAD

**Issue by leonard-pak** [Unity-Technologies/ml-agents#5968] opened 2023-08-21 18:32 UTC
**Describe the bug**
There are many ready-made examples described [here](https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Learning-Environment-Examples.md) to test the ml agent package, but if you download the latest version of the package, you will only find the 3DBall sample.

**To Reproduce**
1. Go to Package Manager
2. Click on ML Agents -> Install
3. Add com.unity.ml-agents.extensions like [this](https://github.com/Unity-Technologies/ml-agents/blob/release_20_docs/com.unity.ml-agents.extensions/Documentation~/com.unity.ml-agents.extensions.md#github-via-package-manager)
4. Don`t see any samples other than 3DBall

**Screenshots**
![image](https://github.com/Unity-Technologies/ml-agents/assets/38388336/b554d536-396d-4ab2-9a58-e8b5e46eb709)

**Environment (please complete the following information):**
- Unity Version: Unity 2022.3.7f1
- OS + version: Windows 10
- _ML-Agents version_: ML-Agents v2.3.0-exp.3

**Comment by miguelalonsojr** [comment] 2023-10-08 17:31
If you want more examples, you'll have to clone this repo. We don't want more than the one example in the package, as it bloats the package size unnecessarily. Closing as this is not a bug.

**Closed by miguelalonsojr** 2023-10-08 17:31 UTC
Labels: bug
