### ISSUE TITLE
Import numpy issues

### ISSUE THREAD

**Issue by fool1280** [Unity-Technologies/ml-agents#1727] opened 2019-02-19 09:14 UTC
Hi everyone, 
I'm following this tutorial. However, as far as I came to Training the Environment section, 

> mlagents-learn config/config.yaml --run-id=RollerBall-1 --train

An error occurred. The error are following:

> ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: DLL load failed: The specified module could not be found.

I have no idea how to fix it. This is my first time using ml-agents and the results from wandering around google didn't help much. Please help! Thank you

**Comment by fool1280** [comment] 2019-02-19 09:17
> # packages in environment at C:\Users\The False Henry\Anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py36he6757f0_0
absl-py                   0.7.0                    pypi_0    pypi
alabaster                 0.7.11                   py36_0
anaconda                  5.3.0                    py36_0
anaconda-client           1.7.2                    py36_0
anaconda-navigator        1.7.0                    py36_0
anaconda-project          0.8.2                    py36_0
appdirs                   1.4.3            py36h28b3542_0
asn1crypto                0.24.0                   py36_0
astor                     0.7.1                    pypi_0    pypi
astroid                   2.0.4                    py36_0
astropy                   3.0.4            py36hfa6e2cd_0
atomicwrites              1.2.1                    py36_0
attrs                     18.2.0           py36h28b3542_0
automat                   0.7.0                    py36_0
babel                     2.6.0                    py36_0
backcall                  0.1.0                    py36_0
backports                 1.0                      py36_1
backports.shutil_get_terminal_size 1.0.0                    py36_2
beautifulsoup4            4.6.3                    py36_0
bitarray                  0.8.3            py36hfa6e2cd_0
bkcharts                  0.2              py36h7e685f7_0
blas                      1.0                         mkl
blaze                     0.11.3                   py36_0
bleach                    1.5.0                    pypi_0    pypi
blosc                     1.14.4               he51fdeb_0
bokeh                     0.13.0                   py36_0
boto                      2.49.0                   py36_0
bottleneck                1.2.1            py36h452e1ab_1
bzip2                     1.0.6                hfa6e2cd_5
ca-certificates           2018.03.07                    0
certifi                   2018.8.24                py36_1
cffi                      1.11.5           py36h74b6da3_1
chardet                   3.0.4                    py36_1
click                     6.7              py36hec8c647_0
cloudpickle               0.5.5                    py36_0
clyent                    1.2.2                    py36_1
colorama                  0.3.9            py36h029ae33_0
comtypes                  1.1.7                    py36_0
conda                     4.6.4                    py36_0
conda-build               3.4.1                    py36_0
conda-env                 2.6.0                h36134e3_1
conda-verify              2.0.0            py36h065de53_0
console_shortcut          0.1.1                         3
constantly                15.1.0           py36h28b3542_0
contextlib2               0.5.5            py36he5d52c0_0
cryptography              2.3.1            py36h74b6da3_0
curl                      7.61.0               h7602738_0
cycler                    0.10.0           py36h009560c_0
cython                    0.28.5           py36h6538335_0
cytoolz                   0.9.0.1          py36hfa6e2cd_1
dask                      0.19.1                   py36_0
dask-core                 0.19.1                   py36_0
datashape                 0.5.4                    py36_1
decorator                 4.3.0                    py36_0
defusedxml                0.5.0                    py36_1
distributed               1.23.1                   py36_0
docopt                    0.6.2                    pypi_0    pypi
docutils                  0.14             py36h6012d8f_0
entrypoints               0.2.3                    py36_2
et_xmlfile                1.0.1            py36h3d2d736_0
fastcache                 1.0.2            py36hfa6e2cd_2
filelock                  3.0.8                    py36_0
flask                     1.0.2                    py36_1
flask-cors                3.0.6                    py36_0
freetype                  2.9.1                ha9979f8_1
gast                      0.2.2                    pypi_0    pypi
get_terminal_size         1.0.0                h38e98db_0
gevent                    1.3.6            py36hfa6e2cd_0
glob2                     0.6                      py36_0
greenlet                  0.4.15           py36hfa6e2cd_0
grpcio                    1.11.1                   pypi_0    pypi
h5py                      2.8.0            py36h3bdd7fb_2
hdf5                      1.10.2               hac2f561_1
heapdict                  1.0.0                    py36_2
html5lib                  0.9999999                pypi_0    pypi
hyperlink                 18.0.0                   py36_0
icc_rt                    2017.0.4             h97af966_0
icu                       58.2                 ha66f8fd_1
idna                      2.7                      py36_0
imageio                   2.4.1                    py36_0
imagesize                 1.1.0                    py36_0
incremental               17.5.0                   py36_0
intel-openmp              2019.0                      118
ipykernel                 4.9.0                    py36_1
ipython                   6.5.0                    py36_0
ipython_genutils          0.2.0            py36h3c5d0ee_0
ipywidgets                7.4.1                    py36_0
isort                     4.3.4                    py36_0
itsdangerous              0.24                     py36_1
jdcal                     1.4                      py36_0
jedi                      0.12.1                   py36_0
jinja2                    2.10                     py36_0
jpeg                      9b                   hb83a4c4_2
jsonschema                2.6.0            py36h7636477_0
jupyter                   1.0.0                    py36_7
jupyter_client            5.2.3                    py36_0
jupyter_console           5.2.0                    py36_1
jupyter_core              4.4.0                    py36_0
jupyterlab                0.34.9                   py36_0
jupyterlab_launcher       0.13.1                   py36_0
keyring                   13.2.1                   py36_0
kiwisolver                1.0.1            py36h6538335_0
lazy-object-proxy         1.3.1            py36hfa6e2cd_2
libcurl                   7.61.0               h7602738_0
libiconv                  1.15                 h1df5818_7
libpng                    1.6.34               h79bbb47_0
libsodium                 1.0.16               h9d3ae62_0
libssh2                   1.8.0                hd619d38_4
libtiff                   4.0.9                h36446d0_2
libxml2                   2.9.8                hadb2253_1
libxslt                   1.1.32               hf6f1972_0
llvmlite                  0.24.0           py36h6538335_0
locket                    0.2.0            py36hfed976d_1
lxml                      4.2.5            py36hef2cd61_0
lzo                       2.10                 h6df0209_2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markdown                  3.0.1                    pypi_0    pypi
markupsafe                1.0              py36hfa6e2cd_1
matplotlib                2.2.3            py36hd159220_0
mccabe                    0.6.1                    py36_1
menuinst                  1.4.14           py36hfa6e2cd_0
mistune                   0.8.3            py36hfa6e2cd_1
mkl                       2018.0.3                      1
mkl-service               1.1.2            py36hb217b18_5
mkl_fft                   1.0.4            py36h1e22a9b_1
mkl_random                1.0.1            py36h77b88f5_1
mlagents                  0.6.0                     dev_0    <develop>
more-itertools            4.3.0                    py36_0
mpmath                    1.0.0                    py36_2
msgpack-python            0.5.6            py36he980bc4_1
msys2-conda-epoch         20160418                      1
multipledispatch          0.6.0                    py36_0
navigator-updater         0.1.0            py36h8a7b86b_0
nbconvert                 5.4.0                    py36_1
nbformat                  4.4.0            py36h3a5bc1b_0
networkx                  2.1                      py36_0
nltk                      3.3.0                    py36_0
nose                      1.3.7                    py36_2
notebook                  5.6.0                    py36_0
numba                     0.39.0           py36h830ac7b_0
numexpr                   2.6.8            py36h9ef55f4_0
numpy                     1.14.5                   pypi_0    pypi
numpydoc                  0.8.0                    py36_0
odo                       0.5.1            py36h7560279_0
olefile                   0.46                     py36_0
openpyxl                  2.5.6                    py36_0
openssl                   1.0.2p               hfa6e2cd_0
packaging                 17.1                     py36_0
pandas                    0.23.4           py36h830ac7b_0
pandoc                    1.19.2.1             hb2460c7_1
pandocfilters             1.4.2                    py36_1
parso                     0.3.1                    py36_0
partd                     0.3.8            py36hc8e763b_0
path.py                   11.1.0                   py36_0
pathlib2                  2.3.2                    py36_0
patsy                     0.5.0                    py36_0
pep8                      1.7.1                    py36_0
pickleshare               0.7.4            py36h9de030f_0
pillow                    5.2.0            py36h08bbbbd_0
pip                       10.0.1                   py36_0
pkginfo                   1.4.2                    py36_1
pluggy                    0.7.1            py36h28b3542_0
ply                       3.11                     py36_0
prometheus_client         0.3.1            py36h28b3542_0
prompt_toolkit            1.0.15           py36h60b8f86_0
protobuf                  3.6.1                    pypi_0    pypi
psutil                    5.4.7            py36hfa6e2cd_0
py                        1.6.0                    py36_0
pyasn1                    0.4.4            py36h28b3542_0
pyasn1-modules            0.2.2                    py36_0
pycodestyle               2.4.0                    py36_0
pycosat                   0.6.3            py36hfa6e2cd_0
pycparser                 2.18                     py36_1
pycrypto                  2.6.1            py36hfa6e2cd_9
pycurl                    7.43.0.2         py36h74b6da3_0
pyflakes                  2.0.0                    py36_0
pygments                  2.2.0            py36hb010967_0
pylint                    2.1.1                    py36_0
pyodbc                    4.0.24           py36h6538335_0
pyopenssl                 18.0.0                   py36_0
pyparsing                 2.2.0                    py36_1
pyqt                      5.9.2            py36h6538335_2
pysocks                   1.6.8                    py36_0
pytables                  3.4.4            py36he6f6034_0
pytest                    3.8.0                    py36_0
pytest-arraydiff          0.2              py36h39e3cac_0
pytest-astropy            0.4.0                    py36_0
pytest-doctestplus        0.1.3                    py36_0
pytest-openfiles          0.3.0                    py36_0
pytest-remotedata         0.3.0                    py36_0
python                    3.6.6                hea74fb7_0
python-dateutil           2.7.3                    py36_0
pytz                      2018.5                   py36_0
pywavelets                1.0.0            py36h452e1ab_0
pywin32                   223              py36hfa6e2cd_1
pywinpty                  0.5.4                    py36_0
pyyaml                    3.13             py36hfa6e2cd_0
pyzmq                     17.1.2           py36hfa6e2cd_0
qt                        5.9.6            vc14h1e9a669_2
qtawesome                 0.4.4            py36h5aa48f6_0
qtconsole                 4.4.1                    py36_0
qtpy                      1.5.0                    py36_0
requests                  2.19.1                   py36_0
rope                      0.11.0                   py36_0
ruamel_yaml               0.15.46          py36hfa6e2cd_0
scikit-image              0.14.0           py36h6538335_1
scikit-learn              0.19.2           py36heebcf9a_0
scipy                     1.1.0            py36h4f6bf74_1
seaborn                   0.9.0                    py36_0
send2trash                1.5.0                    py36_0
service_identity          17.0.0           py36h28b3542_0
setuptools                40.2.0                   py36_0
simplegeneric             0.8.1                    py36_2
singledispatch            3.4.0.3          py36h17d0c80_0
sip                       4.19.8           py36h6538335_0
six                       1.11.0                   py36_1
snappy                    1.1.7                h777316e_3
snowballstemmer           1.2.1            py36h763602f_0
sortedcollections         1.0.1                    py36_0
sortedcontainers          2.0.5                    py36_0
sphinx                    1.7.9                    py36_0
sphinxcontrib             1.0                      py36_1
sphinxcontrib-websupport  1.1.0                    py36_1
spyder                    3.3.1                    py36_1
spyder-kernels            0.2.6                    py36_0
sqlalchemy                1.2.11           py36hfa6e2cd_0
sqlite                    3.24.0               h7602738_0
statsmodels               0.9.0            py36h452e1ab_0
sympy                     1.2                      py36_0
tblib                     1.3.2            py36h30f5020_0
tensorboard               1.7.0                    pypi_0    pypi
tensorflow                1.7.1                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.8.1                    py36_1
testpath                  0.3.1            py36h2698cfe_0
tk                        8.6.8                hfa6e2cd_0
toolz                     0.9.0                    py36_0
tornado                   5.1              py36hfa6e2cd_0
tqdm                      4.26.0           py36h28b3542_0
traitlets                 4.3.2            py36h096827d_0
twisted                   18.7.0           py36hfa6e2cd_1
typed-ast                 1.1.0            py36hfa6e2cd_0
typing                    3.6.2            py36hb035bda_0
unicodecsv                0.14.1           py36h6450c06_0
urllib3                   1.23                     py36_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_0
wcwidth                   0.1.7            py36h3d5aa90_0
webencodings              0.5.1                    py36_1
werkzeug                  0.14.1                   py36_0
wheel                     0.31.1                   py36_0
widgetsnbextension        3.4.1                    py36_0
win_inet_pton             1.0.1                    py36_1
win_unicode_console       0.5              py36hcdbd4b5_0
wincertstore              0.2              py36h7fe50ca_0
winpty                    0.4.3                         4
wrapt                     1.10.11          py36hfa6e2cd_2
xlrd                      1.1.0                    py36_1
xlsxwriter                1.1.0                    py36_0
xlwings                   0.11.8                   py36_0
xlwt                      1.3.0            py36h1a4751e_0
yaml                      0.1.7                hc54c509_2
zeromq                    4.2.5                he025d50_1
zict                      0.1.3                    py36_0
zlib                      1.2.11               h8395fce_2
zope                      1.0                      py36_1
zope.interface            4.5.0            py36hfa6e2cd_0

**Comment by saragai** [comment] 2019-02-19 12:14
I got the same problem.
I guess it due to "ml-agents\ml-agents\setup.py" file.

The error occured as follows.
~~~
\ml-agents\ml-agents>conda create -n ml-agents python=3.6
\ml-agents\ml-agents>conda activate ml-agents
\ml-agents\ml-agents>pip install -e .
\ml-agents\ml-agents>python
Python 3.6.8 |Anaconda, Inc.| (default, Feb 11 2019, 15:03:47) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "E:\ProgramData\Anaconda3\envs\ml-agents\lib\site-packages\numpy\core\__i
nit__.py", line 16, in <module>
    from . import multiarray
ImportError: DLL load failed: The specified module could no be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\ProgramData\Anaconda3\envs\ml-agents\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "E:\ProgramData\Anaconda3\envs\ml-agents\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "E:\ProgramData\Anaconda3\envs\ml-agents\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "E:\ProgramData\Anaconda3\envs\ml-agents\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "E:\ProgramData\Anaconda3\envs\ml-agents\lib\site-packages\numpy\core\__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: DLL load failed: The specified module could not be found.
~~~

**Comment by awjuliani** [comment] 2019-02-19 18:38
Hi all, this looks to be a duplicate of #1701. I am closing this issue to move the conversation there.

**Closed by awjuliani** 2019-02-19 18:38 UTC
