### ISSUE TITLE
no camera sensor component

### ISSUE THREAD

**Issue by ChengXIZhang666** [Unity-Technologies/ml-agents#5964] opened 2023-08-16 12:29 UTC
**Describe the bug**
But the official document states that the visual information transmission is using the camera sensor component, but the Unity Editor 2022.3.3f1c1 cannot find this component anymore, and I have already installed the mlagents plugin

**Comment by jdmcgraw** [comment] 2023-08-16 19:33
Are there any other ML-Agents components you can find in Unity? I just checked release-20's default Project and I am able to search for and add the camera sensor to an agent in `SoccerTwos`.

Are you using the release version directly (which has its own install of ml-agents included, or installing from the Package Manager?

I'm using `Unity Editor 2022.3.7f1`
I'm using `ML Agents 2.3.0-exp.3` (installed from `../ml-agents/ml-agents-release_20/com.unity.ml-agents`)

The `CameraSensor.cs` and `CameraSensorComponent.cs` exists in `ml-agents-release_20\com.unity.ml-agents\Runtime\Sensors`

Does this issue occur if you open the project named `Project` with Unity Hub?

**Comment by ChengXIZhang666** [comment] 2023-08-17 03:42
thanks，my version is 2.0.1, but when I switched to the same version as yours, there was still no camera sensor component and there were warnings. And the editor recommends me to use 2.0.1

**Comment by ChengXIZhang666** [comment] 2023-08-17 03:45
And I can indeed see the Camera Sensor Component script in packages, but it is not present in the add component of the game object

**Comment by miguelalonsojr** [comment] 2023-10-08 17:30
I have confirmed the Camera sensor component is available in 2022.3 and can be added through the editor add component feature. It may be that your library cache needs to be rebuilt. Try re-importing all assets or close unity, delete the Library folder in your project and re-open it in Unity. Closing as this is not a bug.

**Closed by miguelalonsojr** 2023-10-08 17:30 UTC
Labels: bug
