### ISSUE TITLE
JsonSerializationException while training

### ISSUE THREAD

**Issue by AaronMeyers** [Unity-Technologies/ml-agents#213] opened 2017-12-27 01:33 UTC
I keep getting a JsonSerializationException when I'm training. Here is the contents of the unity-environment.log file:
[unity-environment.log](https://github.com/Unity-Technologies/ml-agents/files/1588149/unity-environment.log)

Not sure where it's coming from or what function on my Agent I need to give more information about...

**Comment by draxov** [comment] 2018-01-05 00:42
I am having this same problem trying to train some physics based floating objects to fly to points

I've attached my output log from the build that ran plus the python file and log. I can send the project over if that helps, seems like it's failing to receive a Json at some point. The Python file is a copy paste mostly from the 3D ball lesson with tweaks here and there (mainly in the max steps)

[mlUnityPython.txt](https://github.com/Unity-Technologies/ml-agents/files/1605202/mlUnityPython.txt)
[output_log.txt](https://github.com/Unity-Technologies/ml-agents/files/1605198/output_log.txt)
[unity-environment.log](https://github.com/Unity-Technologies/ml-agents/files/1605199/unity-environment.log)

**Comment by wouterhardeman** [comment] 2018-01-07 13:47
I had the same problem and I think I fixed it by creating the json file directly in the folder (not using jupyter). By copy-and-pasting from jupyter, it didn't parse properly. Maybe because of some line endings or spacing.

Let me know if it helps, because I'm not sure if that actually was the problem.

**Comment by zhenghongzhi** [comment] 2018-01-28 10:15
I also encounter this problem and the log file is exactly as the same.
The JsonSerializationException was thrown then deserializing the string at position 1460, or 2920(which is 2*1460).

I read the relative code and have no idea with this problem.
[unity-environment - 副本 (2).log](https://github.com/Unity-Technologies/ml-agents/files/1670982/unity-environment.-.2.log)
[unity-environment - 副本.log](https://github.com/Unity-Technologies/ml-agents/files/1670983/unity-environment.-.log)

**Comment by Lakrix** [comment] 2018-02-01 14:40
In my unity-environment.log I only get the current date. I have added Debug.Log statements in my AgentStep() method. Do you you guys have this problem?

**Comment by ruanrothmann** [comment] 2018-03-09 09:15
Has anyone had any luck with this issue? I'm not sure what JSON file @wouterhardeman is talking about here - I'd be willing to try anything. The error occurs at seemingly random intervals, so I can save/continue training, but having to manually restart each time rules out any kind of deep training.

My unity-environment.log looks similar to the other posted here. In Jupyter I get the following output:
https://pastebin.com/nXbvZff1

Any hints appreciated!!

**Comment by ruanrothmann** [comment] 2018-03-14 10:02
@zhenghongzhi that explanation looks like it might make sense, and I can confirm that I don't have the problem on 0.3 either. Unfortunately, complex continuous models do not train nearly as well on 0.3 currently, I believe this is a known bug.

**Comment by mmattar** [comment] 2018-04-11 21:34
Thanks for feedback @ruanrothmann, @zhenghongzhi. We've since released v0.3 of ML-Agents which includes several enhancements. I'm closing this out for now, but create a new issue if you run into any additional problems.

**Closed by mmattar** 2018-04-11 21:34 UTC
Labels: help-wanted
