### ISSUE TITLE
Increasing entropy

### ISSUE THREAD

**Issue by fedetask** [Unity-Technologies/ml-agents#3335] opened 2020-02-01 12:06 UTC
Hi,
I have a randomly generated environment changing every N-th episode. I observe during the training that the reward is -slowly- increasing, but entropy is increasing as well.

How should I interpret this? Should I reduce beta?

**Comment by MarkTension** [comment] 2020-02-03 10:16
Hard to say. Have you tried seeing what happens when you change beta?

How I understand entropy is:
When all actions have almost same probability, then Entropy will be high
When one action has near 1 probability, Entropy will be low

In the beginning of training, almost all actions have same probability. After some training, some actions get higher probability (in the direction of getting more rewards), and entropy is reduced over time.

I guess in your situation a cause could be your changing environment. I don't know how much it changes, and how often, but if the agent has to relearn every so many steps, then it's weights will need to readjust after such an update, which results into a more random policy, thus higher entropy.  Maybe test this by increasing N? If true, you'll probably see an increase in the entropy after each N.

Another thing could be that a changing environment every so many steps is very hard to learn for the agent, and the agent is in a local minimum of chance level policy. Can only be true though, if the reward and entropy go down a bit at first I guess.

**Comment by anupambhatnagar** [comment] 2020-02-03 22:35
@fedetask @MarkTension As of last week we have a unity forum for ML Agents. Github issues will be reserved for bugs and feature requests only. It would be great if you could continue the discussion in the forum so that its visible to other ML Agents users as well. Thanks! 

Closing the issue since it's not a bug/feature request.

**Closed by anupambhatnagar** 2020-02-03 22:35 UTC
Labels: discussion
