### ISSUE TITLE
NaN rewards with SAC only

### ISSUE THREAD

**Issue by niskander** [Unity-Technologies/ml-agents#3041] opened 2019-12-05 21:44 UTC
Hi, I tried the SAC trainer and I get NaN rewards whenever it updates (image attached). My environment is returning valid rewards and the issue does not exist for PPO. Any idea what could be wrong?

![SAC_nan_rewards_LI](https://user-images.githubusercontent.com/1988272/70276491-75ece900-177e-11ea-80ff-f6750a938051.jpg)

**Comment by chriselion** [comment] 2019-12-05 22:05
I can reproduce similar behavior with our examples (it's only NaN sometimes but not every time). I'll look into it.

**Comment by chriselion** [comment] 2019-12-05 22:42
I think the `NaN`s are coming from here
https://github.com/Unity-Technologies/ml-agents/blob/0796a1b5ff68a9e9b2b456d7088245edb2c50add/ml-agents/mlagents/trainers/sac/trainer.py#L241-L244
when `self.cumulative_returns_since_policy_update` is empty. It should be harmless, but we should probably output 0 or None in that situation.

@ervteng Any other thoughts?

**Comment by niskander** [comment] 2019-12-05 22:52
@chriselion This is literally all I'm seeing (it's never not NaN), despite the rewards always being valid in  the "Step" logs. So why would cumulative_returns_since_policy_update always be empty?

**Comment by niskander** [comment] 2019-12-05 22:59
If it helps, the Cumulative Reward graph in tensorboard contains valid values.

**Comment by ervteng** [comment] 2019-12-05 23:18
Hi @niskander, the code outputs nan there (when running in `--debug` mode) when there hasn't been a completed episode since the last policy update. Since SAC updates policy much more frequently than PPO, the probability of getting a nan in that message is much higher. However, the step logs happen at a much longer interval, so usually there has been a completed episode by then. The nans are entirely harmless. 

@chriselion you're probably right, we should output None or Invalid in that message (and coincidentally in the CSV log).

**Comment by niskander** [comment] 2019-12-05 23:43
@ervteng that's what I was thinking but does it make sense, in the screenshot, that an episode was completed and yet the next few returns were still NaN? 
I can try to save the output to double check, but I don't see a single non-NaN in the returns. 

On the other hand, it appears to be training "correctly" as far as I can see.  I just want to make sure these NaN values don't affect the training (which seems to be the case).

**Comment by ervteng** [comment] 2019-12-05 23:56
Yep, it makes sense, since it's episodes completed since last policy update. Every time it prints out a message, it's one policy update. So no episode was completed between the two messages, hence it's nan. By default SAC updates every environment step, so it's unlikely you'll see many non-nans.

**Comment by niskander** [comment] 2019-12-07 20:24
Alright, thanks for clarifying @ervteng @chriselion

**Comment by chriselion** [comment] 2019-12-09 17:49
We've got this logged as MLA-414 in our tracker. Closing this for now.

**Closed by chriselion** 2019-12-09 17:49 UTC
Labels: discussion
