### ISSUE TITLE
CTL+C not exiting cleanly and saving training

### ISSUE THREAD

**Issue by traveltrousers** [Unity-Technologies/ml-agents#582] opened 2018-04-05 16:05 UTC
I am a total python newb so that might be a factor but I'm happily training agents using Python 3.6.4 through an Anaconda Prompt and they're working fine. 

Now I'm trying to use imitation learning and need to sometimes terminate the training early, instead of letting it run its course. 

This is the error I get: 

forrtl: error (200): program aborting due to control-C event
Image              PC                Routine            Line        Source
libifcoremd.dll    00007FFDAFF994C4  Unknown               Unknown  Unknown
KERNELBASE.dll     00007FFDEF127EDD  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFDF2131FE4  Unknown               Unknown  Unknown
ntdll.dll          00007FFDF226EFC1  Unknown               Unknown  Unknown

Control + BREAK does the same.....

**Comment by traveltrousers** [comment] 2018-04-07 02:25
slightly answering myself but altering the following command line means you don't have to wait for 100% completion...

--save-freq=<n> Specifies how often (in steps) to save the model during training. Defaults to 50000.

**Comment by awjuliani** [comment] 2018-06-28 21:22
Hi @traveltrousers,

Thank you for bringing this issue to our attention. Unfortunately functionality across different Windows  versions and set-ups are not consistent. Can you tell us a little more about your Windows version?

**Comment by xiaomaogy** [comment] 2018-12-17 23:58
This is a duplicate of #980 so I'm closing it.

**Closed by xiaomaogy** 2018-12-17 23:58 UTC
Labels: bug

**Comment by xiaomaogy** [comment] 2019-01-08 01:39
This bug has been fixed with https://github.com/Unity-Technologies/ml-agents/pull/1558. The error message 
```
forrtl: error (200): program aborting due to control-C event
Image PC Routine Line Source
libifcoremd.dll 00007FFDAFF994C4 Unknown Unknown Unknown
KERNELBASE.dll 00007FFDEF127EDD Unknown Unknown Unknown
KERNEL32.DLL 00007FFDF2131FE4 Unknown Unknown Unknown
ntdll.dll 00007FFDF226EFC1 Unknown Unknown Unknown
```

still exist, which is related to this stackoverflow https://stackoverflow.com/questions/42653389/ctrl-c-causes-forrtl-error-200-rather-than-python-keyboardinterrupt-exception. Our fix get around this error by adding another ctrl-c event handler which saves the model before this error.
