### ISSUE TITLE
API Number is not Compatible

### ISSUE THREAD

**Issue by cmburgul** [Unity-Technologies/ml-agents#2478] opened 2019-08-30 13:25 UTC
UnityEnvironmentException: The API number is not compatible between Unity and python. Python API : API-9, Unity API : API-4.
Please go to https://github.com/Unity-Technologies/ml-agents to download the latest version of ML-Agents.

I don't find any update for API-4.

**Environment :**
- OS + version: Linux 16.04
- _ML-Agents version_: Unity 2017.4

![image](https://user-images.githubusercontent.com/20013792/64024203-d5948200-cb07-11e9-9d04-c45350724a13.png)

**Comment by vincentpierre** [comment] 2019-08-30 18:45
This error arrises because your Python ml-agents and your Unity ml-agents do not have the same version. To upgrade python, you need to run `pip3 install mlagents==X.Y.Z` where X.Y.Z is the version you want. To upgrade the unity code version, you must reclone and update all the files of [this folder](https://github.com/Unity-Technologies/ml-agents/tree/master/UnitySDK/Assets/ML-Agents) in you project.

Closing this issue as it is a duplicate of #1883, #2444 and #2182

**Closed by vincentpierre** 2019-08-30 18:45 UTC
Labels: bug
