### ISSUE TITLE
The Academy blocks the main thread for 4 seconds when initializing (trying to establish communication with python) when there are no training agents in the scene

### ISSUE THREAD

**Issue by Phong13** [Unity-Technologies/ml-agents#4633] opened 2020-11-10 17:59 UTC
**Describe the bug**
When first initializing (Academy.InitializeEnvironment), the Academy tries to establish communications with the python training process. If all the agents are inference and there is no python process then this blocks the main thread for four seconds waiting for a response from they python back end. 

When trying to create a game using ML-Agents (all agents have been trained and are running in inference mode), this is a very long pause for the players. Players will complain that the game is slow starting. 

This giant pause/freeze is unnecessary when all the agents Inference agents.

**To Reproduce**
Always happens

**Console logs / stack traces**

**Screenshots**

**Environment (please complete the following information):**
- Unity Version: 2019.4
- OS + version: Windows 10
- _ML-Agents version_: Version 7
- _Torch version_: using tensorflow
- _Environment_: always happens with any scene when all agents are in inference mode and there is no python process running.

**NOTE:** We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

**Comment by dongruoping** [comment] 2020-11-11 01:47
Hi,

I'd like to clarify a bit more about this issue:

1. Can you provide more details on how you get the 10 second delay (like how you measure this 10 sec, within editor or with binary build, etc)?
2. Can you reproduce this issue with any of the example scene?

From what I observed, if I load any one of the example scene and press the play button (no python running, all agents set to default or inference-only), it starts running right away without noticeable delay. 
More details on how you observed this long delay would be helpful.

**Comment by Ihsees** [comment] 2020-11-11 06:26
@dongruoping 

Player Logs start with 
```
Remaining time:8s
Remaining time:7s
Remaining time:6s
Remaining time:5s
Remaining time:4s
Remaining time:3s
Remaining time:2s
Remaining time:1s
Remaining time:0s
Timed out. Continuing without host connection.
```

**Comment by Phong13** [comment] 2020-11-11 20:25
Hello,

I measured the delay by using the System.Diagnostics.Stopwatch in Academy.InitializeEnvirontment

```
        void InitializeEnvironment()
        {
            ....
                System.Diagnostics.Stopwatch sw = new System.Diagnostics.Stopwatch();
                sw.Start();
                try
                {
                    var unityRlInitParameters = Communicator.Initialize(
                        new CommunicatorInitParameters
                        {
                            unityCommunicationVersion = k_ApiVersion,
                            unityPackageVersion = k_PackageVersion,
                            name = "AcademySingleton",
                            CSharpCapabilities = new UnityRLCapabilities()
                        });
                    UnityEngine.Random.InitState(unityRlInitParameters.seed);
                    // We might have inference-only Agents, so set the seed for them too.
                    m_InferenceSeed = unityRlInitParameters.seed;
                    TrainerCapabilities = unityRlInitParameters.TrainerCapabilities;
                    TrainerCapabilities.WarnOnPythonMissingBaseRLCapabilities();
                }
                catch
                {
                    Debug.Log($"" +
                        $"Couldn't connect to trainer on port {port} using API version {k_ApiVersion}. " +
                        "Will perform inference instead."
                    );
                    Communicator = null;
                }
                sw.Stop();
                Debug.Log("Time to attempt communications: " + sw.Elapsed);
            ....
        }
```

Note that the time does not seem to be consistent. I just tried again and it is now reporting four seconds. Yesterday it was reporting 10 seconds:

```
Time to attempt communications: 00:00:04.1327095
```
Just tested with the "Basic" scene and it too takes approximately four seconds

```
Time to init academy 00:00:04.1557059
```

**Comment by Phong13** [comment] 2020-11-11 20:45
Using "Release 7"

**Comment by dongruoping** [comment] 2020-11-13 00:17
Hi,

Thanks for the information. After some testing, this is issue is only on Windows and the same thing typically only takes ~0.9s on Mac.
I also got ~4s delay with windows machine, and a delay of a few seconds is indeed an inconvenience for running a game.

We'll look more into this and see if we can get a fix out soon. Thanks for reporting this.

**Comment by dongruoping** [comment] 2020-11-13 01:23
Internally tracked as [MLA-1582](https://jira.unity3d.com/browse/MLA-1582).

**Comment by Phong13** [comment] 2020-11-13 19:49
Thanks for looking into this.

**Comment by dongruoping** [comment] 2020-11-16 18:48
A few more questions I'd like to know about, when you observe this delay:
1. Are you running in editor or using a binary build?
2. Are you running this with python `mlagents-learn` command?

**Comment by Phong13** [comment] 2020-11-16 21:35
Running in the editor. I have not tested in a binary build.

Mot using the mlagents-learn command. All the agents in the scene have been configured to "Inference Only". The models were previously trained using training scenes and this is a game scene that is using the trained agents.

**Comment by dongruoping** [comment] 2020-11-16 21:57
So this delay is expected in the editor since we create the communicator in case we want to run in-editor training. 
With binary executable this issue doesn't exist. Does that help with your case?

Also I agree there's something we can make it better with the editor and we're looking into it.

**Comment by Phong13** [comment] 2020-11-16 22:16
Thanks for looking into this. Yes, this does help with my case. My main worry was the big lag spike when switching from the "lobby" scene to the first scene with agents in it. If it doesn't happen with builds that is fine.

It is still annoying in the editor though. It is valuable to be able to enter playmode and back very quickly to speed up debugging/development workflow. Thanks for looking at this.

**Comment by dongruoping** [comment] 2020-11-18 20:07
A quick fix for editor would be replacing this line in `com.unity.ml-agents/Runtime/Communicator/RpcCommunicator.cs`:
```       
            var result = m_Client.Exchange(WrapMessage(unityOutput, 200));
```

with

```
#if UNITY_EDITOR
            var result = m_Client.Exchange(WrapMessage(unityOutput, 200), deadline: DateTime.Now.AddSeconds(1));
#else
            var result = m_Client.Exchange(WrapMessage(unityOutput, 200));
#endif
```

We're working on fixing this with a larger change, but this is an easy fix if it really annoys you.

**Comment by Phong13** [comment] 2020-11-18 20:18
Nice, thanks. I will try that.

**Comment by fredleefarr** [comment] 2021-02-04 13:47
Was also experiencing this issue which I reported in the forum https://forum.unity.com/threads/editor-ml-agents-enterplaymode-time.1051160/

Have applied the suggested change to RpcCommunicator.cs and play mode time is greatly reduced.

**Comment by dongruoping** [comment] 2021-02-04 20:27
Hi @fredleefarr,

Thanks for letting us know, and glad the temporary solution works for you.
Sorry that we haven't gotten to fix it yet but we'll try to prioritize it.

**Comment by dongruoping** [comment] 2021-03-26 03:39
Update: 

After looking into this more, the 4 sec blocking happens in the first message exchange in Grpc no matter the connection succeeded or failed. It's something inside the Grpc package that's out of our control and only happens with Windows.

What we can do here is that we recently added ML-Agents package settings which you can configure in the editor for your project. It has the option "Connect to trainer" that you can specify whether you want to connect to trainer or not. This should allows you to skip the connection time if you don't want to connect at all.

ML-Agents package settings is currently in main and will be included in the next release. More details please checkout our [doc](https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Package-Settings.md).

**Closed by dongruoping** 2021-03-26 03:39 UTC
Labels: bug

**Comment by fredleefarr** [comment] 2021-03-26 13:24
Thanks @dongruoping will look out for the setting in release 16.
