### ISSUE TITLE
0.30.0 installation fails under Python 3.10

### ISSUE THREAD

**Issue by TheRisenPhoenix** [Unity-Technologies/ml-agents#5826] opened 2022-11-22 17:00 UTC
**Describe the bug**
I'm trying to install mlagents 0.30.0 with Python 3.10, as it is now officially supported. However, installation fails, because some dependency installs numpy==1.21.2, which is incomaptible with Python 3.10.
The problem seems to be with mlagents-env, which directly depends on numpy==1.21.2

**To Reproduce**
Run `pip3 install mlagents` in an Python 3.10.x environment and watch it fail

**Console logs / stack traces**
```
  Building wheel for numpy (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for numpy (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [271 lines of output]
      setup.py:63: RuntimeWarning: NumPy 1.21.2 may not yet support Python 3.10.
[....]
[....]
      TypeError: CCompiler_spawn() got an unexpected keyword argument 'env'

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numpy
```

**Environment (please complete the following information):**
- Unity Version: Unity 2021.3.12f1
- OS + version: Windows 10
- _ML-Agents version_: 0.30.0
- _Torch version_: 1.18.0

**Comment by TheRisenPhoenix** [comment] 2022-11-22 18:03
It looks like Dependabot already created PR #5814 which would solve this issue.
I also noticed, that numpy is referenced twice in the setup file, which probably shouldn't be the case:
```
    install_requires=[
        "cloudpickle",
        "grpcio>=1.11.0",
        "numpy>=1.14.1",             <====
        "Pillow>=4.2.1",
        "protobuf>=3.6",
        "pyyaml>=3.1.0",
        "gym>=0.21.0",
        "pettingzoo==1.15.0",
        "numpy==1.21.2",             <====
        "filelock>=3.4.0",
    ],
```

**Comment by hughperkins** [comment] 2022-12-17 21:53
Interestingly I have python 3.10 and numpy 1.21.2 installed, and everyting works swimmingly.

```
(10-unityml) Hughs-MacBook-Air:python hugh$ pip freeze | grep numpy
numpy==1.21.2
(10-unityml) Hughs-MacBook-Air:python hugh$ python -V
Python 3.10.7
```

Maybe this problem is specific to windows though? (I'm on a Macbook M2)

**Comment by TheRisenPhoenix** [comment] 2022-12-27 11:35
Also, please be aware that numpy 1.24 removed the already deprecated float type and replaced it with the python equivalent. However, it is still used in some places of the mlagents lib, which breaks the code.
I therefore suggest to either migrate those code segments, or restrict numpy to <1.24.

@hughperkins Perhaps, I think it has something to do with building the wheels, and some build dependencies might be OS specific, do it's possible that this is a Windows-only issue.

**Comment by StefanoCecere** [comment] 2023-01-22 23:06
ml-agents 0.30.0 has this consttraints: python_requires=">=3.8.13,<=3.10.8",
latest Python is 3.10.9 ... we have ot to install Python 3.10.8 or modify /ml-agents/setup.py

**Comment by hughperkins** [comment] 2023-01-22 23:09
Good observation. Really that constraint should probably be `>=3.8.13,<4.0.0` I reckon?

**Comment by hughperkins** [comment] 2023-01-22 23:10
(or I suppose one could do `>=3.8.13,<3.11.0`, if one doesn't feel that python follows semver. But I think python do a reasonable job on semver?)

**Comment by Marioc9955** [comment] 2023-01-24 23:03
I am having the exact issue with python 3.10.8, torch 1.13.1, pip 22.3.1. What can I do?

**Comment by TheRisenPhoenix** [comment] 2023-01-25 08:24
Currently, you have to clone the repository, and **adjust** the following lines:
In `ml-agents/setup.py`: 
`python_requires=">=3.8.13,<3.11"` (line 82)

In `ml-agents-envs/setup.py`:
`"numpy>=1.14.1,<1.24"` (line 54)
and
`python_requires=">=3.8.13,<3.11"` (line 63)

and **delete** `"numpy==1.21.2"` (line 60)

Then, **first install torch** using your needed configuration (https://pytorch.org/get-started/locally/) and then install your locally changed python packages:
```
pip3 install -e ./ml-agents-envs
pip3 install -e ./ml-agents
```

I hope this helps!

**Comment by StefanoCecere** [comment] 2023-01-25 15:24
anyway i solved installing Python 3.9.x

I hope the maintainers fix these limits ASAP, since it's quite an issue to manage so many different Python versions (especially in multi-platform mac+windows classes)

**Comment by zalogarciam** [comment] 2023-03-30 01:27
Hello

I could make it work with this config:

1. Create Conda env with Python 3.8.16
2. Install these
  % conda install numpy
  % conda install Pytorch=1.8.0
  % conda install h5py
  % conda install grpcio

3. If pytorch is not available from current channels try this
conda install -c conda-forge Pytorch=1.8.0
or try this
conda install -c pytorch pytorch=1.8.0

4. Then you may have problems with PIL error
Just:
pip uninstall pillow
pip install pillow

5. Same, you may have an error with DLL load from h5py
pip uninstall h5py
pip install h5py

If is still missing something (that I dont think so) ... pip install scipy

Test with mlagents-learn --help

Regards

**Comment by barsgunduz** [comment] 2023-10-10 18:39
This issue still there for release branch 21. I used [TheRisenPhoenix](https://github.com/TheRisenPhoenix)'s method solve, but I think it should be fixed before closing this ticket.

**Comment by miguelalonsojr** [comment] 2023-10-10 18:52
I have no issues installing mlagents from pypi and do not get the numpy issue described here. ML-Agents release 21 is pinned to python version 3.10.12. Please make sure that your conda env is set to use this version of python. Otherwise you'll likely run into problems.

**Comment by barsgunduz** [comment] 2023-10-10 19:00
Yes, my conda env is set to use 3.10.12. However the numpy version in [setup.py](https://github.com/Unity-Technologies/ml-agents/blob/97386af74e0153ee045fb2240516f5734692680c/ml-agents-envs/setup.py#L63C9-L63C24) is "numpy==1.21.2".


And python 3.10.12 and numpy 1.21.2 is not compatible. That was the error I got. Then I changed numpy version in setup.py to "numpy>=1.14.1,<1.24" to solve this error. And it installed numpy 1.23.5.

**Comment by miguelalonsojr** [comment] 2023-10-10 19:13
I cannot reproduce this error on mac or linux. Are trying this on Windows?

**Comment by barsgunduz** [comment] 2023-10-10 19:14
yes I'm on Windows 10

**Comment by trsh** [comment] 2023-10-10 19:20
![Uploading 2023-10-10_222001.png…]()

**Comment by trsh** [comment] 2023-10-10 19:20
![2023-10-10_222001](https://github.com/Unity-Technologies/ml-agents/assets/3727523/337674db-5878-4904-96c2-bdff8e26c77e)

**Comment by trsh** [comment] 2023-10-10 19:32
This might be my limited view on things, but most Unity devs I know (90%) work on Windows, so taking mac & linux first approach might be not a wise idea and always come back with issues.

**Comment by miguelalonsojr** [comment] 2023-10-10 22:15
Should be fixed on develop once this PR lands. https://github.com/Unity-Technologies/ml-agents/pull/5997

**Comment by miguelalonsojr** [comment] 2023-10-11 10:56
PR Landed. Closing.

**Closed by miguelalonsojr** 2023-10-11 10:56 UTC
Labels: bug

**Comment by jcobosmeta** [comment] 2023-10-24 14:39
Had this issue as well, release 21 didn't work for me at all (Windows) for the reasons listed here, however after struggling with different python and numpy versions I came across this page! Just moving to the develop branch to include the bumped numpy version worked for me. Should there be a mention of this somewhere in [the documentation](https://unity-technologies.github.io/ml-agents/Installation/)? I don't know if others are also having problems but it would've saved me a lot of time if this was in the release or I'd known about it before

**Comment by parthshetty** [comment] 2023-11-17 01:58
Im also having the same issue, however changing the numpy version in the setup.py file to numpy = 1.21.6 worked to alleviate the issue but runs into a warning that it fails to initialise.
