### ISSUE TITLE
CoreBrainInternal.cs does not find namespace TensorFlow 

### ISSUE THREAD

**Issue by likeygame** [Unity-Technologies/ml-agents#552] opened 2018-03-30 01:01 UTC
I defined ENABLE_TENSORFLOW and installed TFSharpPlugin. when attached bytes script file to Graph Model of Brain and played, it works.
But it does not work to debug C# script in visual studio. 

here are errors.
`Error	CS0246	The type or namespace name 'TensorFlow' could not be found (are you missing a using directive or an assembly reference?)`
`Warning		The primary reference "TensorFlowSharp" could not be resolved because it was built against the ".NETFramework,Version=v4.6.1" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.6".`

**Comment by rgjones33** [comment] 2018-03-30 13:32
+1

**Comment by storedenen** [comment] 2018-04-05 10:12
+1

**Comment by ituni** [comment] 2018-04-09 07:04
+1

**Comment by entropia666** [comment] 2018-04-13 17:41
+1

**Comment by vincentpierre** [comment] 2018-04-14 06:47
I am unable to reproduce this bug. Can you tell me what platform, what version of visual studio and Unity do you use, where the error appears (VS or Unity Console)? I do not understand `But it does not work to debug C# script in visual studio.` Can you give more details and maybe a screenshot ?

**Comment by entropia666** [comment] 2018-04-14 08:02
When you press the button in VS "attach to unity" to run in debug mode, it doesn't work. Vincent, I can let you on my machine if you want, with teamviewer, and show you.

**Comment by entropia666** [comment] 2018-04-14 09:40
Unity Version 2017 3.1f1
VIsual Studio 2017 15.6.2
.net framework 4.7.02556
Microsoft Visual Studio Community 2017 
Version 15.6.2

**Details:**
VisualStudio.15.Release/15.6.2+27428.2005
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Community

C# Tools   2.7.0-beta3-62707-11. Commit Hash: 75dfc9b33ed624dff3985c7435c902c3c58c0e5c
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Visual Basic Tools   2.7.0-beta3-62707-11. Commit Hash: 75dfc9b33ed624dff3985c7435c902c3c58c0e5c
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Unity   3.6.0.5
Visual Studio Tools for Unity

**Comment by vincentpierre** [comment] 2018-04-14 21:45
Thank you for this information @entropia666  My Visual Studio is not connected to my Unity and no one in my team tried to connect the two. We only use Visual Studio to edit code and when we want to run it, we click the play button in the Unity Editor. The issue could be that Visual Studio needs to make sure that the .NET frameworks are compatible while Unity does not. Is it possible for you to play a scene with the internal brain without having to use Visual Studio? 
I am still unable to reproduce this problem, does it affect both Mac and Windows ?

**Comment by rgjones33** [comment] 2018-04-15 18:55
@vincentpierre how does your team single step through code if you do not use the VS debugger? I think the message is pretty clear - whomever built the Tensorflow DLL did it against 4.6.1 - Can we get a copy of the dll built with 4.6 instead?

**Comment by vincentpierre** [comment] 2018-04-15 21:46
Hi, We do not use the VS debugger at all. Like I said, we use VS to edit code and then run it in the editor. Thank you for brining this problem to our attention, I think the issue is that the VS debugger is stricter than the Unity editor when it comes to .NET version. Like you said, Unity is 4.6 and TensorFlowSharp is 4.6.1, so this problem will require some workaround. I would like to know if you can run the editor with internal brain or if the VS debugger prevents you from running the editor in play mode.

**Comment by staceyhaffner** [comment] 2018-04-15 23:05
I can confirm that we can still run the Unity editor with this, but when we try to attach Visual Studio to Unity to do debugging we run into the same issue above.

**Comment by rgjones33** [comment] 2018-04-17 00:51
@vincentpierre No issues in the editor that are apparent. It is only when run through the VS debugger. 

I believe you when you say you have not used VS debugger at all but sorry if  I can't understand how a programmer hasn't tried single step debugging before.

**Comment by xiaomaogy** [comment] 2018-04-17 02:00
@entropia666 @rgjones33 @staceyhaffner I am trying to do what you described, but I was not able to reproduce the bug. Here is the steps I took:

1. Set the Brain Type to "Internal" in 3DBall. 
2. Click to "Assets" -> "Open C# Project", the VS opens. 
3. Click the run button in the Unity Editor, the 3DBall scene starts balancing. 
4. Set a breakpoint in CoreBrainInternal.cs: 171. 
5. In VS, go to "Run" -> "Attach To Process", select "Unity Editor", "Debugger" is selected to be "Unity Debugger", then click "Attach". Now the 3DBall scene stops. 
6. From here I was able to single step through the code without any error. 

Please let me know where I was doing wrong or differently from you guys. Also the OS I used was mac, and the Visual Studio 7.4.2 (build 12), Unity Editor 2017.3.1f.

**Comment by staceyhaffner** [comment] 2018-04-17 14:19
Interesting - when I do the same steps that you outlined on Windows it attaches just fine. The issue seems to be tied to the "Attach to Unity" button within the tool bar. 

![image](https://user-images.githubusercontent.com/4108756/38875562-787956ae-420f-11e8-922d-c4664e3d8f1b.png)

For those of you on Windows, here are the steps that @xiaomaogy did in VS:

1. In VS, go to **Debug** -> **Attach To Process**, select **Unity.exe**, then click **Attach**.

It also seems to work for me if I go to **Debug** > **Attach Unity Debugger**.

**Comment by rgjones33** [comment] 2018-04-17 15:32
In my case I have imported the soccer example in my existing project. The scene objects related the ml-agents example are currently disabled. I am trying to debug another aspect of my game. I open a script in VS from Unity. I set a breakpoint. I click attach to Unity. VS does a build and fails due the error msg we are discussing. I am asked if I want to run the last successful build. If I click yes the attach continues. I can then press play in unity and proceed.

**Comment by xiaomaogy** [comment] 2018-04-17 21:12
So it seems the problem is solved with the way @staceyhaffner stated here. When we release the TensorflowSharp plugin compatible with Tensorflow 1.5 or 1.6, we will try to build it against .NET 4.6 instead of 4.6.1 to see if it works. 
If you guys think this issue is solved I will close it.

**Comment by Aarsh-Singh-Vishen** [comment] 2018-04-18 07:41
" we will try to build it against .NET 4.6 instead of 4.6.1 to see if it works." -xiaomaogy 
Have you guys done this yet?

**Comment by rgjones33** [comment] 2018-04-18 12:28
@xiaomaogy It is a work around so you avoid the compiler warning. I think it still needs a proper solution as you mentioned. Someone needs to understand if System.ValueTuple 4.4.0 is a hard requirement.

**Comment by xiaomaogy** [comment] 2018-04-19 22:53
@Aarsh-Singh-Vishen  @rgjones33 We are actually working on upgrading the TensorflowSharp from 1.4 to 1.5 or 1.6. Along with that upgrade we will try to build against .NET 4.6 instead of .NET 4.6.1.

**Comment by hsaikia** [comment] 2018-04-28 11:34
+1 same issue.

On VS Code : 

`The primary reference "TensorFlowSharp" could not be resolved because it was built against the ".NETFramework,Version=v4.6.1" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.6".
`
On Unity Editor : 

```
UnityAgentsException: The tensorflow graph needs an input for recurrent_in  of type DT_FLOAT
CoreBrainInternal.DecideAction (System.Collections.Generic.Dictionary`2[TKey,TValue] agentInfo) (at Assets/ML-Agents/Scripts/CoreBrainInternal.cs:334)
Brain.DecideAction () (at Assets/ML-Agents/Scripts/Brain.cs:241)
Academy.EnvironmentStep () (at Assets/ML-Agents/Scripts/Academy.cs:477)
Academy.FixedUpdate () (at Assets/ML-Agents/Scripts/Academy.cs:507)
```

**Comment by hsaikia** [comment] 2018-04-28 11:36
This is strange because up until a few days ago, Internal brain was working. I wonder what the issue is.

**Comment by lagidigu** [comment] 2018-04-30 10:41
Got the same error, cannot run anything because of Internal Brain..

**Comment by hsaikia** [comment] 2018-05-01 11:14
Any updates on this? Without internal brain working, it's hard to make progress. Any workarounds will also be appreciated!

**Comment by xiaomaogy** [comment] 2018-05-01 17:34
@lagidigu @hsaikia So for both of you, even the workaround I mentioned above doesn't work?

**Comment by hsaikia** [comment] 2018-05-02 10:45
I didn't quite catch which workaround you are referring to. the bug doesn't have anything to do with Visual Studio. There is an error on the Unity editor itself when I load my internal brain model and run the environment.

This is the error 
```
UnityAgentsException: The tensorflow graph needs an input for recurrent_in  of type DT_FLOAT
CoreBrainInternal.DecideAction (System.Collections.Generic.Dictionary`2[TKey,TValue] agentInfo) (at Assets/ML-Agents/Scripts/CoreBrainInternal.cs:334)
Brain.DecideAction () (at Assets/ML-Agents/Scripts/Brain.cs:241)
Academy.EnvironmentStep () (at Assets/ML-Agents/Scripts/Academy.cs:477)
Academy.FixedUpdate () (at Assets/ML-Agents/Scripts/Academy.cs:507)
```

**Comment by xiaomaogy** [comment] 2018-05-03 01:11
@hsaikia 

The workaround is mentioned in my previous comment which said: 

"I am trying to do what you described, but I was not able to reproduce the bug. Here is the steps I took:....."

However your error in the Unity seems unrelated with the TensorflowSharp version. Your error message said tensorflow side is looking for a input with name recurrent_in with type DT_FLOAT. 

Did your code use LSTM? Could you please post your code and your trainer_config.yaml?

**Comment by hsaikia** [comment] 2018-05-03 10:14
@xiaomaogy 

Yes I use LSTM alongside imitation learning. Here is my agent --

https://github.com/hsaikia/UnityMLAgents/blob/master/SocialWalkerImitation/SWAgent.cs

My trainer_config.yaml file is here --

https://github.com/hsaikia/UnityMLAgents/blob/master/SocialWalkerImitation/trainer_config.yaml

My Brain is called SWStudent which is the last entry in the config file.

**Comment by lagidigu** [comment] 2018-05-07 12:16
@xiaomaogy the problem is that I cannot even do step 1., as I cannot modify scripts, as long as the following message appears: 

> Assets/ML-Agents/Scripts/CoreBrainInternal.cs(12,7): error CS0246: The type or namespace name `TensorFlow' could not be found. Are you missing an assembly reference?

Can't really do anything, as the scene won't run because of that. Tensorflow has been installed.

**Comment by xiaomaogy** [comment] 2018-05-07 20:49
@hsaikia I think your error is related with your LSTM usage. Could you post your snapshot of your Brain Script?

**Comment by cr545l** [comment] 2018-05-07 23:49
PlayerSetting -> Scriptomg Define Symbols -> ENABLE_TENSORFLOW

Using this option will result in a CS0246 error.

**Comment by hsaikia** [comment] 2018-05-08 05:38
@xiaomaogy I don't quite understand what you mean by Brain Script. I already posted my agent script. If you wanna know how I assign brains to the instantiated agents, it is done [here](https://github.com/hsaikia/UnityMLAgents/blob/master/SocialWalkerImitation/SWCrowd.cs)

I thought LSTM was turned on only from trainer_config.yaml and has nothing to do with the C# code. In any case, I'll try to turn off LSTM and see if it works.

**Comment by hsaikia** [comment] 2018-05-08 05:48
Although without LSTM, my agents would be pretty much useless.

**Comment by the1icon** [comment] 2018-05-12 10:29
Hello
If you are starting a new project you must import the TFSharpPlugin again.

**Comment by hsaikia** [comment] 2018-05-17 08:05
Well the TFSharpPlugin is imported. My problem still persists. I feel it has something to do with me using LSTM and imitation learning at the same time.

**Comment by vincentpierre** [comment] 2018-05-17 20:07
@hsaikia I made a fix for the issue you raised in #766 Can you tell me if it solves the problem you are having ?

**Comment by hsaikia** [comment] 2018-05-22 08:13
Hi @vincentpierre, sorry for not replying earlier. Is the fix merged with the master branch yet? I was working on other projects and haven't had a time to look. I'll try it out soon enough.

**Comment by vincentpierre** [comment] 2018-05-22 17:13
@hsaikia It is on `develop`

**Comment by xiaomaogy** [comment] 2018-06-27 23:22
Since Unity 2018.x already supports 4.7, I feels it is not necessary to make a .NET 4.6 TensorflowSharp version. Correct me if I am wrong, if I don't see any objection in a few days I will close this issue. @likeygame @rgjones33 @storedenen @ituni

**Comment by xiaomaogy** [comment] 2018-09-06 20:08
I am closing this thread due to inactivity, but feel free to re-open it if you desire.

**Closed by xiaomaogy** 2018-09-06 20:08 UTC
Labels: bug
