### ISSUE TITLE
Fatal Error: Could not allocate memory

### ISSUE THREAD

**Issue by devedse** [Unity-Technologies/ml-agents#3024] opened 2019-12-04 09:28 UTC
**Describe the bug**
Hi all, I've created a quite simple racing game where an agent learns to drive on a track:

![image](https://user-images.githubusercontent.com/2350015/70129673-7eaac580-167f-11ea-83cf-f164932dc019.png)

![image](https://user-images.githubusercontent.com/2350015/70129815-b9146280-167f-11ea-84d9-36d1513f242b.png)

The agent has the following Agent code:

```
public class RaceGameAgent : Agent
{
    public RoadDetectorScript RoadDetector;
    public ArcadeCar ArcadeCar;
    public RaceTrackScript RaceTrackScript;

    public Vector3 startPos;

    public int FrameCountSinceReset = 0;

    public void Start()
    {
        startPos = ArcadeCar.transform.position;
    }

    public override void AgentAction(float[] vectorAction, string textAction, CustomActionProto customAction)
    {
        ArcadeCar.AIXAxisInput = vectorAction[0];
        ArcadeCar.AIYAxisInput = vectorAction[1];
        ArcadeCar.AIHandBrakeInput = vectorAction[2] > 0.5f;


        //For some reason it resets twice, I think it's due to Resetting not creating gameobjects in the same fixedupdate
        if (FrameCountSinceReset > 1)
        {
            if (RoadDetector.CountWheelsOnRoad == 0)
            {
                Done();
                SetReward(-1f);
            }
            else
            {
                if (RoadDetector.CountWheelsOffRoad == 0)
                {
                    SetReward((ArcadeCar.GetSpeed() * 3.6f - 10.0f) / 200.0f);
                }
                else
                {
                    SetReward(RoadDetector.CountWheelsOffRoad * -0.1f);
                }
            }

            if (GetCumulativeReward() < -100f)
            {
                Done();
            }
        }

        FrameCountSinceReset++;
    }

    public override void AgentAction(float[] vectorAction, string textAction)
    {

    }

    public override void CollectObservations()
    {
        this.AddVectorObs(gameObject.transform.rotation);
        this.AddVectorObs(ArcadeCar.transform.GetComponent<Rigidbody>().velocity);
        this.AddVectorObs(ArcadeCar.GetSpeed());

        var tracers = gameObject.GetComponentsInChildren<TracerScript>();
        foreach (var tracer in tracers)
        {
            this.AddVectorObs(tracer.CastRay());
        }

        this.AddVectorObs(RoadDetector.WheelLFIsRoad);
        this.AddVectorObs(RoadDetector.WheelRFIsRoad);
        this.AddVectorObs(RoadDetector.WheelLBIsRoad);
        this.AddVectorObs(RoadDetector.WheelRBIsRoad);

        this.AddVectorObs(RoadDetector.CountWheelsOnRoad);
        this.AddVectorObs(RoadDetector.CountWheelsOffRoad);

        base.CollectObservations();
    }

    public override void AgentReset()
    {
        ArcadeCar.Reset(startPos, 180);
        RaceTrackScript.Reset();
        FrameCountSinceReset = 0;
    }
}
```

During the training process you can see the memory usage of Unity.exe slowly increasing, after about a night of training I checked and saw that the memory usage capped out on 32gb.

After about 10 minutes it dropped again to 16gb (I would assume due to the garbage collector running.

After about 2 days of training I ran into the following issue:

![image](https://user-images.githubusercontent.com/2350015/70130119-4657b700-1680-11ea-90b2-a1aab4e7f14d.png)

I'm not exactly sure where to start when solving this issue so hopefully someone here could give some advice. Could it be due to a memory leak in ml-agents or does no one else see this problem?

I did also replace the memory (previously I had 16gb and now I moved to new sticks for a total of 32gb) but that did also not solve the issue.

**To Reproduce**
`See above`

**Console logs / stack traces**
`Only logging I have is the screenshot above`

**Screenshots**
`See above`

**Environment (please complete the following information):**
- OS + version: Windows 10 (Fresh install)
- _ML-Agents version_: https://github.com/devedse/ml-agents (should be version 0.11)
- _TensorFlow version_: 1.7.1
- _Environment_: N/A for now due to difficulty in reproducing this issue, I'll see what I can do

**Comment by surfnerd** [comment] 2019-12-04 20:40
Hi @devedse,
Just a quick look at your screen shots, it seems like the allocation is happening in your code.  Are you sure that there isn't a memory leak in your `RaceTrackScript`?

Could you share your project with us?  Without an in depth view into your code, it will be hard to know what's going on.  You can always install the [Unity Memory profiler](https://docs.unity3d.com/Packages/com.unity.memoryprofiler@0.1/manual/index.html) from the package manager to see what type of objects are leaking.

**Comment by devedse** [comment] 2019-12-04 23:26
I'll do some investigation with the memory profiler tomorrow first. Would it be possible to share a private repository?

**Comment by surfnerd** [comment] 2019-12-04 23:52
You could add me as a collaborator and remove me whenever you feel.

**Comment by devedse** [comment] 2019-12-05 10:00
I've been running the memory profiler.

Screenshot of memory usage just after start:
![image](https://user-images.githubusercontent.com/2350015/70224318-5e493c80-174d-11ea-80a5-5c8b153574ba.png)

Screenshot of memory usage afte 5 minutes of running:
![image](https://user-images.githubusercontent.com/2350015/70224342-66a17780-174d-11ea-8359-6205ec27dca3.png)

And the diff:
![image](https://user-images.githubusercontent.com/2350015/70224459-98b2d980-174d-11ea-88dc-d0eb7f4fd8bd.png)

I've also created a private repository which I will add you to. To actually start training I'm currently using the TrainRace.cmd script from our fork of ml-agents:
https://github.com/devedse/ml-agents/blob/master/TrainRace.cmd

You'll receive an invite for the other private repository shortly :smile:

**Comment by devedse** [comment] 2019-12-05 10:44
When digging through the Memory Profile I see a lot of arrays with empty values, e.g.:
![image](https://user-images.githubusercontent.com/2350015/70228391-9607b280-1754-11ea-84f0-1306213c7acb.png)

The same happens with arrays for UINT64 and String. Loads of 0 values or null values.

**Comment by surfnerd** [comment] 2019-12-05 17:19
I got the invite.  I'll see if I can take some time today to run a profiling trace myself.  We haven't seen any memory leaks with our nightly training sessions. But maybe you are hitting a case that we haven't covered.  Thanks for your cooperation and help debugging this.

**Comment by surfnerd** [comment] 2019-12-05 17:20
Are you by chance using visual observations?

**Comment by devedse** [comment] 2019-12-05 17:34
Hey, that's great thanks. It could very well be some misunderstanding for me about how specific things in Unity work but let's see.

I don't use visual observations yet. The inputs of the ml agent are a bunch of Ray traces that input booleans wether they hit the road or hit the grass.

**Comment by surfnerd** [comment] 2019-12-05 17:40
Hey @devedse,
I was able to reproduce the leak without training.  I'm just running the RaceGameScene and seeing large buffers of `UINT64` and `System.Byte[]`.  I'm still not sure if it's coming from ML-Agents or not.  I will dig a bit further.

**Comment by surfnerd** [comment] 2019-12-05 17:52
I do, however, see your material memory growing significantly.  It grew from around 20MB from about 1 minute after the start to about 70MB 10 minutes later.  

Here is a screen shot of a small portion of the Material memory.  
![Screen Shot 2019-12-05 at 9 51 14 AM](https://user-images.githubusercontent.com/1356616/70260317-deb76f80-1744-11ea-81bc-408d3d0b7868.png)


Please see make sure you are correctly disposing of materials that are no longer being used, or ensure to mark them as shared if you are going to reuse them.  I would guess that this could be a leak from the random generation of your track, but I'm not sure.  

I hope this helps.

**Comment by surfnerd** [comment] 2019-12-05 18:01
Related forum thread about disposing of materials
https://forum.unity.com/threads/unityengine-material-object-memory-leak.48623/

**Comment by surfnerd** [comment] 2019-12-05 18:01
Since the materials have the (Instance) tag, it tells me you need to dispose of them manually.  This should solve your memory leak.

**Comment by devedse** [comment] 2019-12-06 10:14
@surfnerd , thanks for this, I'm sorry for the confusion around this.

An additional question though, I could opt for actually setting the meshRenderer.sharedMaterial instead of the meshRenderer.material, but I'm not sure if this will solve the issue as well? (The only thing I could find on google was that sharedMaterial returns the actual reference whereas .material returns a copy for this specific object. But it doesn't state anything about setting it).

So for now I'll implement this patch:
Old
```
for (int i = transfo

```

New
```

```


Another question I have is, do I also need to do something similar for the MiniMap? I'm using the following code to update the images there:
```
var img = ga.GetComponent<Image>();
img.sprite = foundPiece.Sprite;
```

**Comment by devedse** [comment] 2019-12-06 14:17
I'm currently retraining the application and it seems to have not really been resolved as the memory usage of Unity is now at around 7gb.

Could it be that simply setting .sharedMaterial isn't good enough?

If that's the case, is there another solution or should I Dispose the materials themselves somehow? (Should this be done by doing something like `Destroy(ga.GetComponent<MeshRenderer>().material)`

**Comment by surfnerd** [comment] 2019-12-06 15:40
Yes, using the sharedMaterial property may or may not be appropriate for what you are doing.  You will need to destroy any material clones that you’ve created using the `Destroy` function as you stated.

**Comment by devedse** [comment] 2019-12-17 09:45
@surfnerd , Hi, had a bit of a busy period so sorry for the delay in updates. Yesterday I made a [fix to the code](https://github.com/devedse/DS-MLUnityPrivate/commit/e83afb2a870f4b7762ba588c58fdad86a3880ba4) to now destroy materials on recreation of the map. I'm not sure if this has fixed the issue though because after one night of training I'm using about 8gb of memory again:

![image](https://user-images.githubusercontent.com/2350015/70984072-1cf44d80-20ba-11ea-9638-8cc15418bda6.png)

Whether this has fixed the issue is to be seen. I'll keep the training running for a few days and will inform you on the progress.

**Comment by surfnerd** [comment] 2019-12-18 19:20
Thanks for the update.  Can you also take a memory snapshot with the Memory profiler?  I'd like to see what is taking up so much memory.

**Comment by devedse** [comment] 2019-12-19 10:05
@surfnerd , I just took a screenshot when Unity was using ~20gb of memory. When I then opened this snapshot the Unity memory usage spiked to ~27gb so that's why in the screenshot below the memory usage is higher.

Anyway, the snapshot:
![image](https://user-images.githubusercontent.com/2350015/71164469-6de97a80-224f-11ea-8195-d575063bf813.png)

And Task Manager:
![image](https://user-images.githubusercontent.com/2350015/71164485-780b7900-224f-11ea-993a-7f389e1d1366.png)

**Comment by surfnerd** [comment] 2019-12-19 18:49
Hmm, this is pretty weird.  The amount of total memory in the snapshot is definitely less than ~20GB.  It's more on the scale of around 200-300MB.  I'll take a look at the project again and see if I can find anything else.

**Comment by devedse** [comment] 2019-12-20 09:21
I did a bit of scrolling through the snapshot as well and think it might be a bit higher then 200-300MB due to there being quite a lot of instances for some specific 1MB objects. For example there's 935 instances of Texture2D.

However I also agree that this doesn't seem to add up to 20gb.

This morning however I checked again and saw the memory usage dropped to 14GB:
![image](https://user-images.githubusercontent.com/2350015/71244262-68a13400-2312-11ea-8d2f-0aec8a117988.png)

It could possibly just be an artifact of the Garbage collector not running that often, but I'm not really sure.

**Comment by devedse** [comment] 2019-12-20 09:25
Another thing I saw was that the time between snapshots also gradually increases.

At the fist few snapshots I see there's a difference of about 50 seconds per 1000 steps.

At the end this duration has increased to about 220 seconds:

```
INFO:mlagents.trainers: race_7: RaceGameLearningBrain: Step: 1000. Time Elapsed: 52.796 s Mean Reward: -38.610. Std of Reward: 17.850. Training.
INFO:mlagents.trainers: race_7: RaceGameLearningBrain: Step: 2000. Time Elapsed: 102.428 s Mean Reward: -34.189. Std of Reward: 20.628. Training.
INFO:mlagents.trainers: race_7: RaceGameLearningBrain: Step: 3000. Time Elapsed: 152.381 s Mean Reward: -23.578. Std of Reward: 20.009. Training.
INFO:mlagents.trainers: race_7: RaceGameLearningBrain: Step: 4000. Time Elapsed: 206.723 s Mean Reward: -15.534. Std of Reward: 16.491. Training.
INFO:mlagents.trainers: race_7: RaceGameLearningBrain: Step: 5000. Time Elapsed: 257.479 s Mean Reward: -7.267. Std of Reward: 10.994. Training.

...
...
...

INFO:mlagents.trainers: race_7: RaceGameLearningBrain: Step: 2319000. Time Elapsed: 317379.718 s Mean Reward: 1467.813. Std of Reward: 1560.897. Training.
INFO:mlagents.trainers: race_7: RaceGameLearningBrain: Step: 2320000. Time Elapsed: 317599.201 s Mean Reward: 601.707. Std of Reward: 293.869. Training.
INFO:mlagents.trainers: race_7: RaceGameLearningBrain: Step: 2321000. Time Elapsed: 317824.258 s Mean Reward: 1292.860. Std of Reward: 1052.086. Training.
INFO:mlagents.trainers: race_7: RaceGameLearningBrain: Step: 2322000. Time Elapsed: 318044.004 s Mean Reward: 1013.822. Std of Reward: 1115.018. Training.
INFO:mlagents.trainers: race_7: RaceGameLearningBrain: Step: 2323000. Time Elapsed: 318266.715 s Mean Reward: 1757.583. Std of Reward: 2141.269. Training.
```

**Comment by surfnerd** [comment] 2019-12-20 18:19
Do you happen to have the snapshot files you can send to me?

**Comment by surfnerd** [comment] 2019-12-20 18:24
One _guess_ on why the training would be slowing down is if your memory is getting really fragmented with the creation and deletion of materials/textures/etc.  It may also explain the heap size of the unity process.  I'll see if I can find anything with some of my own spelunking.

**Comment by devedse** [comment] 2019-12-20 19:52
Aw shit can only do that next Monday. I'll post it then :).

**Comment by devedse** [comment] 2019-12-23 11:48
Here's the last snapshot from Friday:
https://drive.google.com/open?id=12PKfydD9lMUX3mtwgmEMSu0_uhusF7DR

And a new one from today:
https://drive.google.com/file/d/1bHMs-2HassYa0EoeoGe3u_iYctBwt530/view?usp=sharing

Strange thing is though that the one from Friday was about 3gb while the one from today is 10gb.

**Comment by devedse** [comment] 2020-01-02 09:15
This morning the run finally completed 😃. Unity still used a ton of memory though. The interesting part is, that even after the run completed and Unity was idling in the Editor it would still consume about 26gb's of memory.

What I then tried was pressing the play button to see how the newly trained model would perform, when I did this Unity went in a "Not responding" state and still used about 22 gb of memory:

![image](https://user-images.githubusercontent.com/2350015/71659640-9a6dbe00-2d48-11ea-8d21-722ede1f61ea.png)

After restarting Unity everything worked again and the newly trained model performs great 😄

**Comment by devedse** [comment] 2020-01-16 09:21
@surfnerd , do you have any updates or ideas or shall we leave this issue as stale?

**Comment by surfnerd** [comment] 2020-01-16 17:50
Hey @devedse,
I apologize for not getting back to you.  It has been quite busy lately.  I'd like to investigate further but may not get to it for a while. I'll add the bug label and file this in our internal tracker.  I'd like to get to the bottom of it.

**Comment by surfnerd** [comment] 2020-01-16 17:52
Hi @devedse,
I've filed this under MLA-535 in our internal tracker.  We will prioritize this and update this issue when we have an update.

**Comment by surfnerd** [comment] 2020-03-10 19:46
friendly ping @devedse,
I was wondering if you were still having this issue.  From the debugging I did, I was unable to find a leak in our code.  Where you able to find any more in yours?

**Comment by surfnerd** [comment] 2020-04-02 21:03
Hi @devedse,
We have not been able to find any memory leaks on our end after a few months of testing.  I am going to close this now.  I hope you have resolved your issue.
Cheers.

**Closed by surfnerd** 2020-04-02 21:03 UTC
Labels: bug, discussion

**Comment by devedse** [comment] 2020-04-10 09:16
@surfnerd , sorry for my late response but haven't been working with Unity for a while. For now the issues seems to have been resolved by doing the following:

![image](https://user-images.githubusercontent.com/2350015/78979673-a07bf380-7b1c-11ea-9115-131be76cddef.png)

Once I'll get back to working with Unity I'll run the training algorithm again and see if it remains working. Thanks for the quick responses and help you offered!
