### ISSUE TITLE
"Assertion failed on expression: 'task.rasterData.vertexBuffer == NULL'"

### ISSUE THREAD

**Issue by JPhilipp** [Unity-Technologies/ml-agents#3348] opened 2020-02-04 11:53 UTC
During training, I repeatedly get the following error message (say, half a dozen to a dozen times during a 100k steps run):

> Assertion failed on expression: 'task.rasterData.vertexBuffer == NULL'
> UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

It does not specify any code file or line, nor does it seem to harm training. I'm not sure if this has anything to do with ML Agents, it might just be a (Unity Editor?) bug exposed during the training (if so, please feel free to close this issue). My project is an open world with steerables, rigidbodies, ocean, boats, particles, sounds etc., so I can't easily guess what this may be in relation to, either. I do not remember having seen this error outside of training, though, like when walking the world.

**Comment by JPhilipp** [comment] 2020-02-05 20:32
Thanks. I'm using the very latest stable version -- Unity 2019.3.0f6. (On Windows 10. Currently switched to PC as build platform. It's a rather big project with lots of assets from the Asset Store.)

**Comment by surfnerd** [comment] 2020-02-05 22:02
Could you report a bug [here](https://unity3d.com/unity/qa/bug-reporting) and link to the issue [here](https://issuetracker.unity3d.com/issues/vr-particle-systems-cause-task-dot-rasterdata-dot-indexbuffer-equals-equals-null-error-and-lead-to-graphical-glitches).

It seems like a regression unrelated to ML-Agents.

**Comment by surfnerd** [comment] 2020-02-05 22:03
I will close this issue for now since this isn't an ML-Agents bug.  Thanks for your feedback.

**Closed by surfnerd** 2020-02-05 22:03 UTC
Labels: bug

**Comment by Fzcpp** [comment] 2020-03-28 09:13
https://issuetracker.unity3d.com/issues/task-dot-rasterdata-dot-vertexbuffer-equals-equals-null-errors-when-using-a-particle-system?_ga=2.13234228.269379034.1585150652-1092474247.1569082073

**Comment by Fzcpp** [comment] 2020-03-28 09:14
please vote for it, it should help bring it on the top of the pile
