### ISSUE TITLE
GPU inference bug

### ISSUE THREAD

**Issue by caioc2** [Unity-Technologies/ml-agents#2784] opened 2019-10-23 19:35 UTC
**Describe the bug**
Inference with GPU start outputing all 1s for it `act[]` vector after a few seconds. With CPU it works as intended.

**Steps to reproduce the behavior:**
1. Download the test environment [here](https://drive.google.com/open?id=1JWYgzIhE6UxNkFGPag8B69UBdt4funf9)
2. Open the Scene/Env
3. Set the Brain/Brain to CPU/GPU
4. See the Debug.Log(act[]) in the console

**Console logs / stack traces**
There is no error or stack trace

**Environment :**
- OS + version: Windows 10
- GPU: GTX 1060 & GTX 1080, lastest drives.
- _ML-Agents version_: ML-Agents v0.10.1
- _TensorFlow version_: 1.14.0
- _Environment_: custom minimal env [here](https://drive.google.com/open?id=1JWYgzIhE6UxNkFGPag8B69UBdt4funf9)

**Additional notes**
The model used is a `nature_cnn` with two LSTM layers with 512 units each and it outputs 4 continuous values.
I have tested in 3 different machines and had the same problem

**Comment by niskander** [comment] 2019-10-24 15:02
It is a bug. Workaround discussed there: https://github.com/Unity-Technologies/ml-agents/issues/2769

**Comment by caioc2** [comment] 2019-10-25 03:06
@niskander 

I'm not sure if they are related. Here I use only a single visual observation and continuous action space  without any mask. It only happens when using inference with an already trained model inside Unity with GPU inference select (using CPU inference works fine).
If it is really related could you elaborate how and which work around I could use?

**Comment by jacobson** [comment] 2019-10-27 09:37
(I am commenting on this because I opened the mentioned #2769 bug. That bug happens even if you use CPU. I do not think that these 2 issues are related. I changed EPSILON to a lower value and it worked **only** up to a certain degree. It still **must** be fixed. My change was inside models.py but it was for discrete vector space type. This issue may be related to nvidia graphics card or cuda versions, etc.. I am not sure, I did not follow the steps to reproduce this (#2784) issue.)

**Comment by surfnerd** [comment] 2019-10-31 17:20
friendly ping @mantasp

**Comment by mantasp** [comment] 2019-11-06 14:51
This issue is on our backlog, but at the moment I can't tell for sure when fix will be available.

**Comment by mantasp** [comment] 2019-11-14 13:49
We have found what is causing this issue and expect it to be fixed with ML-Agents upgrade to Barracuda 0.3.x, which we expect to happen soon.

**Comment by caioc2** [comment] 2019-11-14 14:16
I'm glad to hear that, Thanks!

**Comment by mantasp** [comment] 2019-11-22 16:21
@caioc2 could you please try our work in progress branch: https://github.com/Unity-Technologies/ml-agents/tree/develop-barracuda-0.3.x ?

**Comment by caioc2** [comment] 2019-11-22 16:50
@mantasp  It seems to be working properly Thanks!

I'll test it more deeply later, but so far so good.

**Comment by chriselion** [comment] 2019-11-22 18:03
@caioc2 Great! The changes are on develop now, and will be in the next release (hopefully around Dec 2nd).

**Closed** 2019-11-27 16:31 UTC
Labels: barracuda, bug
