### ISSUE TITLE
AttributeError: module 'signal' has no attribute 'SIGALRM'

### ISSUE THREAD

**Issue by echeg** [Unity-Technologies/ml-agents#7] opened 2017-09-20 10:52 UTC
On Windows, signal() can only be called with SIGABRT, SIGFPE, SIGILL, SIGINT, SIGSEGV, or SIGTERM. A ValueError will be raised in any other case.

```
C:\Repos\UnityRF\ml-agents\python\unityagents\environment.py in __init__(self, file_name, worker_id, base_port)
     86                     str(file_name)))
     87 
---> 88         old_handler = signal.signal(signal.SIGALRM, timeout_handler)
     89         signal.alarm(30)  # trigger alarm in x seconds
     90         try:

AttributeError: module 'signal' has no attribute 'SIGALRM'
```

**Comment by ASPePeX** [comment] 2017-09-20 12:12
This is a duplicate of #5.

A easy workaround is removing the lines 10, 88, 89, 99 and 100 from /python/unityagents/environment.py. That's not a nice solution but at least it is working this way.

**Comment by awjuliani** [comment] 2017-09-21 01:07
Thanks for pointing this out. We just pushed a fix to check for socket timeout in a way that is more cross-os compatible: https://github.com/Unity-Technologies/ml-agents/pull/9. Please let me know if things work for you now.

**Closed** 2017-09-21 01:10 UTC

**Comment by zhangdm** [comment] 2018-03-11 07:24
how to solve it ?
