### ISSUE TITLE
Vector observation size limit

### ISSUE THREAD

**Issue by nikola-j** [Unity-Technologies/ml-agents#2153] opened 2019-06-20 14:54 UTC
Hi guys, I'm trying to use multiple agents in a single env, where each agent is using a vector of size 65536. 

I'm using the Python API and when I try to restart the env with 15 agents it works, but when I try the same thing with 16 agents it hangs indefinitely.

Do you maybe know the reason why this would happen? Is there a limit with obs size in the Python API?

**Comment by nikola-j** [comment] 2019-06-24 13:43
Here is a way to reproduce the behavior:
 - Open Ball3D example scene
 - Remove NN model from 3DBallLearningBrain
 - Set observation size to 88000
 - Change Ball3DAgent.cs as follows:
```C#
    private List<float> a;

    public override void InitializeAgent()
    {
        ballRb = ball.GetComponent<Rigidbody>();
        a = new List<float>(88000 - 8);
        for (var i = 0; i < a.Capacity; i++)
        {
            a.Add(0f);
        }
    }

    public override void CollectObservations()
    {
        AddVectorObs(gameObject.transform.rotation.z);
        AddVectorObs(gameObject.transform.rotation.x);
        AddVectorObs(ball.transform.position - gameObject.transform.position);
        AddVectorObs(ballRb.velocity);
        AddVectorObs(a);
    }
```
 - Set control flat for brain in Ball3DAcademy
 - Build it as a server build and save it somewhere
 - Run the env from python using this script:
```python
import random
import time
from mlagents.envs import UnityEnvironment

unity_env = UnityEnvironment("3dball.x86_64")

unity_env.reset()

t1 = time.time()

for i in range(1000):
    if i%100==0:
        print(i,"/",1000)
    unity_env.step([random.uniform(-1,1)]*24)

print(time.time()-t1)
unity_env.close()
```
 - The script will stop on reset() and run indefinitely

Another weird thing to note is that changing the observation size will dramatically impact how fast we can iterate through the environment.

These are the results I got:
 - Observation size **8: 5** seconds to run for 1000 steps
 - Observation size **2000: 11** seconds to run for 1000 steps
 - Observation size **10000: 46** seconds to run for 1000 steps
 - Observation size **87000: 400** seconds to run for 1000 steps

**Comment by xiaomaogy** [comment] 2019-06-24 23:30
Hi @nikola-j, thanks for reporting this bug. I was also able to reproduce the bug on my mac using a mac build. 

Also when the observation size is larger, the simulation time increase is expected, because we need to serialize and send this data from C# side to python side and then back. Larger array will take larger amount of time to serialize and deserialize.

**Comment by nikola-j** [comment] 2019-06-25 11:02
Hi @xiaomaogy, no problem.
Do you think there is room to improve the communication speed between C# and python?

**Comment by xiaomaogy** [comment] 2019-06-25 18:45
@nikola-j There definitely is. We are working on this.

**Comment by harperj** [comment] 2019-07-30 22:17
Hi all -- this issue has been inactive for some time so I'm going to close it.  Feel free to reopen or create a new issue if you have more to discuss.

**Comment by nikola-j** [comment] 2019-07-31 19:44
Hi @harperj, I know it has been inactive, but shouldn't it be closed once the bug is fixed? Or do you guys use something internal to track issues?

**Comment by harperj** [comment] 2019-08-01 21:44
Hi @nikola-j -- thanks for the comment.  It was a mistake on my part to close this issue, we will keep it open until the bug is fixed and I'll also make sure it's captured on our internal bug tracker.

**Comment by surfnerd** [comment] 2019-10-02 17:56
Hi @nikola-j, 
Thanks for reporting this issue.  We have logged the bug internally as MLA-84 and will update this issue once we have more information.

**Comment by chriselion** [comment] 2019-10-10 16:40
HI @nikola-j 
A small update on this. While doing some profiling yesterday, I noticed this this block was especially slow for large observations:
https://github.com/Unity-Technologies/ml-agents/blob/8f2aff493c81c0287b2815ebec577869e4dab98b/ml-agents-envs/mlagents/envs/brain.py#L232-L235

Some alternate approaches are discussed here: https://stackoverflow.com/questions/6736590/fast-check-for-nan-in-numpy . I'm probably going to switch to the `dot` approach soon. I'm reluctant to drop the check entirely, but maybe we can add an option to disable it...

**Comment by chriselion** [comment] 2019-10-24 00:01
@nikola-j Hard to say that this is "fixed", but we sped up one part of the code that slowed down a lot with large numbers of vector observations: https://github.com/Unity-Technologies/ml-agents/pull/2717

**Comment by nikola-j** [comment] 2019-10-24 09:14
Hi @chriselion, thanks, that's great! Maybe you could run the check every 100 steps or something similar? How much of an improvement do you get if you disable it entirely?

**Comment by xiaomaogy** [comment] 2020-03-11 02:07
This issue has been fixed in the latest version, so I'm going to close it for now. If you find this continues to be an issue, feel free to reopen it.

**Closed by xiaomaogy** 2020-03-11 02:07 UTC
Labels: bug
