### ISSUE TITLE
UnityActionException: behavior 3DBall?team=1 needs a continuous input of dimension (0, 2)

### ISSUE THREAD

**Issue by nagybalint25** [Unity-Technologies/ml-agents#5204] opened 2021-03-31 14:46 UTC
Running a version of 3DBall, where I've deleted all agents except for one. Whenever I issue an action  using Gym (with the wrapper), for example taking a random action using 

`env.action_space.sample()`

I get an error:

``` The behavior 3DBall?team=1 needs a continuous input of dimension (0, 2) for (<number of agents>, <action size>) but received input of dimension (1, 2) ``` 

There clearly is an agent in my executable, and ``` mlagents-learn```  works fine too.

My code is as follows:
```import gym

from mlagents_envs.environment import UnityEnvironment
from gym_unity.envs import UnityToGymWrapper
gym.logger.set_level(40)

def main():
    unity_env = UnityEnvironment(file_name="3dballv2")
    env = UnityToGymWrapper(unity_env,  uint8_visual=True,allow_multiple_obs=True)
    env.reset()
    for _ in range(1000):
        env.render()
        env.step(env.action_space.sample()) #random action
    env.close()    
    


if __name__ == '__main__':
    main()
``` 

Environment:
- Unity Version: Unity 2020.1f1
- OS + version: Windows 10
- _ML-Agents version_: Release 15
- _Torch version_: 1.7.1
- _Environment_: 3DBalls

**Comment by vincentpierre** [comment] 2021-03-31 18:15
Hi @nagybalint25 
I was able to reproduce the issue. The problem is that your agent is done, do the environment must reset : 
The following code should do the trick : 

```
from mlagents_envs.environment import UnityEnvironment
from gym_unity.envs import UnityToGymWrapper
gym.logger.set_level(40)

def main():
    unity_env = UnityEnvironment(file_name="3dballv2")
    env = UnityToGymWrapper(unity_env,  uint8_visual=True,allow_multiple_obs=True)
    env.reset()
    for _ in range(1000):
        env.render()
        o,r,d,_ = env.step(env.action_space.sample()) #random action
        if d:
            env.reset()
    env.close()    
    


if __name__ == '__main__':
    main()
```

The error message is wrong and I will work to resolve this. Thank you for raising this issue.

**Comment by nagybalint25** [comment] 2021-03-31 18:22
Thank you very much for your kind and quick reply! Absolutely solved my
problem.

Vincent-Pierre BERGES ***@***.***> ezt írta (időpont: 2021.
márc. 31., Sze, 20:15):

**Comment by dongruoping** [comment] 2021-04-02 20:41
Thanks @vincentpierre !

Since the fix has been merged I'll close it.

**Closed by dongruoping** 2021-04-02 20:41 UTC
Labels: bug
