### ISSUE TITLE
gym_unity.envs.UnityEnv generates incorrect observation space when uint8_visual is True

### ISSUE THREAD

**Issue by dans-msft** [Unity-Technologies/ml-agents#2752] opened 2019-10-17 23:07 UTC
**Describe the bug**
When using wrapping a Unity ML Agents environment in a Gym environment, the gym_unity.envs.UnityEnv class will create an incorrect Box observation space for visual observations when uint8_visual is True.  Specifically, it creates a Box with a dtype of float32, low of 0, and high of 1 which is only appropriate when uint8_visual is False.  It should create a Box with a dtype of uint8, low of 0, and high of 256.

**To Reproduce**
Setup a Unity environment that has a visual observation.  I used the GridWorld sample.
Open up a Jupyter notebook and write the following code:

from gym_unity.envs import UnityEnv
env = UnityEnv(<path-to-env>, 1, True, True)

Now take a look at env.observation_space.low and env.observation_space.high and you'll see the incorrect values.

Furthermore, if you run
env.observation_space.contains(env.step(1)[0])

You will get 'False', indicating that the returned observation is out-of-range for its declared observation space.  This will cause a failure if you try to use this environment with Ray/RLLib (for example).

**Environment (please complete the following information):**
- OS + version:  Ubuntu 18.04.3 LTS
- _ML-Agents version_: mlagents version 0.10.1  gym_unity version 0.4.8
- _Environment_: GridWorld

**NOTE:** We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

**Comment by chriselion** [comment] 2019-10-23 03:43
Hi @dans-msft ,
Sorry for the delay on this.

I confirmed today that the results for `env.observation_space.low` and `high` where what you described.

It looks like we currently only use uint8_visual for scaling the observations here:
https://github.com/Unity-Technologies/ml-agents/blob/36433174a9cf20559be5a44eb60d2c8eaf071429/gym-unity/gym_unity/envs/__init__.py#L242-L268

but we should probably be using it when setting up the observation_space here too https://github.com/Unity-Technologies/ml-agents/blob/36433174a9cf20559be5a44eb60d2c8eaf071429/gym-unity/gym_unity/envs/__init__.py#L139-L147

I'll follow up tomorrow with some folks that are more familiar with this part of the code than I am...

**Comment by chriselion** [comment] 2019-11-06 00:40
Hi @dans-msft,
This was fixed in https://github.com/Unity-Technologies/ml-agents/pull/2783, and the latest version of gym_unity (0.11.0) contains the fix.

**Closed by chriselion** 2019-11-06 00:40 UTC
Labels: bug
