### ISSUE TITLE
DQN trainer plugin: dqn optimizer fix saving to onnx

### ISSUE THREAD

**Issue by Skevinci** [Unity-Technologies/ml-agents#5937] opened 2023-06-18 17:29 UTC
**Describe the bug**
In DQN optimizer, saving to onnx still remains a bug.

I see that in the optimizer file, there is a # TODO: fix saving to onnx. I'm wondering when this will be fixed. Thank you!

**Comment by miguelalonsojr** [comment] 2023-10-08 22:02
The DQN trainer is an example trainer for those that want to implement their own custom trainer. Unfortunately, there are no plans to add ONNX export to the DQN trainer example. Closing as this is not a bug.

**Closed by miguelalonsojr** 2023-10-08 22:02 UTC
Labels: bug

**Comment by adithia425** [comment] 2024-04-08 19:17
how to convert .pt to .onnx??
