### ISSUE TITLE
Brain parameter in agent can't be null in version 0.4.0a

### ISSUE THREAD

**Issue by phoenixSK** [Unity-Technologies/ml-agents#953] opened 2018-07-03 08:27 UTC
Hi! I've just updated to last version (0.4.0a) and now the brain parameter of an agent can't be null as it is said in documentation, since the code in the OnEnable message of Agent's MonoBehaviour use it for initialize the textureArray. As there is no check for avalability of brain, a NullReferenceException will be thrown. Is this a bug or it will be the behaviour from now on? Thanks!

**Comment by awjuliani** [comment] 2018-07-03 14:02
Hi @phoenixSK,

Thanks for brining this to our attention. It is definitely not the intended behavior, and a regression that I failed to catch, since all of our example environments assume the existence of a brain already attached to the agent. We will work to fix this, and release a hotfix in the near future.

**Comment by awjuliani** [comment] 2018-07-24 18:39
We have made a fix for this, and will be releasing it as part of v0.4.0b. https://github.com/Unity-Technologies/ml-agents/tree/hotfix-0.4b

**Closed by awjuliani** 2018-07-24 18:39 UTC
Labels: bug
