### ISSUE TITLE
cython dependency is missing from requirements.txt

### ISSUE THREAD

**Issue by avilay** [Unity-Technologies/ml-agents#939] opened 2018-06-29 07:27 UTC
When creating a new venv and trying to install all the requirements I get the following warnings:

mkl-random 1.0.1 requires cython, which is not installed.
mkl-fft 1.0.0 requires cython, which is not installed.

The installation does proceed to completion. This might be because cython is missing from the requirements.txt file.

**Comment by awjuliani** [comment] 2018-06-29 17:28
Hi @avilay,

Nice to see you here. I assume the issue is related to the `numpy` package installation, where `cython` is a possible backend which seems to not be required by `numpy`, but required by some of the packages it installs. Thanks for brining this up.

**Comment by ivenzor** [comment] 2018-06-30 04:41
I remember I got the same warning when installed the environment. 
Best regards.

**Comment by harperj** [comment] 2018-12-17 23:57
As far as we can tell the addition of a `cython` dependency isn't required for ml-agents to work correctly.  We've also eliminated `requirements.txt` in favor of `setup.py`.  If you run into any issues other than a warning please feel free to reopen, but I'm closing for now.

**Closed by harperj** 2018-12-17 23:57 UTC
Labels: bug
