### ISSUE TITLE
KEY ERROR 

### ISSUE THREAD

**Issue by sunrui19941128** [Unity-Technologies/ml-agents#2427] opened 2019-08-12 01:11 UTC
I got this error when I started Unity while imitating learning!!!!!!Help Me  Thanks!ML-Agents0.9.0

Traceback (most recent call last):
  File "D:\Anaconda3\envs\ml-agents-tutorial\Scripts\mlagents-learn-script.py", line 11, in <module>
    load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')()
  File "e:\githubproject\ml-agents\ml-agents\mlagents\trainers\learn.py", line 319, in main
    run_training(0, run_seed, options, Queue())
  File "e:\githubproject\ml-agents\ml-agents\mlagents\trainers\learn.py", line 118, in run_training
    tc.start_learning(env, trainer_config)
  File "e:\githubproject\ml-agents\ml-agents\mlagents\trainers\trainer_controller.py", line 297, in start_learning
    n_steps = self.advance(env_manager)
  File "e:\githubproject\ml-agents\ml-agents-envs\mlagents\envs\timers.py", line 210, in wrapped
    return func(*args, **kwargs)
  File "e:\githubproject\ml-agents\ml-agents\mlagents\trainers\trainer_controller.py", line 364, in advance
    new_step_infos = env.step()
  File "e:\githubproject\ml-agents\ml-agents-envs\mlagents\envs\subprocess_env_manager.py", line 166, in step
    self._queue_steps()
  File "e:\githubproject\ml-agents\ml-agents-envs\mlagents\envs\subprocess_env_manager.py", line 159, in _queue_steps
    env_action_info = self._take_step(env_worker.previous_step)
  File "e:\githubproject\ml-agents\ml-agents-envs\mlagents\envs\timers.py", line 210, in wrapped
    return func(*args, **kwargs)
  File "e:\githubproject\ml-agents\ml-agents-envs\mlagents\envs\subprocess_env_manager.py", line 253, in _take_step
    all_action_info[brain_name] = self.policies[brain_name].get_action(
KeyError: 'RollerBallPlayer'
![Key Error](https://user-images.githubusercontent.com/34094384/62842010-1f483480-bce1-11e9-8c0e-71f0627f677f.png)

**Comment by mnsmuts** [comment] 2019-08-12 15:41
did you find a solution? I am hitting the same problem (suspect it is something simple) same setup trains offline but will not train online

**Comment by ervteng** [comment] 2019-08-12 16:59
Hi @sunrui19941128, @mnsmuts, can you post your yaml config file?

**Comment by sunrui19941128** [comment] 2019-08-13 01:21
Ok  Immediately submitted I am copy  trainer_config.yaml  ,and modify config default.See the pictures for the details!
![config](https://user-images.githubusercontent.com/34094384/62908661-b8438200-bdab-11e9-932d-05d3d7b19e11.png)

**Comment by sunrui19941128** [comment] 2019-08-13 01:24
I didn't have this problem in version 0.8.1,But this problem was encountered in 0.9.0,Now I am using 0.8.1, so I can train the Demo normally.I tried a lot in 0.9.0 but nothing worked!Later it was reloaded with a 0.8.1 environment to train normally!

> Hi @sunrui19941128, @mnsmuts, can you post your yaml config file?

I didn't have this problem in version 0.8.1,But this problem was encountered in 0.9.0,Now I am using 0.8.1, so I can train the Demo normally.I tried a lot in 0.9.0 but nothing worked!Later it was reloaded with a 0.8.1 environment to train normally!

**Comment by sunrui19941128** [comment] 2019-08-13 01:25
> Hi @sunrui19941128, @mnsmuts, can you post your yaml config file?

![config](https://user-images.githubusercontent.com/34094384/62908763-40c22280-bdac-11e9-931c-793ea5de523d.png)

**Comment by yamashin0922** [comment] 2019-08-13 06:37
Can you check if RollerBallPlayer is exist in Broadcast Hub in the inspector window of your  Academy?
If it is TRUE, please try to remove RollerBallPlayer from the inspector window of the Academy.

**Comment by smshehryar** [comment] 2019-08-13 06:44
any issues with it?

**Comment by yamashin0922** [comment] 2019-08-13 06:50
I'm not sure if issue is around there.  However, I faced the same issue. And I found it as workaround.

**Comment by sunrui19941128** [comment] 2019-08-13 06:54
> 我不确定问题是否存在。但是，我遇到了同样的问题。我发现它是一种解决方法。
 ml-agents whitch version  are you using now?

**Comment by yamashin0922** [comment] 2019-08-13 06:59
I'm using 0.9.0.

**Comment by sunrui19941128** [comment] 2019-08-13 07:02
I tried it and it didn't work with 0.9.0!!  Then it worked normally in 0.8.1!!It's really frustrating

**Comment by yamashin0922** [comment] 2019-08-13 07:16
I understand your frustration.
Do you mean that "KeyError: 'RollerBall Player'" is still shown in the error message even if you remove it from the inspector window in 0.9.0?

**Comment by mnsmuts** [comment] 2019-08-13 09:27
Hi, I can train in v0.8.2 but get the key error in v0.9.X. I am currently trying to roll back my environments to get back to a working system. removing the player brain made no difference, yaml file 
![image](https://user-images.githubusercontent.com/22680369/62930751-ebd6da00-bdb4-11e9-80e9-ea75359750f4.png)

pretty much nothing in it except the default - unless that is not allowed?

**Comment by mnsmuts** [comment] 2019-08-13 09:33
In my case I get : 
![image](https://user-images.githubusercontent.com/22680369/62930978-66075e80-bdb5-11e9-8c33-7020c38752ac.png)

then if I remove the player brain:
![image](https://user-images.githubusercontent.com/22680369/62931165-c3031480-bdb5-11e9-96df-aa8925e760ee.png)

**Comment by mnsmuts** [comment] 2019-08-13 09:34
this is version v0.9.1 and I am removing the player brain from the academy.

**Comment by mnsmuts** [comment] 2019-08-13 09:52
Just in case it helps - here is the anaconda prompt when trying exactly the same training (imitation 3DBall) in v0.8.2
![image](https://user-images.githubusercontent.com/22680369/62932617-62290b80-bdb8-11e9-8682-38397baa789d.png)

Seems to work well, which is why it feels like v0.9.1 has a bug

**Comment by nmndwivedi** [comment] 2019-08-13 12:29
> Can you check if RollerBallPlayer exist in Broadcast Hub in the inspector window of your Academy?
> If it is TRUE, please try to remove RollerBallPlayer from the inspector window of the Academy.

This works for me, thank you

**Comment by yamashin0922** [comment] 2019-08-13 13:27
@sunrui19941128 Can you share the screen capture of your inspector window of the Academy?

**Comment by sunrui19941128** [comment] 2019-08-14 00:51
> @ sunrui19941128你可以分享学院督察窗口的截屏吗？

Ok,this 0.9.0version screenshort  with Acadamy !  Picture one is No delete PlayerBrain .  Picture Two is deleted PlayerBrain! I tried your idea!but There are key errors!I suspect a version problem!sam time 0.8.1 no Problem!



![nodelete](https://user-images.githubusercontent.com/34094384/62987037-9e1fa780-be70-11e9-85d8-16dbc24b0768.png)
![delete](https://user-images.githubusercontent.com/34094384/62987060-b42d6800-be70-11e9-8a95-9b8914cee955.png)

**Comment by yamashin0922** [comment] 2019-08-14 07:34
Thank you for sharing it. 
As you said, there seems to be bug around there since the behavior differs between the two versions

To train RollerBallBrain (not RollerBallPlayer), we have to drag the RollerBallBrain asset to the RollerAgent GameObject Brain field to the learning brain.
Can you check your Brain field of RollerAgent?

**Comment by mnsmuts** [comment] 2019-08-14 09:47
Hi Yes all correct, the agent has a learning brain, the academy has a learning brain with control when creating a build for offline training, or if I am online training,  both a learning brain with control and a player brain.

**Comment by ervteng** [comment] 2019-08-14 19:38
Hey @mnsmuts, @yamashin0922, I can confirm that there is a bug in v0.9.1 that is preventing PlayerBrains from being used. I've pushed a fix to the branch `hotfix-onlinebc` - try checking out that branch and see if it fixes your issue. 

If you want to edit yourself, add `if brain_name in self.policies:` at line 253 in `subprocess_env_manager.py`.

**Comment by AidinD** [comment] 2019-08-15 07:10
I had the same problem moving up to vs 0.9. However, it seems removing the player brain from the academy hub solves the issue and the agent is training when control is checked. And at the same time, you can still use the player brain any way when unchecking control from the learning brain.

**Comment by mnsmuts** [comment] 2019-08-15 13:21
> Hey @mnsmuts, @yamashin0922, I can confirm that there is a bug in v0.9.1 that is preventing PlayerBrains from being used. I've pushed a fix to the branch `hotfix-onlinebc` - try checking out that branch and see if it fixes your issue.
> 
> If you want to edit yourself, add `if brain_name in self.policies:` at line 253 in `subprocess_env_manager.py`. Thank you for bringing this up; it will be fixed in the next release.

Many thanks

**Comment by Numan4221** [comment] 2019-09-19 09:41
Hi I have more or less the same problem but with KeyError: 'default'.
Its my first time so im not sure the issue, im using mlagents 0.9.2
Traceback (most recent call last):
  File "d:\users\danin\anaconda3\envs\ml-agents\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\users\danin\anaconda3\envs\ml-agents\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Users\danin\Anaconda3\envs\ml-agents\Scripts\mlagents-learn.exe\__main__.py", line 9, in <module>
  File "d:\users\danin\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py", line 337, in main
    run_training(0, run_seed, options, Queue())
  File "d:\users\danin\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py", line 110, in run_training
    multi_gpu,
  File "d:\users\danin\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\trainer_util.py", line 45, in initialize_trainers
    trainer_parameters = trainer_config["default"].copy()
KeyError: 'default'

**Comment by AydenWasTaken** [comment] 2019-11-30 13:21
I am currently having an issue with this as well.
I am a complete n00b so forgive any stupidity. I am trying to teach chameleons to take on

**Comment by AydenWasTaken** [comment] 2019-11-30 13:27
Hey. I am having a similar issue but with the newer versions a lot has changed and could not figure it out. Here is the console output:
![image](https://user-images.githubusercontent.com/41434155/69901105-71d75a80-137d-11ea-9843-3c2a18cf084a.png)
Any help would be appreciated!
PS. I am a noob so please forgive any stupidity :)
Ayden

**Comment by chriselion** [comment] 2019-11-30 18:16
@Numan4221 You need to have a "default" section in your trainer config's yaml file. See https://github.com/Unity-Technologies/ml-agents/blob/master/config/trainer_config.yaml#L1 for an example

@AydenWasTaken Can you post the contents of the curriculum folder and file? I think it's expecting a "Chameleon Behavior.json" file there, but you're probably going to have an easier time if you remove the space from the behavior name.

**Comment by AydenWasTaken** [comment] 2019-11-30 18:25
![image](https://user-images.githubusercontent.com/41434155/69904374-3ef58c80-13a6-11ea-911e-0f230731413d.png)
![image](https://user-images.githubusercontent.com/41434155/69904383-4fa60280-13a6-11ea-85c8-bbaf4c7d0c03.png)

@chriselion This is the second ml agents project im trying and the first had "My behavior" and it was fine when the folder was called "penguin" and the file "PenguinLearning.json" so i don't see how the two are related. Could you clarify on what exactly this behavior name is used for?

**Comment by chriselion** [comment] 2019-11-30 19:02
Here's where we parse the curriculum directory: https://github.com/Unity-Technologies/ml-agents/blob/master/ml-agents/mlagents/trainers/meta_curriculum.py#L56
Basically the key for the dictionary is the filename.

The behavior name is used as the key to that dictionary here: https://github.com/Unity-Technologies/ml-agents/blob/master/ml-agents/mlagents/trainers/trainer_util.py#L107-L109

It sounds like the dictionary has key "ChameleonLearning" (no space) but it's trying to look up "Chameleon Learning" (with a space).

We definitely need to make the error handling better here. and maybe handle unknown behavior names.

**Comment by AydenWasTaken** [comment] 2019-12-01 10:45
@chriselion Changing the behavior name to match the filename worked wonders, thank you!
Have a very good day

**Closed** 2019-12-17 02:17 UTC
Labels: bug
