### ISSUE TITLE
protobuf dependency

### ISSUE THREAD

**Issue by AzizRourou** [Unity-Technologies/ml-agents#5915] opened 2023-05-08 16:14 UTC
Problem :

On MacOS (13.3.1), after cloning the repo and following the "Advanced Local Installation for Development", when executing "mlagents-learn" for the first time, an error occur. The Terminal console responds with a traceback followed by :
"TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates"

So I downgraded from protobuf 4.22.1 to protobuf 3.20.0.

- The requirement fix protobuf to minimum 3.6 but should also fix it to a max version of 3.20.

**Comment by miguelalonsojr** [comment] 2023-06-05 10:40
Duplicate of https://github.com/Unity-Technologies/ml-agents/issues/5916

**Closed by miguelalonsojr** 2023-06-05 10:40 UTC
