### ISSUE TITLE
Game window moving downwards on play

### ISSUE THREAD

**Issue by PiotrJZielinski** [Unity-Technologies/ml-agents#1732] opened 2019-02-20 13:39 UTC
I am having a problem with my Unity project using ml-agents. When adding Academy object (even without activating Academy script), each time I press play in the editor the whole part of the UI moves out of the place where it should be.
![image](https://user-images.githubusercontent.com/23311513/53095463-39b50880-351d-11e9-9836-a7df2b6f563e.png)

Removing the whole object (or deactivating it) solves the problem, o does changing window size, but that's not really convenient. Perhaps there is a solution for this problem?
I am using Unity on Linux, if that matters.

**Comment by vincentpierre** [comment] 2019-02-20 19:08
I cannot really see what is happening on the screenshot you sent. Maybe you could give us a video or a before/after comparison. The Linux editor is still experimental, so the issue could come from here. It could also come from the Monitor.cs script that is activated in the Academy. Could you try to remove in the Academy.cs script the calls to the Monitor class around line 400 ? Or maybe even remove the Monitor.cs script altogether ?

**Comment by PiotrJZielinski** [comment] 2019-02-20 19:22
Okay, that is what it looks like before I press the play button:
![image](https://user-images.githubusercontent.com/23311513/53117990-646a8580-354c-11e9-94f1-24365783f095.png)
Then, when I start the game the whole UI moves downwards:
![image](https://user-images.githubusercontent.com/23311513/53118247-f6728e00-354c-11e9-8060-73444438361a.png)
Interestingly, I have recently changed the resolution of images sent through Brain to Python API (previously I have been using 1280x720 and now it is 416x416). Now window looks like this:
![image](https://user-images.githubusercontent.com/23311513/53118191-da6eec80-354c-11e9-8d2e-5fcca7b1753a.png)
I hope it is visible now, if it is still unclear please comment, I will post a video.
That is for now FYI, I will try commenting those Monitor calls.

**Comment by vincentpierre** [comment] 2019-02-20 22:14
This looks to me like a bug in the Linux editor. It seems very strange to me that the visual observation size would have any impact at all. I would say, try using 2 cameras, one for rendering the game in the editor and another for the Agent's camera. Be sure to set each camera to different displays.

**Comment by PiotrJZielinski** [comment] 2019-02-20 22:40
It might be Linux editor bug, but it only occurs while using ml-agents. I've tried changing cameras as well. No matter which display I choose (with various cameras, or even without them) the UI keeps moving. The only thing that solves this problem ultimately is removing or disabling the object with Academy script.

Also, I did try setting another Academy object or switching the script (even though, I have literally nothing added in there), to no avail...

**Comment by vincentpierre** [comment] 2019-02-20 23:42
What if you turn off the visual observations ?

**Comment by PiotrJZielinski** [comment] 2019-02-21 10:28
Nothing. I tried disabling visual observations in the Brain, removing the brain from the Academy and removing camera from Agent. None works. Actually, I am working with both Academy and Agent scripts (not objects) disabled, and it still happens (provided that the GameObject with Academy script is not disabled (it is not unticked)).
![image](https://user-images.githubusercontent.com/23311513/53161719-d1246500-35ca-11e9-95c9-194852202809.png)
I found out that changing Width and Height of Inference Configuration is actually messing up with the UI. Any value higher than 0x0 borks the Game window (pretty much resizing it to the width x height size). After changing those values to 0x0 the UI is okay. However this is not the solution.

**Comment by vincentpierre** [comment] 2019-02-21 23:33
This is very interesting, the `Inference Configuration` is affecting the Editor Window on Linux but not on OSX or Windows.
Can you try commenting out [this](https://github.com/Unity-Technologies/ml-agents/blob/master/UnitySDK/Assets/ML-Agents/Scripts/Academy.cs#L397) line of code ?

**Comment by PiotrJZielinski** [comment] 2019-02-22 10:45
When I comment this line the UI does not break, regardless of width and height value.

**Comment by vincentpierre** [comment] 2019-02-22 17:44
Ok, this is probably the issue then. The resizing should only happen when not in editor mode. I think this is a more permanent solution : 

```csharp
        /// <summary>
        /// Helper method for initializing the environment based on the provided
        /// configuration.
        /// </summary>
        /// <param name="config">
        /// Environment configuration (specified in the Editor).
        /// </param>
        static void ConfigureEnvironmentHelper(EnvironmentConfiguration config)
        {
# if !UNITY_EDITOR
            Screen.SetResolution(config.width, config.height, false);
# endif
            QualitySettings.SetQualityLevel(config.qualityLevel, true);
            Time.timeScale = config.timeScale;
            Time.captureFramerate = 60;
            Application.targetFrameRate = config.targetFrameRate;
        }
```

This should fix the bug in the editor while allow expected behavior when running the executable.

**Comment by PiotrJZielinski** [comment] 2019-02-23 11:47
Thank you, this works perfect.
Do you think it is a Unity-for-Linux-related bug or the reason lies somewhere else?

**Comment by vincentpierre** [comment] 2019-04-03 22:16
This seems to be a Unix-Editor issue. I will close this issue for now.

**Closed by vincentpierre** 2019-04-03 22:16 UTC
