### ISSUE TITLE
Couldn't connect to trainer on port 5004 using API version 1.0.0f, will perform inference instead.

### ISSUE THREAD

**Issue by egedursun** [Unity-Technologies/ml-agents#4021] opened 2020-05-25 20:33 UTC
I have tried nearly everything but it is still not working..

<img width="571" alt="Screenshot 2020-05-25 at 23 28 30" src="https://user-images.githubusercontent.com/28991396/82841623-72415000-9edf-11ea-80bc-eb2a6d1be21c.png">

-Mac OSX : 10.15.4 (Catalina)
-OSX Firewall has been deactivated.
-Tried local installation as well as cloning and using pip.
-Tried conda environments as well as classic python venv's.
-Tried restarting the application and importing the packages multiple times after deactivating firewall and also after restarting terminal and communicator API.
-Tried release-2, release-1, v0.15.1, v0.15.0, v0.14.1, v0.14.0
-mlagents properly installed.
-tensorboard properly installed.

I have read all the documentation but it is still not working on my mac. I feel really sorry about it.

It would be nice if I could get some help.

<img width="579" alt="Screenshot 2020-05-25 at 23 32 42" src="https://user-images.githubusercontent.com/28991396/82841797-090e0c80-9ee0-11ea-9f95-a8fd5ab3d4eb.png">

Traceback of running communicator API before the above screen.

<img width="807" alt="Screenshot 2020-05-25 at 23 33 13" src="https://user-images.githubusercontent.com/28991396/82841809-1aefaf80-9ee0-11ea-9202-89558682a8e3.png">

The error shown in the editor.

Thanks.

**Comment by unityjeffrey** [comment] 2020-05-26 15:21
Hi @egedursun are you able to get training going?  is this message just popping up when you open the project?

**Comment by egedursun** [comment] 2020-05-26 16:23
Hi. It seems like I have been able to solve the problem, and even though the tutorial steps are very clear, I will share the exact steps I did here for the others to be able to try the same steps.

1. Created a folder in my development folder
2. I cloned the ml-agents-release_2 inside the development folder.
3. I have created my Unity project inside the development folder, next to the ml-agents-release_2 folder.
4. I opened the Unity project inside the editor and from Window->Package Manager, I checked the "Show Preview Packages" from the dropdown box named "Advanced".
5. I found the ML-AGENTS package and imported it.
6. I opened an example scene from the example projects from ml-agents-release_2 folder.
7. I have removed the default brain from the agents.
8. From the console, I have created a conda environment via " conda create -n [virtual-env-name] python=3.x.y "
8. Activated the environment with "conda activate [virtual-env-name]
9. Upgraded pip3 : " pip3 install --upgrade pip "
10. Upgraded setuptools : " pip3 install --upgrade setuptools "
11. Installed mlagents : " pip3 install mlagents "
12. Changed directory inside ml-agents-release_2 directory : " cd [current_directory_to_mlagents_parent] /ml-agents-release_2 "
12. Started training : " mlagents-learn config/trainer_config.yaml --run-id:wormsTestOne --train "
13. Pressed play button from the Unity Editor. 
14. Works without any problems!

When problems turn back:
- When I setup the /ml-agents and /ml-agents-envs locally, the problem still happens.
- When I use a python venv instead of conda environment, problem still persists.
- When I turn on Mac OSx firewall, problem still persists.

FYI.
Best,
Ege

**Comment by yiqisetian** [comment] 2020-06-09 12:43
I hava same problem with @egedursun ,and I almost try everything @egedursun  had tried .But the problem is still there.

**Comment by yiqisetian** [comment] 2020-06-10 05:55
> Hi @egedursun are you able to get training going? is this message just popping up when you open the project?

I hava the same problem. I can't get traing going. I think the problem is the connection between unity and mlagents. I found a similar problem,https://github.com/Unity-Technologies/ml-agents/issues/3667. But I have no idea how to set the base_port in the instatiation of the UnityEnvironment to 5004. 
It would be nice if I could get some help too.

**Comment by DataBeeGood** [comment] 2020-06-22 21:16
Hey just a little bump to let the wonderful BugFixers know that the Hummingbird Premium Learn course shows this error in the videos.  I ran the course using Anaconda env Python 3.7 ; Unity 2019.3 then 2019.4; the latest MLAgents from the Package Manager ... about 3 days ago..  This **5004 port issue persists** -- but does not stop the training - able to get a nice ppo Hummingbird.NN... Would really like to be able to control port listening for security purposes.... Thanks.

**Comment by GcodeHub** [comment] 2020-07-17 10:41
Hi, Im also getting the same issue in the last version of MlAgents, i not able to train, when I start trainning the 5004 port issue appears in console and seconds later the cmd in which I run the command gives a timeout error, I've several solutions and multiple projects but it seems to appear everytime I try to train

**Comment by ssshammi** [comment] 2020-12-31 08:38
HI I get the same error on Mac with release build 12 and unity version 2020.. I also get popup in unity when I press play " libgrpc_csharp_ext.x64.bundle” cannot be opened because the developer cannot be verified. with delete and cancel button. But still not able to connect to post 5004 and my firewall is disabled.

**Comment by ssshammi** [comment] 2020-12-31 08:53
`shammis-MacBook-Air:mlagents shammiseth$ mlagents-learn config/ppo/3DBall.yaml --run-id=first3DBallRun --force


                        ▄▄▄▓▓▓▓
                   ╓▓▓▓▓▓▓█▓▓▓▓▓
              ,▄▄▄m▀▀▀'  ,▓▓▓▀▓▓▄                           ▓▓▓  ▓▓▌
            ▄▓▓▓▀'      ▄▓▓▀  ▓▓▓      ▄▄     ▄▄ ,▄▄ ▄▄▄▄   ,▄▄ ▄▓▓▌▄ ▄▄▄    ,▄▄
          ▄▓▓▓▀        ▄▓▓▀   ▐▓▓▌     ▓▓▌   ▐▓▓ ▐▓▓▓▀▀▀▓▓▌ ▓▓▓ ▀▓▓▌▀ ^▓▓▌  ╒▓▓▌
        ▄▓▓▓▓▓▄▄▄▄▄▄▄▄▓▓▓      ▓▀      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌   ▐▓▓▄ ▓▓▌
        ▀▓▓▓▓▀▀▀▀▀▀▀▀▀▀▓▓▄     ▓▓      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌    ▐▓▓▐▓▓
          ^█▓▓▓        ▀▓▓▄   ▐▓▓▌     ▓▓▓▓▄▓▓▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▓▄    ▓▓▓▓`
            '▀▓▓▓▄      ^▓▓▓  ▓▓▓       └▀▀▀▀ ▀▀ ^▀▀    `▀▀ `▀▀   '▀▀    ▐▓▓▌
               ▀▀▀▀▓▄▄▄   ▓▓▓▓▓▓,                                      ▓▓▓▓▀
                   `▀█▓▓▓▓▓▓▓▓▓▌
                        ¬`▀▀▀█▓

        
 Version information:
  ml-agents: 0.23.0,
  ml-agents-envs: 0.23.0,
  Communicator API: 1.3.0,
  PyTorch: 1.7.1
2020-12-31 08:50:55 INFO [learn.py:275] run_seed set to 4927
2020-12-31 08:50:55 INFO [environment.py:205] Listening on port 5004. Start training by pressing the Play button in the Unity Editor.
2020-12-31 08:51:55 INFO [subprocess_env_manager.py:186] UnityEnvironment worker 0: environment stopping.
2020-12-31 08:51:55 INFO [trainer_controller.py:85] Saved Model
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/mlagents-learn", line 11, in <module>
    load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')()
  File "/Users/shammiseth/Projects/MLagents/mlagents/ml-agents/mlagents/trainers/learn.py", line 280, in main
    run_cli(parse_command_line())
  File "/Users/shammiseth/Projects/MLagents/mlagents/ml-agents/mlagents/trainers/learn.py", line 276, in run_cli
    run_training(run_seed, options)
  File "/Users/shammiseth/Projects/MLagents/mlagents/ml-agents/mlagents/trainers/learn.py", line 153, in run_training
    tc.start_learning(env_manager)
  File "/Users/shammiseth/Projects/MLagents/mlagents/ml-agents-envs/mlagents_envs/timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "/Users/shammiseth/Projects/MLagents/mlagents/ml-agents/mlagents/trainers/trainer_controller.py", line 174, in start_learning
    self._reset_env(env_manager)
  File "/Users/shammiseth/Projects/MLagents/mlagents/ml-agents-envs/mlagents_envs/timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "/Users/shammiseth/Projects/MLagents/mlagents/ml-agents/mlagents/trainers/trainer_controller.py", line 109, in _reset_env
    env_manager.reset(config=new_config)
  File "/Users/shammiseth/Projects/MLagents/mlagents/ml-agents/mlagents/trainers/env_manager.py", line 67, in reset
    self.first_step_infos = self._reset_env(config)
  File "/Users/shammiseth/Projects/MLagents/mlagents/ml-agents/mlagents/trainers/subprocess_env_manager.py", line 299, in _reset_env
    ew.previous_step = EnvironmentStep(ew.recv().payload, ew.worker_id, {}, {})
  File "/Users/shammiseth/Projects/MLagents/mlagents/ml-agents/mlagents/trainers/subprocess_env_manager.py", line 95, in recv
    raise env_exception
mlagents_envs.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
	 The environment does not need user interaction to launch
	 The Agents' Behavior Parameters > Behavior Type is set to "Default"
	 The environment and the Python interface have compatible versions.
shammis-MacBook-Air:mlagents shammiseth$ `

HI I am not able to resolve this issue can someone tell me how to change the port number because I think unity is not able to communicate with post no 5004 on Mac.

**Comment by ishitavohra3110** [comment] 2021-01-23 19:11
I am able to train the model but after the training gets finished I see the warning is shown in the Unity Editor. Can someone please help with this issue? TIA

**Comment by shohanulka** [comment] 2021-04-07 17:09
still having the same problem

**Comment by dongruoping** [comment] 2021-04-15 22:43
To conclude all the questions in the thread:

"Couldn't connect to trainer on port 5004" is a log message that tells you the editor is not connect to a python trainer and not always refers to an error, so:
1. If you're able to get the training running and you're seeing the message only at inference time (only running in the editor, no training): this message is totally normal. It's only a message saying it's not connect to trainer.

2. If you're unable to get the training started and you see the timeout error message: The error message in newer version offers more information about probable cause of this:
```
mlagents_envs.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
The environment does not need user interaction to launch
The Agents' Behavior Parameters > Behavior Type is set to "Default"
The environment and the Python interface have compatible versions.
```
So make sure you're using compatible C# and python package and set Behavior Type to "Default". Generally it's recommended to use C# and python package from the same release. Some other machine setup like firewalls and port usage might affect as well. 

To answer specific questions in the thread:
* If you need to specify a specific port, specify `--base-port` in CLI. `mlagents-learn --help` gives you more details on all the available training arguments.
* In the original post, the reason why the training is failing is pointed out in the error message in screenshot: `mlagents.trainers.exception.UnityTrainerException: Previous data from this run ID was found. Either specify a new run ID, use --resume to resume this run, or use the --force parameter to overwrite existing data.` Please make sure you're using unique ID for each training session. This should have nothing to do with connection problem and it's failing because the training session could not start due to duplicated ID.

**Comment by dongruoping** [comment] 2021-04-15 22:48
Sorry for the late reply on this thread and hope it helps. 
As I mentioned this connection problem can be caused by many possible reasons. This thread has diverted a lot from the original post and it's hard to further look into each response since each can be coming from different setup issue. Also there's no known connection issue/bug in our code and the original post seems to be a training ID error. Given all the reasons above I'm closing this issue, but feel free to reopen it if there's still problems around the original post.

For people who run into the same problem, these are some recommended steps to follow:
1. Make sure you have installed ml-agents successfully. Install C# package and python training from the same release is _strongly_ recommended.
2. Try with any of our example environment first. If you're unable to get the examples training, there might be something wrong with your installation or environment setup. 
3. If you're able to train the examples but not your own environment, make sure that the environment does not need user interaction to launch and the Agents' Behavior Parameters > Behavior Type is set to "Default"
4. If you tried all the steps above and still couldn't get it working, please open a post on our [forum](https://forum.unity.com/forums/ml-agents.453/) to ask for help, or if you believe it's a bug please report a new github issue with the details of your machine setup so we have better idea of how to help.

**Closed by dongruoping** 2021-04-15 22:48 UTC
Labels: bug
