### ISSUE TITLE
mlagents-learn --help could not run

### ISSUE THREAD

**Issue by fool1280** [Unity-Technologies/ml-agents#1747] opened 2019-02-22 06:49 UTC
> (ml-agents) C:\Users\The False Henry>mlagents-learn --help
Traceback (most recent call last):
  File "C:\Anaconda3\envs\ml-agents\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\envs\ml-agents\Scripts\mlagents-learn-script.py", line 11, in <module>
    load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')()
  File "C:\Anaconda3\envs\ml-agents\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Anaconda3\envs\ml-agents\lib\site-packages\pkg_resources\__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "C:\Anaconda3\envs\ml-agents\lib\site-packages\pkg_resources\__init__.py", line 2411, in load
    return self.resolve()
  File "C:\Anaconda3\envs\ml-agents\lib\site-packages\pkg_resources\__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\the false henry\ml-agents\ml-agents\mlagents\trainers\__init__.py", line 1, in <module>
    from .buffer import *
  File "c:\users\the false henry\ml-agents\ml-agents\mlagents\trainers\buffer.py", line 1, in <module>
    import numpy as np
  File "C:\Anaconda3\envs\ml-agents\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "C:\Anaconda3\envs\ml-agents\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Anaconda3\envs\ml-agents\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Anaconda3\envs\ml-agents\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Anaconda3\envs\ml-agents\lib\site-packages\numpy\core\__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: DLL load failed: The specified module could not be found.

I can import numpy, however the multiarray is not found. At first, I reinstall numpy using `pip install numpy` then I found out that conda handle the numpy differently, so I use `conda` instead.
Please help!

**Comment by nooootwo** [comment] 2019-02-22 07:53
I have the same problem,If you get any solution, please let me know

**Comment by xTey** [comment] 2019-02-22 08:28
I was facing the same issue.
You should uninstall the numpy 1.14.5 package:
`pip uninstall numpy`
Instead use the numpy 1.13.3 package: 
`pip install numpy==1.13.3`

That solved it for me

**Comment by vincentpierre** [comment] 2019-02-22 19:13
This does not seem to be an ML-Agents issue. https://github.com/ContinuumIO/anaconda-issues/issues/1508

**Comment by vincentpierre** [comment] 2019-02-22 19:13
Duplicate of #1701

**Closed by vincentpierre** 2019-02-22 19:13 UTC
