### ISSUE TITLE
Useless import should be removed

### ISSUE THREAD

**Issue by 13Flo** [Unity-Technologies/ml-agents#1779] opened 2019-03-02 16:50 UTC
Just a heads up -- unused import `System.Runtime.Remoting.Messaging;` should be removed from `BarracudaModelParamLoader.cs` because it generates an error in Unity 2018.3.6

**Comment by X-funbean** [comment] 2019-03-27 09:07
It generates error CS0234 in Unity 2018.3.10f1, too

**Comment by mantasp** [comment] 2019-03-27 12:05
Hi, I can't reproduce this error on my machine. Are you seeing this error in Unity or in some external editor? Could you please attach screenshot?
Thanks!

**Comment by X-funbean** [comment] 2019-03-27 12:28
@mantasp 
![image](https://user-images.githubusercontent.com/24663255/55075587-53261300-50ce-11e9-9cab-94cad0df407f.png)
and in VS2017 it says useless
![image](https://user-images.githubusercontent.com/24663255/55075743-b021c900-50ce-11e9-800a-03c8b603f769.png)

**Comment by mantasp** [comment] 2019-03-27 14:53
Thank you! turns out it's related to API compatibility setting == ".NET Standard 2.0", which is not a default for ML Agents project.

**Comment by mantasp** [comment] 2019-03-28 21:38
Fix landed to "develop" branch

**Closed by mantasp** 2019-03-28 21:38 UTC
