### ISSUE TITLE
Still having issues with VisualHallway

### ISSUE THREAD

**Issue by cxbxmxcx** [Unity-Technologies/ml-agents#1626] opened 2019-01-22 20:53 UTC
Training **VisualHallway**but the agent is still performing no actions, most of the time.  The strange thing is it has worked but then consistently fails.  

I am able to get other visual environments (Pyramids) working without issue.

I disabled recurrent and that seemed to have no effect.  Also, did a fresh clean install and reconfigured VH to use learning, perhaps it is a config issue?

Cheers,

Micheal

**Comment by eshvk** [comment] 2019-01-23 01:05
Hi @cxbxmxcx, are you using the latest ML-Agents from master?

**Comment by cxbxmxcx** [comment] 2019-01-23 14:27
Yes I am using Master, and I did another full clean install as well.

I solved the issue by converting the existing Hallway sample to use VisualHallwayLearning and it works now as expected, 

The VisualPushBlock example also is not working and appears to have the same issue as VisualHallway.  I did not try and fix it though.

As I said previously, the VisualPyramids sample works the first time as expected.

Cheers,

Micheal

**Comment by eshvk** [comment] 2019-01-23 19:49
Are you suggesting that the issue is specific to the Visual environments? 
Also, can you expand a little bit more on this:
> converting the existing Hallway sample to use VisualHallwayLearning and it works now as expected,

**Comment by eshvk** [comment] 2019-01-24 01:33
@cxbxmxcx I was able to replicate this issue, I think this is a bug in VisualHallway. I will log this and get back to you once fixed.

**Comment by moonsh** [comment] 2019-01-25 05:11
@cxbxmxcx 

It looks training for the visual pyramid environment works fine but progress is bad.
I can't see any improvement.

Should I wait for a long time or should I change something for training?

Thank you,

**Comment by cxbxmxcx** [comment] 2019-01-25 05:31
Yeah, apologies for the delay.

I converted Hallway into the VisualHallway scene with visual observations instead of vector and using a VisuslHallwayLearning brain.  After I did that the agent appeared to work as expected.

I have noticed the visual environments fall off policy and appear to start exploring again after 250000 to around 1 million iterations of training.  The agent seems to get worse, cumlative mean reward decreases, in my last couple days of testing.  Visually, I can see the agent just spin in place, almost like it is stuck picking the same action.  

My next tests are to disable recurrent and see if that helps.

Cheers,

Micheal






⁣Get BlueMail for Android ​

**Comment by cxbxmxcx** [comment] 2019-01-25 22:22
Based on my initial tests it looks like recurrent and visual learning are having issues.  

If I disable recurrent in a Visual environment I am seeing regular progressive training.  Otherwise, the agent may train for a while but then appears to just start exploring or gets appears to get stuck in a single action.

Cheers,

Micheal

**Comment by eshvk** [comment] 2019-04-03 22:31
We logged this bug and we will note in future releases when it is fixed. For now, we are closing this issue, thanks!

**Closed by eshvk** 2019-04-03 22:31 UTC
Labels: bug
