### ISSUE TITLE
RollerBall agent does not move when training

### ISSUE THREAD

**Issue by josephparis97** [Unity-Technologies/ml-agents#1888] opened 2019-04-03 18:09 UTC
Hi ! It is very frustrating because I have followed "Making a New Learning Environment" tutorial and it doesn't work. When I hit the play button my agent stay still and the cmd is saying repeatedly : 

"INFO:mlagents.trainers: RollerBall-1-0: RollerBallBrain: Step: 37000. No episode was completed since last summary. Training."

![image](https://user-images.githubusercontent.com/47667216/55501800-7fe8a600-564b-11e9-9dfa-d587622bd925.png)

![image](https://user-images.githubusercontent.com/47667216/55501856-9ee73800-564b-11e9-8ce3-b638f88e9623.png)

![image](https://user-images.githubusercontent.com/47667216/55501916-c211e780-564b-11e9-8d47-1aa998d19d3d.png)

Could Someone help me ?

**Comment by ShaneCaler** [comment] 2019-04-03 21:19
Have you tried removing RollerballPlayerBrain from the academy? Maybe it's waiting for some input from that to train the learning brain? I haven't messed much with player brains, though, so I'm not totally sure what the problem is.

**Comment by josephparis97** [comment] 2019-04-03 21:27
I have tried to remove the RollerballPlayerBrain but nothing changed.
I forgot to put the pictures off the cmd
![image](https://user-images.githubusercontent.com/47667216/55514294-fbf0e700-5667-11e9-87d5-445f067c8e3f.png)
![image](https://user-images.githubusercontent.com/47667216/55514326-15922e80-5668-11e9-84d4-b55ef3eed090.png)

**Comment by josephparis97** [comment] 2019-04-03 21:34
I think that the learning brain never takes any decision because vectorAction is always equal to zero. I don't know why

**Comment by ervteng** [comment] 2019-04-03 22:32
Hey @josephparis97, what Brain is assigned to the Agent game object? It should be the Learning brain, not the Player Brain.

**Comment by josephparis97** [comment] 2019-04-04 05:02
Oh you are right !!!!! The learnig brain was not assigned ! It was the player brain! thank you so much ! But now it is moving frame by frame, I there a way to make it more fluid ?
![roller agent](https://user-images.githubusercontent.com/47667216/55530643-2d3cd780-56a7-11e9-8cdd-fa0a9b86c3e2.gif)

And I have another question, my training process stopped without me. Why ?
![image](https://user-images.githubusercontent.com/47667216/55530719-8278e900-56a7-11e9-8a68-5460ff768e84.png)

**Comment by ervteng** [comment] 2019-04-04 21:06
Ah, that's because it's training! The rendering is slow but you're getting many more steps. When you're happy with the reward it's getting, run ml-agents with the --load and --slow flags and it'll run at realtime.

**Comment by josephparis97** [comment] 2019-04-04 21:14
ok thank you really much !!! This ml agent IA toolkit is really cool ! I  am actually trying to create littles creatures like this one :)
![creature1](https://user-images.githubusercontent.com/47667216/55588918-5012ce80-572f-11e9-9094-46a122bb8ce5.gif)

**Comment by warpdriv** [comment] 2019-04-10 17:41
Bug in instructions: 
https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Create-New.md

Section : Final Editor Setup - Step 3. It says:
Drag the Brain RollerBallPlayer from the Project window to the RollerAgent Brain field.

Should say:
Drag the Brain RollerBallBrain from the Project window to the RollerAgent Brain field.

Please someone correct this. Thank you.

**Comment by buddha314** [comment] 2019-04-27 00:16
I just lost two days to this error.  Man oh man.  I read that line four times because it seemed wrong and then I forgot about it.  Poop.  Poop poop procreating poop.

**Comment by unityjeffrey** [comment] 2019-04-29 15:37
made a PR here to fix in develop

https://github.com/Unity-Technologies/ml-agents/pull/1993

**Comment by unityjeffrey** [comment] 2019-05-29 22:46
Thanks for reaching out to us. Hopefully you were able to resolve your issue.  We are closing this due to inactivity, but if you need additional assistance, feel free to reopen the issue.

**Closed by unityjeffrey** 2019-05-29 22:46 UTC
