### ISSUE TITLE
Couldn't connect to trainer on port 5004 using API version 0.15.0

### ISSUE THREAD

**Issue by atapley** [Unity-Technologies/ml-agents#3804] opened 2020-04-18 23:13 UTC
**Describe the bug**
I am getting the above error when trying to train my own custom environment. 

**To Reproduce**
I have been getting this error numerous times, even after cloning a new repo and reinstalling.

I cloned the repo (latest release) onto my laptop. I installed the dependencies following the development instructions on the installation doc into an Anaconda env. I then created my own environment in Unity. I was able to train the environment with no issues. However, I decided I wanted to save off the images from my visual observations to my laptop, so I installed opencv with "conda install opencv". I then went into ml-agents-env/base_env.py and added a line to save off the images. However, once I tried to start training again, I got the error. After deleting the line from base_env.py, I am still getting the error and cannot train.

In the past, I have deleted the repo and recloned it, and I am usually able to run the examples without any issues. Usually, once I run my own environment, I run into the issue where the trainer cannot connect. I was finally able to get it to run this morning without the issue (somehow) but it came back once I attempted to add a line to the file. 

**Console logs / stack traces**
<img width="491" alt="Screen Shot 2020-04-18 at 5 23 20 PM" src="https://user-images.githubusercontent.com/23152013/79671708-8f755700-819a-11ea-89bd-494c35e2b659.png">

This is from the ~/Library/Logs/Unity/upm.log file.

**Screenshots**
<img width="940" alt="Screen Shot 2020-04-18 at 5 23 49 PM" src="https://user-images.githubusercontent.com/23152013/79671704-8ab0a300-819a-11ea-8a45-55966096008f.png">

This is what shows up when I run the mlagents-learn.

<img width="634" alt="Screen Shot 2020-04-18 at 5 17 40 PM" src="https://user-images.githubusercontent.com/23152013/79671709-913f1a80-819a-11ea-9382-40c288c1e62f.png">

This is what I get in the console inside of Unity.

<img width="783" alt="Screen Shot 2020-04-18 at 5 24 00 PM" src="https://user-images.githubusercontent.com/23152013/79671713-956b3800-819a-11ea-8de8-0784b1d81b7f.png">

This is the error I get on the terminal side.

**Environment (please complete the following information):**
- OS + version: Mac 10.15.3 (Catalina)
- _ML-Agents version_: latest release (0.15.1)
- _TensorFlow version_: 2.0.1
- _Environment_: 3D-Ball, or any environment actually

**Comment by atapley** [comment] 2020-04-20 14:06
I was able to get rid of the error once again by deleting and recloning the repo/creating a new python venv and installing the dependencies in ml-agents-envs and ml-agents. I was able to train my model with no issues on my custom environment. However, once I changed a line to the config.yaml file within my own directory (completely separate from ml-agents repo), I got the error again. Recloning the repo and creating a new venv solves the problem.

It seems like whenever I make a change within my project or the ml-agents project, this error shows up.

**Comment by anupambhatnagar** [comment] 2020-04-20 17:36
@atapley looks like you have been able to resolve the issue. It's not a bug but an installation issue. I'll be closing the issue.

**Closed by anupambhatnagar** 2020-04-20 17:36 UTC
Labels: bug

**Comment by atapley** [comment] 2020-04-20 17:39
The issue has not been resolved though. Every time I make a change to a project, I get the error and I have to re-clone the repo and re-install all dependencies. Maybe it is an installation issue, but I'm following all of the directions in the docs and still getting it. Do you have any insights into why exactly that could be?

**Comment by anupambhatnagar** [comment] 2020-04-20 17:56
I'll try to reproduce the issue you are having. We use github issues for bugs and feature requests only. I recommend you post the issue on the ML-Agents forum. https://forum.unity.com/forums/ml-agents.453/ We can continue the discussion there.
